### ISSUE TITLE
如何给不同的节点添加不同的链接地址？

### ISSUE THREAD

**Issue by Okswwen** [hizzgdev/jsmind#100]
书写topic中，如何使不同的节点上，链接到不同的地址中，在addNode()函数中，我好像仅仅能书写唯一的地址，谢谢~

**Comment by hizzgdev** [comment]
为什么呢？

**Comment by Okswwen** [comment]
换个说法，我每次添加新节点，都需要去调整addNode()中的代码吗？进而用来实现跳转不同的目的地址！

**Comment by hizzgdev** [comment]
因为每个node的文本和链接都不一样，所以你要构造不同的topic。

**Comment by Okswwen** [comment]
恩，会有点繁琐，倘若25个节点，重复工作会很多！谢谢~
