### ISSUE TITLE
【React应用】节点上添加事件

### ISSUE THREAD

**Issue by MrZhangFengfeng** [hizzgdev/jsmind#101]
请问能否在节点上调用jsmind外部的事件。例如

`<button onclock="functionClick()">`  

目前我没有实现。 求助，谢谢。
注：我是在react组件内使用的。

**Comment by MrZhangFengfeng** [comment]
补充。对应一个节点的代码：
` {"id":"easy1","topic":"<button onclick=functionClick1()'>hello</button>"},`
` {"id":"easy2","topic":"<button onclick=functionClick2()'>hello</button>"},`

**Comment by MrZhangFengfeng** [comment]
发现可以这样做
`<a href='javascript:del()' value="hello">hello</a>`
`a{
  display:inline-block;
  width:50px;
  line-height:24px;
  padding:5px;
  background:#ccc;
  border:1px solid #ccc;
  text-decoration: none
}`
`function del(){
  alert("111")
}`

**Comment by xiaohuoz** [comment]
你可以在jsmind_container那个div加点击事件，然后调用jsMind.current来获取数据的。

**Comment by MrZhangFengfeng** [comment]
@xiaohuoz 但是这种方法针对的是真个jsmind，而我要给jsmind的每个节点添加不同的方法。

**Comment by hizzgdev** [comment]
感谢 @MrZhangFengfeng  @xiaohuoz 的关注与支持。
我并没有在 react 环境下对 jsmind 进行过验证，如果 @MrZhangFengfeng 的实践有效的话，请在此回复一下，这样如果再有别人遇到同样的问题，便可参考你的解决方案了。
谢谢。

**Comment by xiaohuoz** [comment]
在react中，应该是没办法把组件内部事件直接传入jsmind，我把在jsmind_container上绑定事件出现的问题及解决方案说一下哈。
1. 点击事件需要区分开选中的html元素，点击空白处元素名JMNODES，点击节点上JMNODE，导航条上是DIV，自己在节点内写的html元素要判断。
2. 监听鼠标右键用到onMouseDown与onContextMenu，onMouseDown先触发，如果更新了state，会导致onContextMenu不触发，浏览器默认菜单会显示出来。解决方案是在父组件中在包含该组件的html节点上监听onContextMenu阻止掉onContextMenu。
3. 右键弹出模态框输入时，发现输入框内键盘左右空格用不了，我直接把jsmind内的快捷键禁用了。不知道有没有其他解决方案。

**Comment by xdwxls** [comment]
@xiaohuoz 你好，请问你是如何在react 项目中引用jsmind 的？

**Comment by xiaohuoz** [comment]
npm install jsmind --save；
然后引入进来 import JsMind from 'jsmind';
在componentDidMount中处理就行了

**Comment by guoxiangwen** [comment]
报错了
![image](https://user-images.githubusercontent.com/7627191/38225913-a6533a0e-3729-11e8-87f7-a258c1bce345.png)

```
  componentDidMount() {
    console.log(document.querySelector("#jsmind_container"))
    var mind = {
      // 3 data formats were supported ...
      // see Documents for more information
    };
    var options = {
      container: "jsmind_container",
      theme: "orange",
      editable: true
    };
    var jm = new jsMind(options);
    jm.show(mind);
  }
  render() {
    const { state, getDemand } = this.props;
    return (
      <div id="jsmind_container">
        
      </div>
    );
  }
```

**Comment by miliwang** [comment]
@xiaohuoz 你好，请问想将动态元素添加到节点上，但是我用获取dom的方式都获取不到，$("jmnode") 就选中了所有的，每次追加所有的都追加了一遍，请问有什么解决办法吗？

**Comment by wtligit** [comment]
@guoxiangwen 
信息显示你没有name值啊，所以你要在mind里面放入相应的数据。你把基本用法-树对象格式示例的内容粘到你的mind里面，就可以了。然后这个时候前端显示的mind应该是乱的，你把CSS import进来，然后给div设尺寸属性值，像这样<div id="jsmind_container" style={{margin:'auto', width:'1500px',height:'500px',background:'#f4f4f4'}}></div>就ok了

**Comment by xxc03** [comment]
react 使用报错
![Uploading WechatIMG260.jpeg…]()

**Comment by xxc03** [comment]
react 报错
![WechatIMG260](https://user-images.githubusercontent.com/39787035/56954357-2eabd380-6b71-11e9-8814-d0212b45631b.jpeg)
