### ISSUE TITLE
关于高度过高  canvas  线条不显示的问题

### ISSUE THREAD

**Issue by JavaZWT** [hizzgdev/jsmind#102]
您好，我发现使用jsmind 时，当超过一定高度时，会画不出线来，我查阅资料发现浏览器对  canvas的 尺寸做了限制，高度 为  32767 px  ，请问有什么方法解决这个问题吗？

**Comment by hizzgdev** [comment]
通过多个canvas拼合，或者局部重绘+自定义滚动的方式应该可以解决这个问题，不过都需要比较大的重构。
