### ISSUE TITLE
有什么办法能够根据节点点开的内容自动调整div的高度？

### ISSUE THREAD

**Issue by crackeryk** [hizzgdev/jsmind#104]
我看到文档介绍中要求每次使用的时候需要定义div标签的高度
那么通过什么方法能够让他自动缩进？
定义了一个jm对象，通过jm.view.size.h能够看到展开的高度，但是缩小后这个高度并没有发生变化，
又没有什么解决办法？

**Comment by lpcsmile0125** [comment]
先展开，再收缩

**Comment by hizzgdev** [comment]
一般一个脑图的显示窗口（jsmind_container）大小应该是固定的，如果需要显示窗口随浏览器的窗口动态变化的话，建议在 window.resize事件里重置一下 jsmind_container 的 style.width/height。

参考url:  http://jsmind.sinaapp.com/  (http://jsmind.sinaapp.com/static/scripts/index.js)

**Comment by hizzgdev** [comment]
jm.resize 或许能解决你的问题 https://github.com/hizzgdev/jsmind/blob/master/js/jsmind.js#L1644
