### ISSUE TITLE
jsmind中add_node 放在for循环中，批量增加 js会卡死

### ISSUE THREAD

**Issue by lpcsmile0125** [hizzgdev/jsmind#105]
请问。当for循环中 循环次数大于30个时，插件经常卡死。有没有批量插入节点数组的方法？截图，发到你163邮箱了

**Comment by lpcsmile0125** [comment]
你们在for循环中 调用 add_node 的时候，出现过卡死吗。急

**Comment by lpcsmile0125** [comment]
用最新版本的。不会卡死。之前用的可能是网上别人改动过的。但是支持 虚线箭头。咱们的 曲线大括号能随便改吗

**Comment by hizzgdev** [comment]
能否给出示例代码？
