### ISSUE TITLE
jmnodes元素与canvas是什么关系（上下层关系）

### ISSUE THREAD

**Issue by szdbb1102** [hizzgdev/jsmind#107]
您好志刚兄
观察了一下demo，是在canvas同级自定义了jsmind的html元素，但是在下面还有一个同样的canvas元素
能否告知一下整体的实现思路，jmnodes元素与canvas是什么关系，是否没有canvas也一样的？或者是用于保存图片，可否理解为jsmind的计算逻辑都在jmnodes中？

**Comment by hizzgdev** [comment]
canvas仅用于显示连接线。jmnodes是一个容器，容纳所有的jmnode。
