### ISSUE TITLE
怎么直接保存为xmind的文件（浏览器端不便实现）

### ISSUE THREAD

**Issue by lunanjack** [hizzgdev/jsmind#108]
xmind的数据结构怎么搞？

**Comment by lunanjack** [comment]
求教 lunanjackln@163.com

**Comment by xdsnet** [comment]
参考 http://www.xmindchina.net/xinshou/xmind-wenjian-geshi.html
需要写xml
还要zip压缩

**Comment by hizzgdev** [comment]
感谢 @lunanjack  @xdsnet 关注与支持。
