### ISSUE TITLE
每一个节点怎么加一个弹窗，并自定义里边的内容

### ISSUE THREAD

**Issue by ybx13579** [hizzgdev/jsmind#109]
每一个节点鼠标滑上去，旁边能不能出来一个弹窗，现在不晓得怎么写，有思路吗？ 需要加文字和 图片

补充：需要保留编辑功能

**Comment by huoji555** [comment]
每个节点设置节点的id(新建节点的时候就可以生成节点id了，可以用日期生成),    调用jsmind中的jm. get _n ode (nodeid) 方法，可以获取当前id的值，根据节点中提供的属性（比如说该节点的id号），绑定一个JQuery事件，弹出一个框。需要进一步了解的话，可以发邮件  961946407@qq.com

**Comment by hanxiaomax** [comment]
是类似这样的效果吗？
https://hanxiaomax.github.io/WordPowerMadeEasy/

**Comment by ybx13579** [comment]
@hanxiaomax  啊 对 文字加图片 就类似这样的，您写的例子方便给我一份吗 谢谢

**Comment by hanxiaomax** [comment]
https://github.com/hanxiaomax/WordPowerMadeEasy

我用的是bootstrap的popover，其实就是你生成的节点里面，内容直接填html
```
<div data-toggle='popover' data-content='n. 谄媚；奉承；追随；拍马屁'>sycophancy</div>
```
```
{
            "topic": "<div data-toggle='popover' data-content='fig'>sykon</div>", 
            "expanded": false, 
            "id": 2, 
            "children": [
              {
                "topic": "<div data-toggle='popover' data-content='n. 谄媚；奉承；追随；拍马屁'>sycophancy</div>", 
                "expanded": false, 
                "id": 3, 
                "children": []
              }
            ]
          }, 
```

**Comment by ybx13579** [comment]
@hanxiaomax 我需要保留编辑功能  直接编辑节点会不会把添加的html直接删除了

**Comment by hanxiaomax** [comment]
是会删除的

**Comment by chrisliee** [comment]
@ybx13579 hi,你有解决保留编辑功能，并且节点可以自定义么？如果有，可以交流下么
