### ISSUE TITLE
子节点能否添加纵向布局

### ISSUE THREAD

**Issue by chenhuaping** [hizzgdev/jsmind#111]
目前只能左右布局子节点，是否可以添加可以纵向布局的模式

**Comment by hizzgdev** [comment]
参考一下这个，看是不是你想要的效果：https://github.com/hizzgdev/jsmind/issues/56

**Comment by jakiechen2001** [comment]
是的，就是这个需求。我现在使用了一种取巧的方案现实现了，就是将脑图区域的div整体向右旋转90度。旋转之后也带来很多问题，调试了好久，不过基本也可用了。

**Comment by jakiechen2001** [comment]
你们真正实现垂直显示的方案现在还在开发中是吧？

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
