### ISSUE TITLE
节点拖拽完成以后会触发哪个钩子

### ISSUE THREAD

**Issue by zhangyuntao1** [hizzgdev/jsmind#112]
节点拖拽完成以后会触发哪个钩子，还有就是一些点击事件该怎么应用呢，求解答

**Comment by huoji555** [comment]
能给个邮箱地址联系一下吗，最近也在解决这个问题，希望和你讨论一下

**Comment by hizzgdev** [comment]
目前并未提供拖拽完成事件，如果需要，可以参考源码中的 event_type 自行添加，欢迎提交 pull-request
