### ISSUE TITLE
shortcut方法里添加了键盘事件，在弹窗中有keydown操作，怎么阻止默认事件

### ISSUE THREAD

**Issue by zhangyuntao1** [hizzgdev/jsmind#113]

**Comment by hizzgdev** [comment]
阻止默认事件的意思是要禁用快捷键吗？不太清楚冲突在哪里，你可以试试在配置中禁用快捷键看能不能达到你想要的效果。

[2.4. 快捷键](https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md#24-%E5%BF%AB%E6%8D%B7%E9%94%AE)

**Comment by asdfghjkl01** [comment]
这个问题在修改节点内容时我也遇到了，弹窗打开时，让快捷键禁用，jm.shortcut.opts.enable=false;关闭弹窗时，启用快捷键，jm.shortcut.opts.enable=true;
