### ISSUE TITLE
请问，我想在  线上 添加文字

### ISSUE THREAD

**Issue by zylbiubiubiu** [hizzgdev/jsmind#115]
![111](https://user-images.githubusercontent.com/25952486/35023056-f515033a-fb73-11e7-9b2c-a4d0bae482ed.png)

如图，就是想在线上添加 文字说明 对应的关系。
有相应的api么？

或者有什么方式可以更好的实现？

**Comment by hizzgdev** [comment]
jsMind暂不支持，如果实现，欢迎提交 pull-request
