### ISSUE TITLE
Callbacks?

### ISSUE THREAD

**Issue by olimart** [hizzgdev/jsmind#119]
Hi,
very impressive work. Thank you.

- Is there any callback event triggered when a node is added/removed/modified?
- Is there a means to know node's 'level' when adding a new node? (i.e. level 3). Or maybe how many parents the node has?

**Comment by yatarphae** [comment]
Hi, @olimart, I had a similar question with you. And I found a method `add_event_listener`, and the code calling event handlers `this.event_handles[i](type,data)` in method `_invoke_event_handle`. So we can just call `jm.add_event_listener((type,data)=>{/**/}) ` to add a callback. Supported event types are specified in `jsMind.event_type`. Hope this will help you :-)

**Comment by olimart** [comment]
@yatarphae Thank you

**Comment by olimart** [comment]
@yatarphae by chance, do you know a way to get node's level?

**Comment by hizzgdev** [comment]
@olimart 
 jsMind does not provide a property to indicate node's level, but it is not very hard to calculate.

```javascript
function (node){
    var depth = 1;
    while(!node.isroot){
        depth ++;
        node = node.parent;
    }
    return depth;
}
```

BTW, would you mind to tell me the reason why you want to get it? maybe it is a very useful property.

**Comment by olimart** [comment]
Thanks @hizzgdev I will give it a try.

My use case is simple. I'd like to style n2+ nodes differently (like XMind Zen themes). Where it gets more difficult is when node are dragged to a different parent.
