### ISSUE TITLE
Link 2 nodes to a single node

### ISSUE THREAD

**Issue by brenopolanski** [hizzgdev/jsmind#121]
It's possible link 2 nodes to a single node? Like this:

![screenshot from 2018-03-16 11-17-07](https://user-images.githubusercontent.com/1894191/37525428-95a737ae-290b-11e8-90a3-34d395c1343a.png)

**Comment by ttsdzzg** [comment]
I'm sorry, jsMind does not provide support for this feature.

**Comment by hizzgdev** [comment]
I'm sorry, jsMind does not provide support for this feature.

**Comment by brenopolanski** [comment]
no problems @hizzgdev! Thanks :+1:
