### ISSUE TITLE
根节点和展开收缩标识错位

### ISSUE THREAD

**Issue by ass233** [hizzgdev/jsmind#122]
想咨询下根节点错位，往右移动部分太多直接遮挡住了子节点，并且子节点的收缩表示直接跑到了左上角，实际应该在右边才对，请问怎么修改这个样式问题，不应该直接修改源码样式吧？有jsmind    QQ技术群吗 可以交流技术的

**Comment by hizzgdev** [comment]
能不能描述具体的用例
