### ISSUE TITLE
Vue下怎么使用拖拽功能？

### ISSUE THREAD

**Issue by evangerlions** [hizzgdev/jsmind#123]
使用npm安装jsmind，然后在.vue文件中  
`import "jsmind/style/jsmind.css";
import jsMind from "jsmind";`  
这样虽然可以使用大部分功能，但是不支持拖拽（吐槽一下，第一个jsmind.css不引入无法工作）
再`import “jsmind/js/jsmind.draggable.js”`依旧无效。快捷键我没有试，估计和拖拽一样。
请问在Vue环境下使用拖拽功能？

**Comment by dandelion1000** [comment]
同问这个问题，我这里vue引了这个拖拽功能也无效

**Comment by gefangshuai** [comment]
引了起作用的，亲测有效！
```
    import '../../../libs/jsmind/js/jsmind';
    import '../../../libs/jsmind/js/jsmind.draggable';
    import "../../../libs/jsmind/style/jsmind.less";
```

**Comment by DCsunset** [comment]
用npm安装，import “jsmind/js/jsmind.draggable.js” 之后也没有拖拽能够起作用，
但是其他功能均正常。

**Comment by pycodev** [comment]
react 可以这样
```js
global.jsMind = require('jsmind')
require('../../../../node_modules/jsmind/js/jsmind.draggable')
```

**Comment by ccchhhccc** [comment]
import jsMind from 'jsmind'

then  global.jsMind = jsMind
and   require('jsmind/js/jsmind.draggable.js')
投机取巧的解决方法

**Comment by dandelion1000** [comment]
谢谢各位的回复，我将文件目录下载到本地，通过import方式将其引入项目中可以，然而如果直接通过npm安装，import  jsmind，只能jsmind.js文件生效

**Comment by zwmmm** [comment]
原因就是使用了import jsMind就不会挂在到window了 修改下源码即可

**Comment by zwhid** [comment]
> 原因就是使用了import jsMind就不会挂在到window了 修改下源码即可

怎么修改呢？

**Comment by zwhid** [comment]
> 原因就是使用了import jsMind就不会挂在到window了 修改下源码即可

请问怎么修改呢？

**Comment by zwmmm** [comment]
```js
// export jsmind
    if (typeof module !== 'undefined' && typeof exports === 'object') {
        module.exports = jm;
    } else if (typeof define === 'function' && (define.amd || define.cmd)) {
        define(function() { return jm; });
    }
    $w[__name__] = jm;
```
@zwhid

**Comment by zwhid** [comment]
感谢！ @zwmmm

**Comment by bymomo** [comment]
// 导入jsmind相关依赖
import "common/js/jsmind/jsmind.css";
import jsMindMap from 'common/js/jsmind/jsmind.js';
window.jsMind = jsMindMap;
// 一定要放最后，也就是等jsmind挂载到全局后
require('common/js/jsmind/jsmind.draggable.js')

**Comment by jiangtwelve** [comment]
import "../common/jsmind.css";
import jsMindMap from '../common/jsmind.js';
window.jsMind = jsMindMap;
require('../common/jsmind.draggable.js')

使用这种引入报错了
jsMind is not a constructor

请问有解决的方案嘛

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
