### ISSUE TITLE
建议添加toggle_node、expand_node触发事件

### ISSUE THREAD

**Issue by 1394230111** [hizzgdev/jsmind#126]
toggle_node:function(node){
            if(!jm.util.is_node(node)){
                var the_node = this.get_node(node);
                if(!the_node){
                    logger.error('the node[id='+node+'] can not be found.');
                    return;
                }else{
                    return this.toggle_node(the_node);
                }
            }
            if(node.isroot){return;}
            this.view.save_location(node);
            this.layout.toggle_node(node);
            this.view.relayout();
            this.view.restore_location(node);

            ///////
            this.invoke_event_handle(jsMind.event_type.edit, { evt: 'toggle_node', data: [], node: node.id });
            ///////
        },

        expand_node:function(node){
            if(!jm.util.is_node(node)){
                var the_node = this.get_node(node);
                if(!the_node){
                    logger.error('the node[id='+node+'] can not be found.');
                    return;
                }else{
                    return this.expand_node(the_node);
                }
            }
            if(node.isroot){return;}
            this.view.save_location(node);
            this.layout.expand_node(node);
            this.view.relayout();
            this.view.restore_location(node);

            ///////
            this.invoke_event_handle(jsMind.event_type.edit, { evt: 'toggle_node', data: [], node: node.id });
            ///////
        },

**Comment by caitao-ct** [comment]
我想添加节点的选中事件, 请问加上你的这段就可以实现吗, 在哪里添加, 感谢!

**Comment by ForeverS2C** [comment]
> 我想添加节点的选中事件, 请问加上你的这段就可以实现吗, 在哪里添加, 感谢!

在哪添加？你知道了吗？

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
