### ISSUE TITLE
Special request

### ISSUE THREAD

**Issue by evenmind** [hizzgdev/jsmind#128]
Hi, I have an special request. I implemented 2 types of nodes and I want to align the nodes depending on it's type.

What I have:
![Image of mindmap](https://image.ibb.co/kJQe17/mindmap1.png)

What I want:
![Image of mindmap](https://image.ibb.co/gTh3Tn/mindmap2.png)

Do you do a special développements on request ? (Paid of course).
Or if not, how can I achieve this ?

You can contact me on contact@even-mind.com

**Comment by hizzgdev** [comment]
close on expired
