### ISSUE TITLE
怎么获取节点后给节点添加事件？

### ISSUE THREAD

**Issue by zhuangbb0** [hizzgdev/jsmind#129]
怎么获取节点后给节点添加事件？

**Comment by miliwang** [comment]
@zhuangbb0，你好，请问你的问题解决了吗？我想在节点上追加动态元素，不知道怎么操作

**Comment by gaoyibin0001** [comment]
_jm.view.add_event(_jm,'mouseover',mouse_over);

function mouse_over(e){
        var element = e.target || event.srcElement;
        var nodeid = _jm.view.get_binded_nodeid(element);
        if(!!nodeid){
                this.select_node(nodeid);
            }
            else{
                this.select_clear();
            }
    }

**Comment by ForeverS2C** [comment]
> @zhuangbb0，你好，请问你的问题解决了吗？我想在节点上追加动态元素，不知道怎么操作

你们都解决了吗？我想知道节点的点击事件怎么设置

**Comment by hizzgdev** [comment]
建议直接在 #container 上增加事件，通过冒泡取得 event.target，再进行后续处理

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
