### ISSUE TITLE
怎么将动态的元素追加到某个子元素上

### ISSUE THREAD

**Issue by miliwang** [hizzgdev/jsmind#131]
想在节点上添加一个按钮，但是问题是，$("jmnode") 选中的是所有的元素，怎么才能选中固定的那个，dom元素的方式都试过了失败，还是应该操作他的节点吧？求解答

**Comment by miliwang** [comment]
追加：
  因为看到作者说，jsmind 支持html，所以在添加内容时候，直接添加的 html 标签字符串，虽然实现了动态添加元素，但是总觉得这样还是有点缺陷。

**Comment by wtligit** [comment]
直接给div加点击事件，在handleClick中用jm.get_selected_node()就可以获取当前选中的节点

**Comment by hizzgdev** [comment]
close on expired
