### ISSUE TITLE
Allow multi line nodes

### ISSUE THREAD

**Issue by lucasrogeriomasotti** [hizzgdev/jsmind#133]
Anyone also thinks we should allow multi line nodes?
Sometimes the user may want to write a lot of words in a single node.

I tried messing around with the code a bit but couldn't get it to work.If other people are interested too, I may try again.

**Comment by huoji555** [comment]
First of all, I very much agree with your point of view, you can refer to the next kitty-mind. I tried to use another idea. Click on each node to display extra content by popping up.

**Comment by hizzgdev** [comment]
close on expired
