### ISSUE TITLE
有人实现过画布拖动吗？

### ISSUE THREAD

**Issue by wjfei** [hizzgdev/jsmind#136]
拖动画布空白区域，所有的节点位置都会改变

**Comment by Hongmy0** [comment]
可以看一下我这个demo  https://github.com/Hongmy0/jsMind-.git我初步实现了canvs拖动的功能

**Comment by WalkerHJ** [comment]
我利用的JQ的拖动插件。
![image](https://user-images.githubusercontent.com/35361255/63499679-e8e99100-c4fa-11e9-93eb-0edd7261354b.png)
![image](https://user-images.githubusercontent.com/35361255/63499698-f3a42600-c4fa-11e9-92da-419f234920be.png)

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
