### ISSUE TITLE
请问可以显示脑图，但屏幕截屏中一旦画布高度在8000px以上就不能显示任何节点为什么，谷歌浏览器

### ISSUE THREAD

**Issue by asdfghjkl01** [hizzgdev/jsmind#142]

**Comment by hizzgdev** [comment]
"屏幕截屏" 指的是什么？

**Comment by asdfghjkl01** [comment]
screen_shot(),作为一个图片导出脑图

**Comment by hizzgdev** [comment]
我在这个测试环境上简单测试了一下，并没有出现这个情况。
http://hizzgdev.github.io/jsmind/example/2_features.html

**Comment by asdfghjkl01** [comment]
那可能是我自己的问题，谢谢啦

**Comment by asdfghjkl01** [comment]
我在你的测试环境上直接导入.jm文件测试发现，不是高度的问题，是大小，不能超过1.5MB

**Comment by hizzgdev** [comment]
是什么不能超过1.5MB？
超过8000px的部分能显示吗？

**Comment by asdfghjkl01** [comment]
作为.png文件的大小，一旦接近1.5MB，图片整体空白。

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
