### ISSUE TITLE
请问如何在页面中显示多个脑图？

### ISSUE THREAD

**Issue by zhangxiaoda007** [hizzgdev/jsmind#145]
您好，
   我想请问如何在一个容器中显示多个脑图并调整到想要的位置？在html文件中加入新的脑图即使使用同一个容器也只能固定在上图下面的位置而无法根据要求进行调整。

**Comment by hizzgdev** [comment]
关于如何在页面中显示多个脑图的回答：

1. 在页面添加多个容器
2. new JsMind() 时传入的 option 指定不同的容器

关于调整脑图位置的回答：

容器的位置请使用样式表进行控制，可以先把jsmind的功能去掉，将容器调整到指定位置后再添加 jsmind

**Comment by zhangxiaoda007** [comment]
感谢您！问题已经解决。
