### ISSUE TITLE
为什么点击+/-号收放节点时会选中父节点

### ISSUE THREAD

**Issue by suhao666** [hizzgdev/jsmind#146]

**Comment by zwmmm** [comment]
![image](https://user-images.githubusercontent.com/30194521/49361494-2a40d300-f717-11e8-8f6b-113712359b33.png)
![image](https://user-images.githubusercontent.com/30194521/49361506-3036b400-f717-11e8-96fd-b288963a4c43.png)
修改源码可以解决

**Comment by zg08** [comment]
可以配合组件使用吗
