### ISSUE TITLE
怎么把一个节点和它下面所有的子节点，子节点的子节点等等，复制一份到指定节点下面？

### ISSUE THREAD

**Issue by fstg0504** [hizzgdev/jsmind#147]
比如节点1，有子节点，子节点下面也有子节点等等一堆节点；
然后要把这个节点1和它的子节点全部信息复制到其他节点下面；
jm.add_node(parent_node, nodeid, topic, data) 好像只可以添加一个节点到父节点下面；
那节点1下面的谁有的节点我需要便利它的children集合一个个添加吗？
如果不知道节点1下面有多少层级咋办呢？

**Comment by perseverancer** [comment]
递归

**Comment by hizzgdev** [comment]
复制节点需要自行包装，每个节点都有自己的ID，复制节点不同于移动，需要使用新的ID，这也是需要你处理的地方。
