### ISSUE TITLE
将pspace调大之后，折叠按钮偏上移动了，尚未解决

### ISSUE THREAD

**Issue by sweet-yaya** [hizzgdev/jsmind#148]
只有pspace=13的时候居中心，但是节点与连接线之间的水平间距太小，有没有解决办法

**Comment by sweet-yaya** [comment]
![default](https://user-images.githubusercontent.com/22144229/45810385-20552980-bcfd-11e8-8786-5f3bddbb8fa4.png)

这是设置为50的时候  空隙正好，但是按钮偏上

**Comment by sweet-yaya** [comment]
这是设置为默认13的时候，按钮位置适中，但是节点与连接线之间太近了
![111](https://user-images.githubusercontent.com/22144229/45810661-b8eba980-bcfd-11e8-8a56-3fe852ee7c80.png)

**Comment by hizzgdev** [comment]
因太久没有更新而关闭，如有需要请 reopen 这个 issue
