### ISSUE TITLE
vue中使用get_selected_node（）如何绑定事件？

### ISSUE THREAD

**Issue by zhangxiaoda007** [hizzgdev/jsmind#151]
您好：
请问我在vue中使用jsmind，希望在每个节点处添加一个点击事件，使其有弹出框的效果该如何做？看了一下文档，我在methods中添加
`methods：｛load_jsmind:function(){
            var jm = jsMind.show(this.options,this.mind);     
            var vm = jm.get_selected_node();
        }｝`
不知道后面该如何绑定事件呢？我试过vm.onclick=function(){}但是没有反应。

**Comment by MiRECoFu** [comment]
get_selected_node 返回的是个js对象。。不是dom

**Comment by chuwu0** [comment]
this.jm.selected_node = this.ownFun
