### ISSUE TITLE
线条模糊怎么解决

### ISSUE THREAD

**Issue by zzlw** [hizzgdev/jsmind#153]
线条模糊怎么结解决

**Comment by hizzgdev** [comment]
你可以试试画粗点儿，或许就不会显得模糊了，调整的话代码还比较容易找，你试试。

**Comment by suwu150** [comment]
看着线条好像是跟节点颜色最深,越到叶子节点颜色越浅,感觉有点重复画线的样子.不知道有没有解决办法,
![image](https://user-images.githubusercontent.com/20339760/58848860-a1512700-86ba-11e9-88a1-bb592dc4a0db.png)
