### ISSUE TITLE
该思维导图支持设置两个根节点吗？

### ISSUE THREAD

**Issue by chuwu0** [hizzgdev/jsmind#155]
![image](https://user-images.githubusercontent.com/23164531/48039323-3c2e6500-e1af-11e8-96d1-9bb1025fa15f.png)
类似这种的设置

**Comment by chuwu0** [comment]
现在这个都是我根据数据用canvas绘画的，想改成类似思维导图的形式，但我发现该插件好像不支持多个根节点

**Comment by hizzgdev** [comment]
如果你试验成功了，欢迎你提pull-request
