### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by xudai3** [hizzgdev/jsmind#156]
react怎么使用拖拽功能呀,import了jsmind-draggable.js还是不行

**Comment by zwmmm** [comment]
改下源码 吧jsMind暴露到全局
![image](https://user-images.githubusercontent.com/30194521/48594910-9d172380-e98d-11e8-9986-da75ba429ea5.png)

**Comment by suwu150** [comment]
> 改下源码 吧jsMind暴露到全局
> ![image](https://user-images.githubusercontent.com/30194521/48594910-9d172380-e98d-11e8-9986-da75ba429ea5.png)

然后呢,然后怎么处理?

**Comment by hizzgdev** [comment]
@suwu150  Thanks
