### ISSUE TITLE
如何实现部分可以编辑的功能

### ISSUE THREAD

**Issue by zwmmm** [hizzgdev/jsmind#157]
rt 例如 一级目录不能编辑以及拖拽 后面的可以编辑拖拽 如果暂无改功能 麻烦告知下修改哪部分源码

**Comment by hizzgdev** [comment]
我感觉是有点儿麻烦，要不你自己研究一下？

**Comment by Zaynex** [comment]
@zwmmm  哎，你就判断这个节点的 parentid 是不是 root ，是的话，就禁止这个节点所有事件好了。

**Comment by zwmmm** [comment]
@Zaynex  你这样就写死了一级目录不能编辑 实际上我的需求是 可以按照自己的要求规定哪些节点可以编辑

**Comment by Zaynex** [comment]
@zwmmm 我只是针对你的一级目录给你个思路，你选中节点的时候，就能拿到这个节点数据。你可以根据数据是否达到你的要求来决定是否可以编辑。

**Comment by zwmmm** [comment]
@Zaynex 我就是这么做的 直接在源码里面去修改了
