### ISSUE TITLE
show方法返回的对象存在递归引用,导致内存泄漏

### ISSUE THREAD

**Issue by zwmmm** [hizzgdev/jsmind#158]
![image](https://user-images.githubusercontent.com/30194521/49057716-c1032080-f23b-11e8-9d42-e9ae1a8a465b.png)

**Comment by hizzgdev** [comment]
只是互相持有引用而已，内存泄露在哪里？

**Comment by zwmmm** [comment]
存储在vuex中就会内存泄漏
