### ISSUE TITLE
vue使用拖拽功能时，节点拖拽到root节点时，jsmind.js报错

### ISSUE THREAD

**Issue by whyyyy** [hizzgdev/jsmind#161]
386行，jsMind处报错，无此对象
if(direction == jsMind.direction.left)

改成
if(direction == jm.direction.left){
后不报错了，也能用。但不知道有没有什么影响。
开发人员帮忙看下可否？

**Comment by Zaynex** [comment]
看起来是bug。用 jm 才是对的。 jm.direction 里存储了 方向的三个数据。楼主可以提个pr 试试。
https://github.com/hizzgdev/jsmind/blob/9a81a1e91624347ae8b628c3a49129aa025c6de8/js/jsmind.js#L113 @whyyyy

**Comment by whyyyy** [comment]
> 看起来是bug。用 jm 才是对的。 jm.direction 里存储了 方向的三个数据。楼主可以提个pr 试试。
> [jsmind/js/jsmind.js](https://github.com/hizzgdev/jsmind/blob/9a81a1e91624347ae8b628c3a49129aa025c6de8/js/jsmind.js#L113)
> 
> Line 113 in [9a81a1e](/hizzgdev/jsmind/commit/9a81a1e91624347ae8b628c3a49129aa025c6de8)
> 
>  jm.direction = {left:-1,center:0,right:1}; 
> @whyyyy

提了一个pr
