### ISSUE TITLE
如何修改derection为向下？

### ISSUE THREAD

**Issue by leotengfei** [hizzgdev/jsmind#164]
您好：
      现在只支持方向向左或者向右，怎样实现方向可以向下？

**Comment by louyea** [comment]
自己改去

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/pull/103
可以试用一下

**Comment by hizzgdev** [comment]
时间太久了，先 close 了，如果有类似问题再 reopen 吧。
