### ISSUE TITLE
节点之间的连线可以调整为对齐网格的直线吗

### ISSUE THREAD

**Issue by haozaicool** [hizzgdev/jsmind#167]
节点之间的连线可以调整为对齐网格的直线吗

**Comment by laoyangyu** [comment]
请问是将节点之间的连接线，由贝塞尔曲线改为直线吗？如果是的话，请在jsmind.js文件中搜索一个叫draw_line的方法，将其中的jm.util.canvas.bezierto改为jm.util.canvas.lineto

**Comment by laoyangyu** [comment]
代码中的lineto方法在969行，会直接连接两个点的直线，
`lineto: function (ctx, x1, y1, x2, y2) {
                ctx.beginPath();
                ctx.moveTo(x1, y1);
                ctx.lineTo(x2, y2);
                ctx.stroke();
            },`
可以加一行，改成这样
` lineto : function(ctx,x1,y1,x2,y2){
                ctx.beginPath();
                ctx.moveTo(x1,y1);
                ctx.lineTo(x1,y2);
                ctx.lineTo(x2,y2);
                ctx.stroke();
            },`
带直角转弯的连接线

**Comment by haozaicool** [comment]
按照您的说试了一下，达到了我想要的效果。
万分感谢，谢谢您百忙之中回答我的问题，谢谢！


------------------ 原始邮件 ------------------
发件人: "laoyangyu"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 下午2:02
收件人: "hizzgdev/jsmind"<jsmind@noreply.github.com>;
抄送: "魏"<809686861@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [hizzgdev/jsmind] 节点之间的连线可以调整为对齐网格的直线吗 (#167)




代码中的lineto方法在969行，会直接连接两个点的直线，
 lineto: function (ctx, x1, y1, x2, y2) { ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); },
 可以加一行，改成这样
  lineto : function(ctx,x1,y1,x2,y2){ ctx.beginPath(); ctx.moveTo(x1,y1); ctx.lineTo(x1,y2); ctx.lineTo(x2,y2); ctx.stroke(); },
 带直角转弯的连接线

**Comment by zg08** [comment]
> 请问是将节点之间的连接线，由贝塞尔曲线改为直线吗？如果是的话，请在jsmind.js文件中搜索一个叫draw_line的方法，将其中的jm.util.canvas.bezierto改为jm.util.canvas.lineto

想问一下 可以绘制曲线吗

**Comment by hizzgdev** [comment]
@laoyangyu Thanks
