### ISSUE TITLE
vue中拖拽无效

### ISSUE THREAD

**Issue by juhaiqi123** [hizzgdev/jsmind#169]
npm安装的不能使用拖拽功能

**Comment by zg08** [comment]
vue中怎么使用呢 可以组件可以作为节点引入吗

**Comment by hitzhaodong** [comment]
可以的  我实现过

**Comment by hizzgdev** [comment]
我对 vue 并不了解，希望熟悉的同学能给出建议或解决方法。感谢。

**Comment by bymomo** [comment]
我这边vue也不行，在index.html里面scr引入的话会报错,求解决办法

**Comment by bymomo** [comment]
// 导入jsmind相关依赖
import "common/js/jsmind/jsmind.css";
import jsMindMap from 'common/js/jsmind/jsmind.js';
window.jsMind = jsMindMap;
// 一定要放最后，也就是等jsmind挂载到全局后
require('common/js/jsmind/jsmind.draggable.js')

**Comment by modernzc** [comment]
> //导入jsmind相关依赖
> import“common / js / jsmind / jsmind.css”;
> 从'common / js / jsmind / jsmind.js'导入jsMindMap;
> window.jsMind = jsMindMap;
> //一定要放最后，也就是等jsmind挂载到全局后
> 要求（'common / js / jsmind / jsmind.draggable.js'）

您好，你在vue中使用的问题解决了吗，解决的话，我想看一下您怎么使用的

**Comment by haihai0000003** [comment]
大佬请问下vue中如何引入jsmind啊

**Comment by liang0-0** [comment]
> // 导入jsmind相关依赖
> import "common/js/jsmind/jsmind.css";
> import jsMindMap from 'common/js/jsmind/jsmind.js';
> window.jsMind = jsMindMap;
> // 一定要放最后，也就是等jsmind挂载到全局后
> require('common/js/jsmind/jsmind.draggable.js')

关键就是 window.jsMind   以及后面要使用require, 其他的都是一样的

**Comment by jiangtwelve** [comment]
import "../common/jsmind.css";
import jsMindMap from '../common/jsmind.js';
window.jsMind = jsMindMap;
require('../common/jsmind.draggable.js')

使用这种引入报错了
jsMind is not a constructor

请问有解决的方案嘛

**Comment by akingwangx** [comment]
import static/jsmind/js/jsmind.js';
import 'static/jsmind/js/jsmind.draggable.js';
先引入
然后在create函数里：
const Jsmind = window.jsMind
然后就按文档里new jsmind就完事了
