### ISSUE TITLE
Problem with not drawing the lines between nodes

### ISSUE THREAD

**Issue by harlan3** [hizzgdev/jsmind#173]
JSMind has a problem with not drawing the lines between nodes.  The attached Freemind file exhibits the behavior if you scroll down to the lower part of the canvas.  The Freemind file renders properly in the actual Freemind application.  Thanks.
.
[test.zip](https://github.com/hizzgdev/jsmind/files/3159586/test.zip)

**Comment by hizzgdev** [comment]
jsmind load your test file without any problem in chrome for test.

may i ask for some snapshots about the problem?

**Comment by harlan3** [comment]
Note the orphaned nodes with disconnected lines.
![jsmind_test](https://user-images.githubusercontent.com/24535999/62663672-84e59b00-b946-11e9-9cff-7b9b427c5212.PNG)

**Comment by hizzgdev** [comment]
Did you test in google chrome or Firefox , It may be a known issue in IE:
https://github.com/hizzgdev/jsmind/issues/26

**Comment by harlan3** [comment]
Just tested in Firefox and it seems to work ok.  I have no way of testing with Chrome.  I will mark this issue as closed.  Thanks for your help!

**Comment by hizzgdev** [comment]
@harlan3
The problem could be resolved in the pull-request: 
https://github.com/hizzgdev/jsmind/pull/205

It changes the method of drawing a line with SVG instead of canvas.

**Comment by harlan3** [comment]
Using svg engine fixes the problem in Microsoft Edge.
