### ISSUE TITLE
 topic节点可以添加vue组件吗

### ISSUE THREAD

**Issue by zg08** [hizzgdev/jsmind#176]
如果可以的话方便给个代码片段吗 因为节点里面有一些业务逻辑需要处理 现在是用原生js写的 很麻烦

**Comment by w1109770609** [comment]
不可以的，作用域不同

**Comment by zg08** [comment]
好的 谢谢


 
---原始邮件---
发件人: "w1109770609"<notifications@github.com>
发送时间: 2019年7月17日(星期三) 中午11:55
收件人: "hizzgdev/jsmind"<jsmind@noreply.github.com>;
抄送: "zg08"<595158663@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hizzgdev/jsmind]  topic节点可以添加vue组件吗 (#176)



不可以的，作用域不同
