### ISSUE TITLE
更新数据之后 更新视图 没有找到方法 是需要重新初始化吗

### ISSUE THREAD

**Issue by zg08** [hizzgdev/jsmind#177]
使用html动态添加了topic   更改之后需要重新初始化jsmind吗

**Comment by infosecliqin** [comment]
请问解决了吗？我需要动态加载数据，也需要重新初始化吗

**Comment by hizzgdev** [comment]
@zg08  @infosecliqin 请使用 jsMind 的 api 添加topic，这样节点会自动显示在脑图上。

使用html的dom模型添加html元素并不能真正的添加节点。

**Comment by DUKE-CAI** [comment]
请问 我通过后台数据动态更新jsmind脑图为什么会在自动生成一个？每点一次查询就会生成一个jsmind-inner

**Comment by hizzgdev** [comment]
> 请问 我通过后台数据动态更新jsmind脑图为什么会在自动生成一个？每点一次查询就会生成一个jsmind-inner
@DUKE-CAI 

用文档里的写法
```javascript
    // 一个页面上只 new 一次
    var jm = new jsMind(options);

    // 刷新数据时只需要重新调用 jm 对象的 show
    jm.show(mind);

    // 刷新数据时只需要重新调用 jm 对象的 show
    jm.show(mind);

    // 刷新数据时只需要重新调用 jm 对象的 show
    jm.show(mind);
```
