### ISSUE TITLE
控制台和正常绘制输出的一样，这里实际上是已经绘制了，只不过标准h5文档声明`<!DOCTYPE HTML>`下，容器的高度未被撑开，即`#container`容器的高度为0，而子容器`.jsmind-inner`的`overflow`为`auto`，此种情况下改为visible即可看到图了.

### ISSUE THREAD

**Issue by infosecliqin** [hizzgdev/jsmind#178]
控制台和正常绘制输出的一样，这里实际上是已经绘制了，只不过标准h5文档声明`<!DOCTYPE HTML>`下，容器的高度未被撑开，即`#container`容器的高度为0，而子容器`.jsmind-inner`的`overflow`为`auto`，此种情况下改为visible即可看到图了.
而示例代码http://hizzgdev.github.io/jsmind/中，通过函数`set_container_size()`给容器`#jsmind_container`设定了高度，从而避免了这个问题的出现。
现在要考虑的问题的是，如果不给容器设定高度，也不指定相关容器的`overflow`,能否像设置非标准h5文档声明一样可以自动撑开这个高度。
我抽时间再研究下源码，谢谢 @hizzgdev 的回复

_Originally posted by @shaozujie in https://github.com/hizzgdev/jsmind/issues/64#issuecomment-261698541_

**Comment by infosecliqin** [comment]
您好，请问解决了吗？也遇到了相同问题

**Comment by hizzgdev** [comment]
#container容器是用以承载 jsMind 的容器，jsMind 不会撑开它。
