### ISSUE TITLE
支持加标记吗？比如√，×，红旗之类的

### ISSUE THREAD

**Issue by wangtian010** [hizzgdev/jsmind#180]

**Comment by hizzgdev** [comment]
暂无实现

**Comment by WalkerHJ** [comment]
可以配合JQ右键菜单实现。
![image](https://user-images.githubusercontent.com/35361255/63397652-df2e3380-c3fd-11e9-821e-6aa88d4ff3a1.png)

**Comment by hizzgdev** [comment]
目前不支持，你试试通过html扩展一下吧。

**Comment by feimf** [comment]
> 可以配合JQ右键菜单实现。
> ![image](https://user-images.githubusercontent.com/35361255/63397652-df2e3380-c3fd-11e9-821e-6aa88d4ff3a1.png)

请问每个节点框的颜色不同，是怎么设置的啊

**Comment by hizzgdev** [comment]
时间太久了，先 close 了，如果有类似问题再 reopen 吧。
