### ISSUE TITLE
如何增加右键菜单功能，通过菜单中的事件来增删改节点

### ISSUE THREAD

**Issue by infosecliqin** [hizzgdev/jsmind#181]
如何增加右键菜单功能，通过菜单中的事件来增删改节点

**Comment by lance-z** [comment]
可以使用jQuery-contextMenu组合一下，直接在jmnode添加右键事件就可以增加节点

**Comment by infosecliqin** [comment]
请问，如何控制不同节点，右键菜单中的内容不同呢？我需要对不同节点有不同的操作

**Comment by infosecliqin** [comment]
请问，如何控制不同节点，右键菜单中的内容不同呢？我需要对不同节点有不同的操作

**Comment by lance-z** [comment]
contextMenu的每个菜单项都visible方法，获取当前节点判断是否显示应该能满足你的需求
