### ISSUE TITLE
Hi，各位，脑图线条绘制有性能问题，有好的优化方案吗？下面是我的描述

### ISSUE THREAD

**Issue by w1109770609** [hizzgdev/jsmind#187]
想问下浏览器会默认给canvas新建一个图层，脑图线条绘制有性能问题，在低配版电脑环境会异常卡顿，经性能测试发现是图层合成占了几乎所有的时间，有没有什么办法可以使canvas不单独创建一个图层或者有其他的妙招吗？

**Comment by Zaynex** [comment]
你看下 canvas 的面积有多大。一般而言，canvas 面积越大，绘制越慢。

**Comment by w1109770609** [comment]
@Zaynex 宽高有的都上万了，但是在本地就不卡，接入项目中就卡，很奇怪

**Comment by w1109770609** [comment]
@Zaynex jsmind插件本身太耗内存，尤其绘制canvas线条特别严重，插件本身比较好用以及扩展，瓶颈就在性能这一块，希望可以好好优化优化

**Comment by hizzgdev** [comment]
@w1109770609  "本地就不卡，接入项目中就卡" 是相同的代码，相同的html吗？

**Comment by w1109770609** [comment]
@Zaynex 后续验证应该跟接没接入没关系。jsmind用canvas绘制线条有性能的瓶颈，耗内存特别严重，我这边用svg绘制不仅可以解决耗内存的性能问题，还可以解决canvas本身高度的限制，两个性能对比都不是一个量级的，这是我的一点使用经验，也算一种比较好点的思路

**Comment by w1109770609** [comment]
@hizzgdev 后续验证应该跟接没接入没关系。jsmind用canvas绘制线条有性能的瓶颈，耗内存特别严重，我这边用svg绘制不仅可以解决耗内存的性能问题，还可以解决canvas本身高度的限制，两个性能对比都不是一个量级的，这是我的一点使用经验，也算一种比较好点的思路

**Comment by hizzgdev** [comment]
感谢回复，我先调研一下。

**Comment by hizzgdev** [comment]
@w1109770609 你好，你在使用svg和canvas进行性能对比的时候，脑图大概有多少个节点？你是使用svg改造了jsmind后进行测试的吗？

**Comment by w1109770609** [comment]
@hizzgdev 
1. 每一个tab页面有1200左右的节点，4个tab页面就已经快卡死了，内存爆满
2. 用的svg改造jsmind进行测试开10+个tab页面都不觉得太大的卡顿，这点我是拿jsmind对比百度脑图思考的产物

**Comment by hizzgdev** [comment]
@w1109770609 
嗯。我刚才了解了一下，在绘制比较大的面积的时候，canvas的性能下降得很严重。后续可能要对jsMind进行一些改进，如果方便的话，能否请你能分享一下你改造后的代码？

**Comment by w1109770609** [comment]
@hizzgdev 可以，我回头整理整理给提交下

**Comment by hizzgdev** [comment]
@w1109770609 感谢

**Comment by hizzgdev** [comment]
@w1109770609 尝试了一下 SVG ( #205 ) ，感觉也不复杂。而且在节点很多时，SVG的性能表现的确较好。
