### ISSUE TITLE
如何更新节点的ID

### ISSUE THREAD

**Issue by zwmmm** [hizzgdev/jsmind#195]
场景如下：
新增一个节点，插件会自动生成一个ID，但是我需要将这个ID改成后端返回的ID，这样才能请求接口

现在的做法：
是改了源代码，所有的事件都返回__id__

想要的效果，能够有个api可以修改节点的ID，直接替换是不行的，会报错

**Comment by hizzgdev** [comment]
你可以先请求接口，再新增节点，这样新增节点的时候就可以使用你后端返回的ID了。
`jm.add_node(parent_node, nodeid, topic, data)`
