### ISSUE TITLE
xmind文件可以不可以解析然后转换为脑图呢

### ISSUE THREAD

**Issue by Celine-h** [hizzgdev/jsmind#198]

**Comment by Zaynex** [comment]
可以。请参考 https://github.com/xmindltd/xmind-sdk-js

**Comment by hizzgdev** [comment]
有需要的话可以尝试解析，但xmind并不像freemind那么方便处理。

顺便说一句，兼容一种格式可能比想象得要复杂得多，虽然 jsMind 能读取 freemind 格式的文件，但其实只支持其基本的数据，别的很多特性都没能很好得处理。
