### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/Subject'

### ISSUE THREAD

**Issue by christopherney** [hizzgdev/jsmind#199]
Hello,

I have the following error
./node_modules/angular-mindmap/dist/mind-map-main.js
Module not found: Error: Can't resolve 'rxjs/Subject'

I'm using RxJs version :         "rxjs": "6.5.2",

**Comment by hizzgdev** [comment]
looks like you are looking for angular-mindmap, that is not jsMind
