### ISSUE TITLE
Creating Multiline TextArea, draggable, Save, Re-open, to hold user-input text labels, small todo lists, additional info

### ISSUE THREAD

**Issue by ghost** [hizzgdev/jsmind#210]
Would be nice enhancement feature if map user can enter (multi-line, if possible) text for labels, small to-do lists (1. 2. 3.), additional information that, as a text area, can be dragged and positioned next to a node (above, below, left or right side) to hold additional information. Could be a pop-up to save space(for example, SweetAlert2)? Should be able to save this text area locally as part of the map (if possible, in same JM or MM file as map), so that these text areas can be re-opened in the correct position on the map for editing, revising, re-positioning as needed. Would be a nice enhancement feature. Have tried to create this by duplicating and modifying add_node function (add_node2()) with additional CSS {} parameters, but no success, so far.

**Comment by hizzgdev** [comment]
Closed : long time pending
