### ISSUE TITLE
What's the relation between react-mind and jsmind?

### ISSUE THREAD

**Issue by anyexinglu** [hizzgdev/jsmind#212]
https://guimeisang.github.io/react-mind/example/demo1.html
http://hizzgdev.github.io/jsmind/example/1_basic.html

https://github.com/guimeisang/react-mind/blob/master/src/mind.js
https://github.com/hizzgdev/jsmind/blob/master/js/jsmind.js

**Comment by hizzgdev** [comment]
他可能是基于jsmind的一个早期的版本修改的，看名字应该是支持在react环境下使用。

我觉得他应该保留jsmind的版权声明。

**Comment by anyexinglu** [comment]
> 他可能是基于jsmind的一个早期的版本修改的，看名字应该是支持在react环境下使用。 我觉得他应该保留jsmind的版权声明。
> […](#)
> 在 2019年9月8日，18:53，anyexinglu ***@***.***> 写道： https://guimeisang.github.io/react-mind/example/demo1.html http://hizzgdev.github.io/jsmind/example/1_basic.html https://github.com/guimeisang/react-mind/blob/master/src/mind.js https://github.com/hizzgdev/jsmind/blob/master/js/jsmind.js — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

可以看下源码，好像就缩进不同（react-mind里也没有react关键字）

**Comment by hizzgdev** [comment]
嗯。他可能是当时没有通过fork方式处理。
