### ISSUE TITLE
存在大量的节点，拖拽节点时，拖拽缓慢且目标节点定位不准确

### ISSUE THREAD

**Issue by KRYshan** [hizzgdev/jsmind#215]
脑图存在大量的节点（多层级），拖拽任意节点为目标节点的子节点时，目标节点定位不准确（光标离节点很远），请问这种情况要怎么解决呀

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md#23-排版选项

使用 svg 引擎试试

**Comment by KRYshan** [comment]
切换为svg；显示的时候线条和节点分开显示了
![image](https://user-images.githubusercontent.com/16300720/66474662-501bce80-eac4-11e9-9d77-f0fa9fbc67af.png)

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
