### ISSUE TITLE
和bootstrap的模态框混用会出现样式问题，脑图挤在一起了。。

### ISSUE THREAD

**Issue by HanJunJun** [hizzgdev/jsmind#221]
![image](https://user-images.githubusercontent.com/16394348/68853104-2766a480-0714-11ea-9a07-d548a480773a.png)

**Comment by hugocvx** [comment]
Hi
I have this kind of issue if I call jsMind while rendering of html is not finished.
On a bootstrap modal, call jsMind in 

```
$('#myModal').on('shown.bs.modal', function () {
  // call jsMind there
})
```

**Comment by hizzgdev** [comment]
时间太久，如果有类似问题再 reopen 吧
