### ISSUE TITLE
多根节点及自由连线

### ISSUE THREAD

**Issue by ironman1987** [hizzgdev/jsmind#222]
有人实现了，在一个画布显示多个根节点，并且多个根节点可以自由连线的吗？

**Comment by xiaoxiaojian** [comment]
> 有人实现了，在一个画布显示多个根节点，并且多个根节点可以自由连线的吗？

同求，关系线

**Comment by hizzgdev** [comment]
抱歉，暂不支持

**Comment by StarSun123** [comment]
什么时候能支持啊 很难受呢 一个画布不支持多根节点

**Comment by StarSun123** [comment]
> > 有人实现了，在一个画布显示多个根节点，并且多个根节点可以自由连线的吗？
> 
> 同求，关系线

大哥，请问你解决了吗

**Comment by hizzgdev** [comment]
一个 mindmap 只支持一个根节点。暂时没有计划支持多根节点。
能问一下是什么样的场景需要多个根节点吗？ @StarSun123
