### ISSUE TITLE
自己写的jsmind右键扩展插件，有需要的同学自己去拿吧

### ISSUE THREAD

**Issue by allensunjian** [hizzgdev/jsmind#225]
业务中使用到了jsmind 但是无法满足全部需求。

所以自己进行了扩展。

增加了，右键的操作功能。和定制样式，文本和回调函数。

有需要的同学可以自行取用！

https://github.com/allensunjian/jsmind.menu.js

**Comment by Xiaxingdong** [comment]
牛逼

**Comment by yunfan** [comment]
刚好有需要 多谢

**Comment by tlxf** [comment]
这个能改造成简单的”工作流设计器“吗？可以保存json那种!

**Comment by hizzgdev** [comment]
Close old issues
