### ISSUE TITLE
测试有效// 导入jsmind相关依赖

### ISSUE THREAD

**Issue by 1pbSolidDrives** [hizzgdev/jsmind#228]
// 导入jsmind相关依赖
import "common/js/jsmind/jsmind.css";
import jsMindMap from 'common/js/jsmind/jsmind.js';
window.jsMind = jsMindMap;
// 一定要放最后，也就是等jsmind挂载到全局后
require('common/js/jsmind/jsmind.draggable.js')

_Originally posted by @bymomo in https://github.com/hizzgdev/jsmind/issues/123#issuecomment-522880144_

**Comment by haihai0000003** [comment]
大佬想问一下vue中如何导入呢

**Comment by jiangtwelve** [comment]
import "../common/jsmind.css";
import jsMindMap from '../common/jsmind.js';
window.jsMind = jsMindMap;
require('../common/jsmind.draggable.js')

使用这种引入报错了
jsMind is not a constructor

请问有解决的方案嘛
