### ISSUE TITLE
您好，请问有支持拖拽画布功能吗？

### ISSUE THREAD

**Issue by baimoer** [hizzgdev/jsmind#229]
不是拖拽节点，而是拖拽整个画布，比如当我的DIV很小的时候，比如400px * 400px  ，而思维导图很大，可以拖拽整个画布，显示相应的内容，一些客户端思维导图软件好像是支持的，可以考虑增加一个属性，是否允许拖拽画布。也可以增加一个方法，还原最初的位置。

还有就是可以增加一个方法，让它全屏显示吗？有的思维导图太大了。全屏显示的话，效果会好一些。

**Comment by baimoer** [comment]
谢谢，我已经找到修改的方法了

**Comment by ysk2014** [comment]
您好，请问是怎么实现的？

**Comment by rzy972408745** [comment]
您好，请问如何实现的？

**Comment by Ailichiyann** [comment]
您好，请问是如何实现的能具体说一下吗？
