### ISSUE TITLE
当jsmind数据过大时，在谷歌浏览器中下载图片会出现下载失败-网络错误

### ISSUE THREAD

**Issue by calmzhuang** [hizzgdev/jsmind#230]
当jsmind数据过大时，在谷歌浏览器中下载图片会出现下载失败-网络错误；
![image](https://user-images.githubusercontent.com/36062221/72120731-e5fd1900-3393-11ea-84fe-891de60c2e36.png)；
研究发现，把转换为base64的数据再转换为blob数据就可以正常下载了，如下：
![image](https://user-images.githubusercontent.com/36062221/72120849-43916580-3394-11ea-8707-52e8608e5732.png)

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
