### ISSUE TITLE
handler conflict with input element

### ISSUE THREAD

**Issue by hugocvx** [hizzgdev/jsmind#233]
Hi all,

JSMind event handler is wildely define including key up and down. Then if you have an input field in same page than a JSMind object, some keys (including space) are ignored once a node is selected.

I correct this by adding check in handler function:
```
        handler: function (e) {
            // ignore if this is not visible
            if ( !document.getElementById(this.jm.options.container).offsetParent ) { return ; }
            // ignore if target is an input element
            if ( e.target.tagName == 'INPUT' ) { return ; }

```
First check ignores event if jsmind container is hidden (case of tabs for example), second one ignores event if event target is an input element.

Do you have a better correction ?

I will submit pull request if not.

**Comment by hugocvx** [comment]
will add textarea check in pull request.

**Comment by hizzgdev** [comment]
fixed

ref: https://github.com/hizzgdev/jsmind/issues/296
