### ISSUE TITLE
组织架构图案例

### ISSUE THREAD

**Issue by superguopeng** [hizzgdev/jsmind#235]
请问下现在怎么实现竖向的组织架构图呢？

**Comment by hizzgdev** [comment]
往前翻翻 Issues 有讨论过该问题，而且有 pull-request，你可以试试。如果好用欢迎反馈

**Comment by sevenleos** [comment]
> 
> 
> 请问下现在怎么实现竖向的组织架构图呢？

比较麻烦，你可以看我的源代码 [http://www.sevenleos.com/jsmind/](url)
