### ISSUE TITLE
Vue单页面中如何引入

### ISSUE THREAD

**Issue by Thinker-Mars** [hizzgdev/jsmind#236]
哥哥们，npm安装模块后，如何在Vue单页面中引入jsmind，我按如下方式导入无效，但调用API有数据返回，所以我怀疑是css未正常导入，在线等，挺急的[狗头]

<script>
import "jsmind/style/jsmind.css";
import jsMind from "jsmind";
export default {
   ...
}
</script>

**Comment by Thinker-Mars** [comment]
已解决

**Comment by haihai0000003** [comment]
您好 请问是如何解决的 能告诉我一下吗  正确导入js和css

**Comment by Thinker-Mars** [comment]
> 您好 请问是如何解决的 能告诉我一下吗 正确导入js和css

你把你的邮箱发给我，我整理下发给你

**Comment by cmm-va** [comment]
> > 您好 请问是如何解决的 能告诉我一下吗 正确导入js和css
> 
> 你把你的邮箱发给我，我整理下发给你

我也需要，能发给我看一下吗 谢谢

**Comment by Thinker-Mars** [comment]
> > > 您好 请问是如何解决的 能告诉我一下吗 正确导入js和css
> > 
> > 
> > 你把你的邮箱发给我，我整理下发给你
> 
> 我也需要，能发给我看一下吗 谢谢

其实也不难啦，你把jsmind对象保存到一个变量中，在导出来就好啦~

**Comment by zhangxh1023** [comment]
> > > > 您好 请问是如何解决的 能告诉我一下吗 正确导入js和css
> > > 
> > > 
> > > 你把你的邮箱发给我，我整理下发给你
> > 
> > 
> > 我也需要，能发给我看一下吗 谢谢
> 
> 其实也不难啦，你把jsmind对象保存到一个变量中，在导出来就好啦~

我有点儿没理解...有时间可以麻烦解释一下吗 或者给个伪代码😂

**Comment by zhangxh1023** [comment]
> > > > > 您好 请问是如何解决的 能告诉我一下吗 正确导入js和css
> > > > 
> > > > 
> > > > 你把你的邮箱发给我，我整理下发给你
> > > 
> > > 
> > > 我也需要，能发给我看一下吗 谢谢
> > 
> > 
> > 其实也不难啦，你把jsmind对象保存到一个变量中，在导出来就好啦~
> 
> 我有点儿没理解...有时间可以麻烦解释一下吗 或者给个伪代码😂

找到问题了. 是我自己的问题. 把容器高度设置的太低了, 显示不了, 设置 高点就好了.
