### ISSUE TITLE
怎么动态添加包含子元素的节点呢

### ISSUE THREAD

**Issue by Manybin** [hizzgdev/jsmind#239]
目前可以通过异步加载子元素，但是怎么添加带扩展的+ 的元素呢

**Comment by hizzgdev** [comment]
你可能需要先解释一下什么是“ 带扩展的+ 的元素”

**Comment by Manybin** [comment]
就是带children的元素，点击可以展示子元素。
我动态获取数据，这个数据是包含children的，这时候使用add_node 这个方法似乎只能添加一层节点

**Comment by hizzgdev** [comment]
继续往下一级添加就可以了。

**Comment by Manybin** [comment]
我想要那个带展开符号的，因为每一次都会需要动态加载。使用add_node的时候没办法带展开符号的

**Comment by hizzgdev** [comment]
那个加号没有参数控制，有子节点时自动出现。
