### ISSUE TITLE
可以实现选择多个节点然后获取对应的文本内容吗？

### ISSUE THREAD

**Issue by majiajue** [hizzgdev/jsmind#24]
可以实现选择多个节点然后获取对应的文本内容吗？

**Comment by hizzgdev** [comment]
技术角度上讲，实现多节点选中问题不大，但需要一定的重构。

获取对应文本的话，可能并不太适合同时处理，虽然技术角度并无障碍。

你的具体需求是什么呢？

**Comment by suwu150** [comment]
请问如何实现,多选之后,进行删除节点的操作,或者通过多选之后,给我返回选择之后的id数组,我通过循环的方式进行一一删除?

**Comment by suwu150** [comment]
现在如果能够在我多选时,进行标记已经选择的节点就可以了,删除的操作我可以通过循环实现
