### ISSUE TITLE
当节点特别多的时候，背景会变成黑色，连接线也会消失，请问怎么解决？

### ISSUE THREAD

**Issue by billzw** [hizzgdev/jsmind#242]
当节点特别多的时候，背景会变成黑色，连接线也会消失，请问怎么解决？

![20200420000230](https://user-images.githubusercontent.com/4268456/79693001-d0ed2b80-829a-11ea-8fa1-bcbf6be5a589.jpg)

**Comment by hizzgdev** [comment]
节点特别多是指有多少？或者提供可复现此问题的测试数据。

**Comment by erinozomi** [comment]
我的也出现这个问题了。数据特别多的时候背景黑色。

**Comment by hizzgdev** [comment]
如有必要，请提供测试数据和浏览器情况后 reopen 此 issue

**Comment by zxd6654** [comment]
我也遇到了，就是博主可以自己创建一个几千条数据，然后用jsmind导图展示一下试试，背景变黑了，线条消失了，当你把数据变少的时候，就恢复正常了

**Comment by hizzgdev** [comment]
@zxd6654 你在option里把 view.engine 设置成 svg 看能不能解决这个问题。https://hizzgdev.github.io/jsmind/docs/zh/2.options.html如果不行的话，可以分享一下你用的jsmind的版本，浏览器，以及数据的规模有多大。谢谢！在 2024年4月10日，16:00，朱晓东 ***@***.***> 写道：﻿
我也遇到了，就是博主可以自己创建一个几千条数据，然后用jsmind导图展示一下试试，背景变黑了，线条消失了，当你把数据变少的时候，就恢复正常了

**Comment by zxd6654** [comment]
解决了，view.engine 设置成 svg 这个就可以了，使用 svg 绘制线条，当思维导图的节点很多，面积巨大的时候，使用该模式能带来显著的性能提升

**Comment by zxd6654** [comment]
感谢楼主

**Comment by hizzgdev** [comment]
是的，浏览器还不能支持无限大的 canvas，svg应该是更好的选择。感谢你的反馈，这个issue终于可以放心地关掉了。

**Comment by zxd6654** [comment]
楼主，再问您一个问题哈，就是数据多的时候用svg解决了，但是用jm.screenshot.shootDownload() 下载图片的时候，数据多的话，下载的图片也是空的，数据少的时候就有了，正常了

**Comment by hizzgdev** [comment]
是的，screenshot 截图时需要用到 canvas 来生成图片，所以这其实是个已知问题。如果你需要自己生成图片的话（而不是提供功能给别人使用的话），可以用 chrome 自带的功能来处理。 参考这个答案： https://github.com/hizzgdev/jsmind/discussions/575

@zxd6654 zxd
