### ISSUE TITLE
读入freemind脑图，节点中文本超过一定长度后会被省略

### ISSUE THREAD

**Issue by zhyma** [hizzgdev/jsmind#247]
![jsmind](https://user-images.githubusercontent.com/2032749/80872662-47b5fb80-8c81-11ea-9c60-cb44291ef7d8.png)
如图所示，超过一定长度后会被省略。请问是否可以让其显示全一个节点中的内容？谢谢。

**Comment by hizzgdev** [comment]
按文档说明自定义一个主题，修改其样式就行了。

**Comment by zhyma** [comment]
在HotTopic里找到解决方案了，谢谢！
