### ISSUE TITLE
建议新增对事件的支持。

### ISSUE THREAD

**Issue by winunet** [hizzgdev/jsmind#25]
你好，非常感谢你开源的jsMind，对我们项目帮助很大。目前有一个小小的不足和建议，那就是jsMind应该提供对事件的支持。例如：选中事件，拖曳事件，节点改变事件等等。我想这也是jsMind能够更大强大的一个开发方向。

最后谢谢你开发并开源这么好的产品。

**Comment by ttsdzzg** [comment]
jsmind 目前支持很少量的事件，但是由于太少了，以至于文档中并没有提及。确如你所说，这方面是一个重要的提升方向。慢慢会不断添加，希望大家也能帮助我一起做好她。

PS，jsmind是基于 html 的，所以基于事件冒泡的原理，如果有需要可以在外层 dom 中添加事件并进行处理。
