### ISSUE TITLE
建议编辑输入框增加个字体颜色，字体颜色和背景色都是白色，没法看

### ISSUE THREAD

**Issue by wmz46** [hizzgdev/jsmind#251]
双击编辑节点时，由于字体颜色是白色，背景色也是白色，会看不到文字。建议增加个编辑框字体颜色，类似下面这样。
`.jsmind-editor{
    color:#000000;
}`

**Comment by hizzgdev** [comment]
未发现此问题，请提供测试用例。

**Comment by wmz46** [comment]
我发现是引入了bootstrap后才出现的
https://codepen.io/wmz46/pen/WNQPNoq

**Comment by hizzgdev** [comment]
在你的项目里自行修改吧
