### ISSUE TITLE
data的topic可以支持函数吗，便于配置自定义的节点

### ISSUE THREAD

**Issue by fezzl** [hizzgdev/jsmind#252]
```js
data: {
 id: 'root'
 topic: (ele) => `<div>${ele}</div>`
}
```

**Comment by hizzgdev** [comment]
要不你试试，然后提个pr我们一起测试测试。

另外我也没有想出这样的使用场景……

**Comment by coderzelin** [comment]
> 要不你试试，然后提个pr我们一起测试测试。 另外我也没有想出这样的使用场景……
> […](#)
> 在 2020年5月21日，16:58，coderzelin ***@***.***> 写道： ﻿ data: { id: 'root' topic: (ele) => `<div>${ele}</div>` } — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

例如，每个节点都要渲染成一个相同的 dom 结构，每次都要自己去拼接 dom 结构会有点麻烦，所以如果支持一个函数的话可以抽离出一个通用的 render 函数

**Comment by hizzgdev** [comment]
我理解你这是不是就是 addCustomNode 的意思？

**Comment by coderzelin** [comment]
> 我理解你这是不是就是 addCustomNode 的意思？
> […](#)
> 在 2020年5月22日，10:36，coderzelin ***@***.***> 写道： ﻿ 要不你试试，然后提个pr我们一起测试测试。 另外我也没有想出这样的使用场景…… … 在 2020年5月21日，16:58，coderzelin @.***> 写道： ﻿ data: { id: 'root' topic: (ele) => <div>${ele}</div> } — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 例如，每个节点都要渲染成一个相同的 dom 结构，每次都要自己去拼接 dom 结构会有点麻烦，所以如果支持一个函数的话可以抽离出一个通用的 render 函数 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是的

**Comment by hizzgdev** [comment]
太久没有更新
