### ISSUE TITLE
node点击

### ISSUE THREAD

**Issue by zhaoshiqi123** [hizzgdev/jsmind#253]
有没有node的点击事件，就是这个标题块的本身的点击事件

**Comment by hizzgdev** [comment]
用dom的事件即可

**Comment by zhaoshiqi123** [comment]
ok 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhigang Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 晚上6:17
收件人:&nbsp;"hizzgdev/jsmind"<jsmind@noreply.github.com&gt;;
抄送:&nbsp;"wcy"<2844605531@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hizzgdev/jsmind] node点击 (#253)





 用dom的事件即可
 
 &gt; 在 2020年5月21日，18:05，zhaoshiqi123 <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; 有没有node的点击事件，就是这个标题块的本身的点击事件
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
