### ISSUE TITLE
如何监听节点的点击事件

### ISSUE THREAD

**Issue by fezzl** [hizzgdev/jsmind#254]
想在点击节点时触发一个回调函数，并获取节点的id

**Comment by hizzgdev** [comment]
试试这个：
jm.add_event_listener(function(type,data){

});

或者直接使用dom的事件。

**Comment by coderzelin** [comment]
> 试试这个： jm.add_event_listener(function(type,data){ }); 或者直接使用dom的事件。
> […](#)
> 在 2020年5月27日，10:04，coderzelin ***@***.***> 写道： ﻿ 想在点击节点时触发一个回调函数，并获取节点的id — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

只在初次渲染的时候触发了事件，在点击节点时候没触发事件，想要在点击节点时获取点击那个节点data的id有什么方法吗

**Comment by hizzgdev** [comment]
“ 只在初次渲染的时候触发了事件” 哪个事件？上面说的试过了吗？

> 在 2020年5月27日，10:49，coderzelin <notifications@github.com> 写道：
> 
> 只在初次渲染的时候触发了事件

**Comment by coderzelin** [comment]
> “ 只在初次渲染的时候触发了事件” 哪个事件？上面说的试过了吗？
> […](#)
> 在 2020年5月27日，10:49，coderzelin ***@***.***> 写道： 只在初次渲染的时候触发了事件

试过了，就是初次渲染的时候触发的jm.add_event_listener(function(type,data){})的callback，点击的时候没触发

**Comment by hizzgdev** [comment]
那使用dom的事件吧，element的attribute有id，你找找看看吧。

**Comment by sakuramiss** [comment]
$("#jsmind_container").on('click', function () {   //监听jsmind设置id的点击事件
        console.log("jsmind_container click");   
        console.log(jm.get_selected_node());    //获得被选中节点信息
        
    })

**Comment by coder-yuzhiwei** [comment]
> ```
> $("#jsmind_container").on('click', function () {   //监听jsmind设置id的点击事件
>     console.log("jsmind_container click");   
>     console.log(jm.get_selected_node());    //获得被选中节点信息
>     
> })
> ```

nice solution!

**Comment by LDT2016** [comment]
> ```
> $("#jsmind_container").on('click', function () {   //监听jsmind设置id的点击事件
>     console.log("jsmind_container click");   
>     console.log(jm.get_selected_node());    //获得被选中节点信息
>     
> })
> ```

good!
