### ISSUE TITLE
有个bug, jm.insert_node_after里写成了node_before

### ISSUE THREAD

**Issue by ArthurKing01** [hizzgdev/jsmind#255]

**Comment by ArthurKing01** [comment]
![image](https://user-images.githubusercontent.com/20166822/83097728-60c49780-a0db-11ea-9e0c-f1edb615c321.png)

**Comment by hizzgdev** [comment]
fixed by https://github.com/hizzgdev/jsmind/commit/e3e2b31a80491ab627927b0a835dc895c2d6a55c @w5240
