### ISSUE TITLE
IE浏览器线不显示问题

### ISSUE THREAD

**Issue by zhangshuai1** [hizzgdev/jsmind#26]
在IE下同纵向节点要是大于140线就没了，
横着是没问题的，怀疑是高度问题。
感谢您开源的jsmind强大功能，只是有IE和火狐的我说的我问题。

**Comment by ttsdzzg** [comment]
方便的话可否贴出测试的数据

**Comment by zhangshuai1** [comment]
就是在同级节点上一直增加节点到一定数量就会出现了。

**Comment by hizzgdev** [comment]
Firefox 44.0.2 没有出现你提到的问题，能否截图或提供一下游览器版本？

**Comment by zhangshuai1** [comment]
我不知道怎么在这发图片,我的浏览器就是44.0.2应该是您的节点数还没达到140左右？

**Comment by hizzgdev** [comment]
我在IE和重现了你提出的问题（但在 Firefox 下仍未能重现）。jsMind 使用 canvas 绘制连接线，而IE对canvas 的实现存在以下问题：

> The maximum size of the rendered area on a canvas is from 0,0 to 8192 x 8192 pixels, regardless of the size of the canvas. [MSDN: canvas element][1]

jsMind 暂时不会对 IE 的这一特点进行特殊处理，希望你理解。

[1]: https://msdn.microsoft.com/zh-cn/library/ff975062(v=vs.85).aspx

**Comment by wycJason** [comment]
我用的是“360极速浏览器”，极速模式，版本号9.0.1.140，内核版本：55.0.2883.87测试的，节点数我创建了差不多1000多个，文字20万字节，当折叠到一定数量时，节点与节点之前的连线会显示出来，当展示数量足够多时，连线就看不见了。请问是什么原因？谷歌浏览器也有同样的问题。

**Comment by wycJason** [comment]
是不是画布上渲染区域的最大大小从0,0到8192 x 8192像素，超出了就不显示连线了呢？如果是，有什么办法能解决，张先生。

**Comment by hizzgdev** [comment]
@wycJason 

参考一下这个结果，应该就是这个原因：
https://stackoverflow.com/a/11585939

```
Chrome:

Maximum height/width: 32,767 pixels
Maximum area: 268,435,456 pixels (e.g., 16,384 x 16,384)

Firefox:

Maximum height/width: 32,767 pixels
Maximum area: 472,907,776 pixels (e.g., 22,528 x 20,992)

IE:

Maximum height/width: 8,192 pixels
Maximum area: N/A

IE Mobile:

Maximum height/width: 4,096 pixels
Maximum area: N/A

```

如果一定要处理的话，大致有两个思路：

1. 使用多个canvas进行拼接
2. 让一个canvas滑动起来，永远显示在浏览器视野里

但是都不太容易处理。请见谅。
