### ISSUE TITLE
怎么给边的开头或结尾加上箭头？(How do I add arrows to start or end of the edges?)

### ISSUE THREAD

**Issue by neehow** [hizzgdev/jsmind#261]
大佬们，想给边加上箭头，有什么方案吗？
I need to add arrows to start or end of the edges. Can anyone help?
(写上英文，万一有老外知道呢^_^)

**Comment by wuliguaiguaia** [comment]
那个边，有图的话清晰些

**Comment by neehow** [comment]
> 那个边，有图的话清晰些

![image](https://user-images.githubusercontent.com/7135209/85366276-984b2600-b559-11ea-8776-ccd3e242a7f3.png)
比如图中红色标注的部分

**Comment by wuliguaiguaia** [comment]
这个线条是有明确的开始和结束位置，所以可以拿着结束位置的坐标画一个箭头，此外还得考虑箭头的转向
