### ISSUE TITLE
转成image好像只有线，没有节点

### ISSUE THREAD

**Issue by iamzwq** [hizzgdev/jsmind#267]
我检查元素，是这样的，这个不是用canvas去画的吗？我把这个canvas转成image就只有线，没有节点
<div class="jsmind_container" id="jsmind_container_1234809" style="transform: scale(0.5); width: 666px; height: 540px; position: absolute; top: -130px; left: -162px;">
    <div class="jsmind-inner">
        <canvas width="666" height="540"></canvas>
        <jmnodes class="theme-primary" style="width: 666px; height: 540px;">
            <jmnode class="root" nodeid="12347098" style="visibility: visible; left: 179px; top: 246.5px;">示例框架根节点</jmnode>
            <jmexpander nodeid="12347307" style="visibility: hidden; display: none;">-</jmexpander>
            <jmnode nodeid="12347307" style="visibility: visible; left: 397px; top: 251px;">node011</jmnode>
            <jmnode style="visibility: hidden; z-index: 3; cursor: move; opacity: 0.7;"></jmnode>
        </jmnodes>
        <canvas width="666" height="540"></canvas>
    </div>
</div>

**Comment by hizzgdev** [comment]
是的

**Comment by hizzgdev** [comment]
http://hizzgdev.github.io/jsmind/example/2_features.html

导出图片的话用 screenshot 插件来搞，代码参考上面的地址
