### ISSUE TITLE
拖动时，会关联到隐藏元素上

### ISSUE THREAD

**Issue by Jam1zhu** [hizzgdev/jsmind#268]
如图，拖拽元素时，关联到了隐藏元素上。求教，是我少加了什么设置吗
![1595470997517](https://user-images.githubusercontent.com/21252750/88246959-b6c64d80-ccce-11ea-8a40-c0885a5b80f4.jpg)

**Comment by rockfang** [comment]
@Jam1zhu 请问，有找到解决方式吗

**Comment by hizzgdev** [comment]
抱歉，这是个bug，已修复
