### ISSUE TITLE
收起所有节点

### ISSUE THREAD

**Issue by zhangshuai1** [hizzgdev/jsmind#27]
请问咱们关闭节点时候能否关闭除二级节点外所有节点的方法？
我发现循环关闭节点很卡，谢谢了。

**Comment by ttsdzzg** [comment]
此功能已更新至 dev-0.2的分支里了，过段时间会合并到 master 中，敬请期待，或先试用 dev-0.2 的版本

**Comment by zhangshuai1** [comment]
首先感谢您的回信，那咱们的dev-0.2版本不知道什么时候出来那？我现在能否试用那？

**Comment by hizzgdev** [comment]
git clone https://github.com/hizzgdev/jsmind.git
cd jsmind
git checkout dev-0.2 origin/dev-0.2

**Comment by zhangshuai1** [comment]
您这个有关闭节点的但是这个好像没有提供一下关闭所有节点的方法是吧？

**Comment by zhangshuai1** [comment]
您这个插件默认进去是要画top和left值，和画线这样操作完后咱们是否能够提供一个方法将所有节点全部收缩起来?

**Comment by hizzgdev** [comment]
expand_to_depth(1) 不知道是否能满足你的需要。
我之前理解你说的“关闭节点”是指把节点收缩起来的意思，不知道是否正确。

**Comment by zhangshuai1** [comment]
您好这个在那个js里？

**Comment by zhangshuai1** [comment]
TypeError: _jm.expand_to_depth is not a function
	

_jm.expand_to_depth(1);

**Comment by hizzgdev** [comment]
在 dev-0.2的分支里

**Comment by zhangshuai1** [comment]
那您这个应该引用一个js吧？
或者我怎么验证这个dev-0.2怎么运用那？

**Comment by zhangshuai1** [comment]
虽然您说是在dev-0.2分支里但我不知道我该怎么运用？

**Comment by hizzgdev** [comment]
用 dev-0.2 里的  jsmind.js 替换你现在使用的版本即可。

**Comment by zhangshuai1** [comment]
您能否直接发我下载的没有发现dev-0.2,而且您的服务器我是看不到？

**Comment by hizzgdev** [comment]
git clone https://github.com/hizzgdev/jsmind.git
cd jsmind
git checkout dev-0.2 origin/dev-0.2
cd js
你就能看到新版本的 jsmind.js 了。

**Comment by zhangshuai1** [comment]
好的我试试

**Comment by zhangshuai1** [comment]
谢谢

**Comment by zhangshuai1** [comment]
在有您这个相当于层级？收缩也不是所有节点都收缩是吧？

**Comment by zhangshuai1** [comment]
而且我也测试了dev-0.2节点多在火狐下还是没有线。

**Comment by zhangshuai1** [comment]
或者咱们这个插件有什么办法知道有几层数据吗？

**Comment by hizzgdev** [comment]
> 在有您这个相当于层级？收缩也不是所有节点都收缩是吧？

我不是很清楚这是什么意思， 你验证一下看看，或者你觉得应该是什么样的，可以提出来。

**Comment by hizzgdev** [comment]
> 而且我也测试了dev-0.2节点多在火狐下还是没有线。

这个我会再继续测试，今天晚些时候再回复你。

**Comment by hizzgdev** [comment]
> 或者咱们这个插件有什么办法知道有几层数据吗？

目前没有提供这个接口，如果你有这个需求，可以先尝试自己计算一下。

**Comment by zhangshuai1** [comment]
好的，谢谢您，我的意思是比如说要把所有节点都全部收缩我试了咱们的方法写1是第一层收缩，写2是第二级收缩，功能确实很强大了，在有没有一种方法是知道数据一共有层数这样循环也就达到所有节点收缩的效果了。

**Comment by zhangshuai1** [comment]
好的明白谢谢

**Comment by hizzgdev** [comment]
如果是这样的话，你可以在构造数据对象的时候，给每一个节点都设置一下  expanded=false 即可达到你的效果了。

节点的初始参数：https://github.com/hizzgdev/jsmind/blob/dev-0.2/docs/zh/1.usage.md#注

**Comment by zhangshuai1** [comment]
谢谢，正好是我说的效果

**Comment by hizzgdev** [comment]
好的， 感谢支持！

**Comment by zhangshuai1** [comment]
在有就是浏览器的那个问题了，很感谢您的耐心解答，非常感谢。

**Comment by hizzgdev** [comment]
收起所有节点已解决： https://github.com/hizzgdev/jsmind/commit/cd4f9c2a8e98dae2a3053a9622d33a010f303ba1
浏览器问题参见： https://github.com/hizzgdev/jsmind/issues/26
