### ISSUE TITLE
該如何在Angular 下 import jsmind(How to import jsmind in Angular2)

### ISSUE THREAD

**Issue by KUOYUCHEN** [hizzgdev/jsmind#272]
在npm i jsmind 安裝後, 在ts檔案輸入 import jsMind from 'jsmind'

按照初始設定後, 可以順利顯示在網頁上, 不過我想有draggable

該如何import 另外一個 jsmind.draggable.js 檔呢?

請各位大老解惑

After npm i jsmind, I follow the rule of default code, and it works

BUT I want to add new behavior which is draggable,

How do I import another jsmind.draggable.js ?

Please help, thanks

**Comment by hizzgdev** [comment]
请参考:  https://github.com/hizzgdev/jsmind/issues/228

**Comment by tonyyuer** [comment]
angular13 以第三方js方式引入，有三种方式，网上有很多可以搜一下，目前我用下列实现方式：
1，首先下载jsMind压缩包，解压后放到src/assets目录下
2，在angular.json中配置style和JavaScript            
 "styles": [
              "src/assets/jsmind/style/jsmind.css",
              "src/styles.scss"
            ],
            "scripts": [
              "src/assets/jsmind/js/jsmind.draggable-node.js",
              "src/assets/jsmind/js/jsmind.js",
              "src/assets/jsmind/js/jsmind.screenshot.js"
            ]
3，在需要的地方引入
import '../assets/jsmind/js/jsmind.js';
import '../assets/jsmind/js/jsmind.draggable-node';
declare var jsMind:any;
然后在ngOnInit中可正常使用 
this.mindMap = jsMind.show(options,this.mind);
