### ISSUE TITLE
建议:自动展开和手风琴折叠

### ISSUE THREAD

**Issue by jinigithub** [hizzgdev/jsmind#275]
很喜欢jsmind,个人有两个建议：
1.展开节点时，自动展开所有父节点，因为折叠时也是能越级. 有时候通过直接子节点搜索定位展开时有用,get_node如果能增加模糊匹配就更美好了.
2.增加全局属性：手风琴排它开关. on的时候,排他性展开,即当一个子节点展开时,可以用开关控制当前链路之外的节点全部折叠,对于内容多时方便集中信息展示

**Comment by hizzgdev** [comment]
jsmind提供了基础的支持，提到的两个功能倒不难，但暂不考虑加到jsmind的支持范围内，可以在具体应用里自行实现。
