### ISSUE TITLE
Custom Style when selecting a node 

### ISSUE THREAD

**Issue by VoltolRL** [hizzgdev/jsmind#276]
Currently the selected node is highlighted by the dark blue color (#11f).

The actual color of the selected node is therefore hidden.

My request is therefore: "Is it possible to provide another way than background-color to highlight the selected node? For example to choose between option "border" or "background-color" to highlight the selected node."

![mceclip5_2020-09-17_21-08-29_948](https://user-images.githubusercontent.com/71836214/94164229-0ec53000-fe89-11ea-8f20-93514b647074.png)

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/en/1.usage.md#13-themes

It's easy to custom the style of selected nodes by following the doc above.
