### ISSUE TITLE
请问一下，有属性可以控制思维导图的比例缩放吗？

### ISSUE THREAD

**Issue by lin-blake** [hizzgdev/jsmind#278]

**Comment by mi521** [comment]
<button type="button" id="zoom-in-button" onclick="zoomIn()" class="btn btn-inverse btn-block">放大</button>
<button type="button" id="zoom-out-button" onclick="zoomOut()" class="btn btn-inverse btn-block">缩小</button>

/**
     *
     * 放大
     * 缩小
     * */

    var zoomInButton = document.getElementById("zoom-in-button");
    var zoomOutButton = document.getElementById("zoom-out-button");

    function zoomIn() {
        if (jm.view.zoomIn()) {
            zoomOutButton.disabled = false;
        } else {
            zoomInButton.disabled = true;
        }
        ;
    };

    function zoomOut() {
        if (jm.view.zoomOut()) {
            zoomInButton.disabled = false;
        } else {
            zoomOutButton.disabled = true;
        }
        ;
    };

**Comment by lin-blake** [comment]
非常感谢，已在源码找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hizzgdev/jsmind"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 下午3:04
收件人:&nbsp;"hizzgdev/jsmind"<jsmind@noreply.github.com&gt;;
抄送:&nbsp;"1679433504"<1679433504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hizzgdev/jsmind] 请问一下，有属性可以控制思维导图的比例缩放吗？ (#278)





 
放大
 缩小
 
/**
 *
 * 放大
 * 缩小
 * */
 var zoomInButton = document.getElementById("zoom-in-button"); var zoomOutButton = document.getElementById("zoom-out-button"); function zoomIn() {     if (jm.view.zoomIn()) {         zoomOutButton.disabled = false;     } else {         zoomInButton.disabled = true;     }     ; }; function zoomOut() {     if (jm.view.zoomOut()) {         zoomInButton.disabled = false;     } else {         zoomOutButton.disabled = true;     }     ; };
