### ISSUE TITLE
jsmind在ie8下不显示连接线问题

### ISSUE THREAD

**Issue by 826169340** [hizzgdev/jsmind#28]
在ie8下显示没有连接线，ie9之后的浏览器就正常，是不是ie8的兼容性问题，demo在ie8浏览器下也无法打开

**Comment by ttsdzzg** [comment]
是的，jsMind 并不支持 IE8，也并无兼容 IE8 的计划表，十分抱歉。

**Comment by DKSwang** [comment]
IE11支持吗?
