### ISSUE TITLE
放弃了

### ISSUE THREAD

**Issue by sevenleos** [hizzgdev/jsmind#286]
1

**Comment by sevenleos** [comment]
顺便说一句，原谅我不会用github，不会版本管理什么的。但是源码里面改过的部分，基本上都做了注释。直接看源代码就好了

**Comment by xdsnet** [comment]
很好的实践，不过jsmind的使用其实分成2种情况
1. 仅仅是展示使用
2. 生成编辑输出使用
你的例子只有编辑输出使用，没有单纯的展示使用例子啊

**Comment by sevenleos** [comment]
> 
> 
> 很好的实践，不过jsmind的使用其实分成2种情况
> 
>     1. 仅仅是展示使用
> 
>     2. 生成编辑输出使用
>        你的例子只有编辑输出使用，没有单纯的展示使用例子啊

你可以在我的链接下载源代码，在右上角。电脑可以直接用浏览器打开。可以编辑的时候，保存json或者jm文件。可以本地打开用来展示的。或者可以部署在自己的应用里面去做呈现。
