### ISSUE TITLE
topic中加入富文本后拖拽功能位置会不准

### ISSUE THREAD

**Issue by akingwangx** [hizzgdev/jsmind#290]
![image](https://user-images.githubusercontent.com/25190253/109789474-54adcd80-7c4b-11eb-968e-2be04facbf93.png)
如图 鼠标点到1那个标签上 会判定到左上角，看了下源码应该是jsmind.draggable.js中dragstart函数中的offset_x和offset_y位置不正确，有什么解决方案吗？

**Comment by hizzgdev** [comment]
未能复现。
如果需要的话请提供测试数据后 reopen 这个 issue.
