### ISSUE TITLE
编辑节点的时候怎么手动换行？

### ISSUE THREAD

**Issue by Ikarossssss** [hizzgdev/jsmind#293]
编辑节点的时候怎么手动换行？

**Comment by hizzgdev** [comment]
jsmind主要提供的是一个lib，自带交互式的编辑功能只是满足简单的需要，建议在使用的时候根据自己的产品需求进行适当的包装。
具体到这个问题，jsmind里编辑节点的时候，使用的是 `input type=text`，你可以尝试修改为 textarea 或者使用其它的方法对节点进行编辑。
