### ISSUE TITLE
CSS没有效果

### ISSUE THREAD

**Issue by Mytheses** [hizzgdev/jsmind#295]
![image](https://user-images.githubusercontent.com/62224193/118461248-0ed3b200-b730-11eb-87ea-761856abf7f8.png)
The Styling is still messed up even though I imported the css.
Any help?
Thanks in Advance

我已近写了css可是效果还是如上图一样。
求大神帮帮

**Comment by hizzgdev** [comment]
只有一个截图可能没人能帮得了你，不如你介绍一下你加了什么，改了什么。

**Comment by hizzgdev** [comment]
如有更新请再 reopen 这个 issue 吧。
