### ISSUE TITLE
Global shortcuts

### ISSUE THREAD

**Issue by Tilesto** [hizzgdev/jsmind#296]
Problem:
Shortcuts are working for the whole document, not only for the canvas of jsmind. And I can't press, for example - Space, in another place on my page.

Problem place:
https://github.com/hizzgdev/jsmind/blob/d08e5c7ba87223a2a269afc292c1eec8deb4c5e8/js/jsmind.js#L2813

Not $d , but my canvas container, or .jsmind-inner blocks

**Comment by hizzgdev** [comment]
@Tilesto thanks for your mention, i just fixed the problem.
