### ISSUE TITLE
遇到的错误：jsmind.js:2306 the options.view.container was not be found in dom 。。。。

### ISSUE THREAD

**Issue by XiaoBaiRuler** [hizzgdev/jsmind#299]
你好！
问题描述：在我的项目中，有某个生成思维导图调用，会报以下错误：
jsmind.js:2306 the options.view.container was not be found in dom 。。。。
![image](https://user-images.githubusercontent.com/49758796/119245368-72843200-bbab-11eb-83a6-eb60800c5015.png)
但是其他和它类似调用，都没有出错；
补充：数据格式采用的是表对象格式，另外数据的格式都检查过了，没有问题。

**Comment by hizzgdev** [comment]
看着像是没有找到container，你在new jsMind之前看看能不能get到配置的container。

**Comment by XiaoBaiRuler** [comment]
谢谢，找到了，是另外一个插件出问题，导致页面元素丢失，影响到这里了
