### ISSUE TITLE
[Question] Support for bottom and top direction

### ISSUE THREAD

**Issue by xcesaralejandro** [hizzgdev/jsmind#304]
Is it possible to make the cards go up or down? I have checked the documentation and have not found anything about it.

Example:
````
            [LABEL 1]
                |
      _________ | ______
      |                  |
[LABEL 2]           [LABEL 3]
````

**Comment by hizzgdev** [comment]
@xcesaralejandro try this PR: https://github.com/hizzgdev/jsmind/pull/103

**Comment by xcesaralejandro** [comment]
Thanks you
