### ISSUE TITLE
发个新版本吧

### ISSUE THREAD

**Issue by kxcc** [hizzgdev/jsmind#305]
领导觉得几年没更新的软件，没人维护了，不让用了

**Comment by hizzgdev** [comment]
自力更生，艰苦奋斗，拒绝做伸手党，自己维护自己用哈。

**Comment by kxcc** [comment]
唉，仅仅是因为有要求禁止使用两年前的软件，就算我拿现有的代码二次开发，那也相当于我用了两年前的软件。
