### ISSUE TITLE
line_color 如何设置线条的颜色

### ISSUE THREAD

**Issue by zxylin** [hizzgdev/jsmind#306]
默认是统一设置；如果要实现不同层级的线条颜色不同要怎么修改js代码呢？各位大神指导下~

**Comment by hizzgdev** [comment]
搜索代码里的 draw_line ，顺藤摸瓜修改就好了。

**Comment by zxylin** [comment]
> 搜索代码里的 draw_line ，顺藤摸瓜修改就好了。

哈哈。我能力有限呀。。想从前端传不同参数进来让它画出不同的颜色线条出来

**Comment by zxylin** [comment]
自己摸索，已解决！

**Comment by kpwa** [comment]
how did you manage to achieve this? i have a similar question

**Comment by hizzgdev** [comment]
1. Given different colors for different node by it’s level
2. add a new color parameter to draw_line
3. Set stoke color
4. Done
