### ISSUE TITLE
怎么实现让root节点显示在浏览器正中间？

### ISSUE THREAD

**Issue by zxylin** [hizzgdev/jsmind#307]
如题~ 我想让页面一加载就让root节点显示在正中位置。

**Comment by hizzgdev** [comment]
默认情况下，会显示在container的正中间。要实现你的要求，需要你自己把container放在浏览器的正中间。

**Comment by zxylin** [comment]
明白，但我获取jsmind_container高度一直为 0，不知为何

**Comment by zxylin** [comment]
难道是因为我用了jsMind.util.ajax.get获取数据显示，才会这样？

**Comment by zxylin** [comment]
document.documentElement.scrollTop || window.pageYOffset || document.body.scrollTop
想获取滚动条的长度也一直都是0

**Comment by hizzgdev** [comment]
container 是需要你自行设置宽高的，jsmind 不会 “自动撑开” container。@zxylin
