### ISSUE TITLE
怎么把整体靠左显示，默认是居中。线条怎么换成折线 

### ISSUE THREAD

**Issue by lukg151154** [hizzgdev/jsmind#308]

**Comment by hizzgdev** [comment]
把整体靠左显示，默认时居中

这个是指只要右边，不要左边吗？如果是的话，你看一下文档就有答案。


线条怎么换成折线

翻翻之前的关闭的issue，有人问过相同的问题，需要自己做少许修改。

**Comment by lukg151154** [comment]
靠右是指：只要右边后，根节点左边紧贴容器

**Comment by hizzgdev** [comment]
紧贴左边容器需要自己实现，你先看看文档吧，改个参数试试符不符合你的需求。不行再改。

**Comment by lukg151154** [comment]
好的 谢谢
