### ISSUE TITLE
如何让双击事件不显示编辑框

### ISSUE THREAD

**Issue by NorthWind17** [hizzgdev/jsmind#309]
你好，我用的是format: 'node_tree',  support_html: true,   topic是生成的html结构，我想双击的时候不出现编辑框，我看到之前有人提过该问题，说源码里enable_dblclick_handle设为 false就不会出现，我试了下，不行，请问怎么解决啊

**Comment by xc327** [comment]
可以通过获取节点dom，添加双击事件，阻止冒泡来解决
const jmnodes = document.getElementsByTagName("jmnode");
Object.values(jmnodes).forEach((jmnode) => {
  jmnode.ondblclick = function (e) {
    e.preventDefault();
    e.stopPropagation();
  };
});
