### ISSUE TITLE
引入bootstrap3，选中节点字体颜色变为白色

### ISSUE THREAD

**Issue by radishj** [hizzgdev/jsmind#31]
引入`bootstrap3`，选中节点字体颜色变为白色(文字消失)，原因是`bootstrap primary`定义字体颜色为白色。

我的解决办法是第`2172`行加入
```
this.e_editor.style.color = 'black';
```

这样修改可能并不好，仅作提醒

**Comment by hizzgdev** [comment]
你试一下换一个主题：

```javascript
        var options = {
            container:'jsmind_container',
            theme:'greensea',
            editable:true
        }
```

theme实际上就是一个样式名，参见 jsmind.css 中的定义。

如果可行，烦请回复。感谢支持！

**Comment by ttsdzzg** [comment]
@radishj

**Comment by radishj** [comment]
解决方案是可以的，只是类名重复，有些属性被覆盖而已~ 换个主题就OK（建议像amaze一样，class上增加个前缀，避免干扰）

**Comment by hizzgdev** [comment]
@radishj 感谢回复。
下次更新会把所有的主题对应的样式名统一加个前缀。
