### ISSUE TITLE
让指定的节点居中

### ISSUE THREAD

**Issue by NorthWind17** [hizzgdev/jsmind#312]
你好，我看到之前#281这个问题，我需要一个大致相同的功能，我看你说用滚动条控制，如果是让最上方，最下方和最右方的节点居中，滚动条这个方式就不行了，还有什么方法么

**Comment by hizzgdev** [comment]
如果需要让“角落” 的节点居中的话，可能需要修改一下 [view.hmargin 和 view.vmargin](https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md#23-%E6%8E%92%E7%89%88%E9%80%89%E9%A1%B9) 这两个参数。

抱歉现在才回复您，如果还能有帮助的话将非常荣幸。
