### ISSUE TITLE
可以监听操作事件吗？

### ISSUE THREAD

**Issue by haoran0412** [hizzgdev/jsmind#315]
比如监听节点展开事件，因为要从远程加载数据。

**Comment by fanchao892** [comment]
dom 操作

**Comment by hizzgdev** [comment]
可以监听dom事件

**Comment by fanchao892** [comment]
> 比如监听节点展开事件，因为要从远程加载数据。

展开收起时，会触发   jm.click_handle 这个函数，可以看一下作者写的找找感觉，最好扩展一套触发节点事件的插件，方便后续使用

**Comment by aqu415** [comment]
源码里有这个函数，非常有用
       add_event_listener:function(callback){
            if(typeof callback === 'function'){
                this.event_handles.push(callback);
            }
        },
