### ISSUE TITLE
使用vue3-jsmind时，存在内存泄露的问题

### ISSUE THREAD

**Issue by ahjihyqw** [hizzgdev/jsmind#320]
我更改data的频率大概每秒一次，项目中集成了echarts插件，单独测试过了，不是echarts的问题，
测试js-mind组件时，任务管理器每秒增加10MB内存，2分钟后达到了2个多G

代码如下
`<js-mind v-for="item in minds" :values="item.data" :options="item.option" ref="jsMind" width="100%" height="6rem"></js-mind>`

**Comment by hizzgdev** [comment]
能提供个示例代码吗？

**Comment by ahjihyqw** [comment]
> 能提供个示例代码吗？
> […](#)
> 在 2022年4月18日，06:04，ahjihyqw ***@***.***> 写道： ﻿ 我更改data的频率大概每秒一次，项目中集成了echarts插件，单独测试过了，不是echarts的问题， 测试js-mind组件时，任务管理器每秒增加10MB内存，2分钟后达到了2个多G — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

我改回了原生js，自己适配vue，现在没有问题了。
顺便问一下有没有已经发布过的生产环境CDN

**Comment by ahjihyqw** [comment]
我这边只能找到未压缩的

**Comment by hizzgdev** [comment]
暂未提供，可以放到你的项目里。

**Comment by ahjihyqw** [comment]
> 暂未提供，可以放到你的项目里。
> […](#)
> 在 2022年4月20日，12:57，ahjihyqw ***@***.***> 写道： ﻿ 我这边只能找到未压缩的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

那有没有可以防止输出日志的办法呢，我不是专业的前端工程师

**Comment by ahjihyqw** [comment]
我这边每秒20多下刷新，把自己的日志都给覆盖了

**Comment by hizzgdev** [comment]
看看代码，把12行log那里改成noop就好了。
