### ISSUE TITLE
请问有办法实现全键盘操作吗？

### ISSUE THREAD

**Issue by klemperer** [hizzgdev/jsmind#321]
我使用了一下[Basic Demo](https://hizzgdev.github.io/jsmind/example/1_basic.html)，发现要先用鼠标点击一下某个节点，才能用快捷键新增子节点。添加完一个子节点后，尽管图上显示这个节点处于选中状态，但是，还是需要鼠标再点击一下，才能用快捷键添加下一个节点。
请问有办法解决需鼠标不断介入的问题、进而实现全键盘操作吗？谢谢！

**Comment by hizzgdev** [comment]
并不需要鼠标介入，你试试 jsmind.sinaapp.com

**Comment by klemperer** [comment]
感谢告知，我把两个js和一个css都换成sinaapp里面上的文件，可以实现全键盘操作了。其中，jsmind.js里面写的版本都是0.4.6，实际上内容不一样的是吗？

**Comment by hizzgdev** [comment]
github上的版本会比sinaapp上的高。
但是这跟全键盘操作应该无关。

**Comment by klemperer** [comment]
了解，但github上的demo，确实没办法实现全键盘操作，你可以再试试看。我先用sinaapp上这个版本了，感谢你的优秀作品！
> github上的版本会比sinaapp上的高。 但是这跟全键盘操作应该无关。
> […](#)
> 在 2022年4月28日，19:05，klemperer ***@***.***> 写道： ﻿ 感谢告知，我把两个js和一个css都换成sinaapp里面上的文件，可以实现全键盘操作了。其中，jsmind.js里面写的版本都是0.4.6，实际上内容不一样的是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

**Comment by hizzgdev** [comment]
@klemperer 确认了一下，这是在处理 #296 时 https://github.com/hizzgdev/jsmind/commit/4f3772d94252f8e6cac6e4ef6e5998467c12853f 引入的 bug，目前已经在 https://github.com/hizzgdev/jsmind/commit/934b3884528bd410737452e8cc586d13f0c51ca4 里修复了 。感谢支持。

**Comment by klemperer** [comment]
> @klemperer 确认了一下，这是在处理 #296 时 [4f3772d](https://github.com/hizzgdev/jsmind/commit/4f3772d94252f8e6cac6e4ef6e5998467c12853f) 引入的 bug，目前已经在 [934b388](https://github.com/hizzgdev/jsmind/commit/934b3884528bd410737452e8cc586d13f0c51ca4) 里修复了 。感谢支持。

感谢修复。但还是有个小问题：思维导图初次加载后，还是需要鼠标点击一下其中的一个节点才能操作。在sinaapp那个版本的js中，可以在页面显示思维导图后加上一句：jm.select_node(jm.get_root())， 之后就可以键盘操作了。但是最新的版本中，这个办法还是不行。我根据你修复的思路，在源代码init_nodes函数结尾处，加上一句this.e_panel.focus()，这样思维导图加载后可以直接键盘操作了。

**Comment by hizzgdev** [comment]
是的，方便的话可以提个pr。谢谢

**Comment by klemperer** [comment]
> 是的，方便的话可以提个pr。谢谢
> […](#)
> 在 2022年4月29日，09:20，klemperer ***@***.***> 写道： ﻿ @klemperer 确认了一下，这是在处理 #296 时 [4f3772d](https://github.com/hizzgdev/jsmind/commit/4f3772d94252f8e6cac6e4ef6e5998467c12853f) 引入的 bug，目前已经在 [934b388](https://github.com/hizzgdev/jsmind/commit/934b3884528bd410737452e8cc586d13f0c51ca4) 里修复了 。感谢支持。 感谢修复。但还是有个小问题：思维导图初次加载后，还是需要鼠标点击一下其中的一个节点才能操作。在sinaapp那个版本的js中，可以在页面显示思维导图后加上一句：jm.select_node(jm.get_root())， 之后就可以键盘操作了。但是最新的版本中，这个办法还是不行。我根据你修复的思路，在源代码init_nodes函数结尾处，加上一句this.e_panel.focus()，这样思维导图加载后可以直接键盘操作了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.

我这边没安装相关git环境，不太方便提pr，你可以直接修改哈，再次感谢

**Comment by hizzgdev** [comment]
OK

**Comment by hizzgdev** [comment]
> 感谢修复。但还是有个小问题：思维导图初次加载后，还是需要鼠标点击一下其中的一个节点才能操作。

@klemperer 我后来想了想，这应该是个正常的行为，原因有二：
1. 初次加载后，并没有“选中”某个节点，自然也就没法开始“上一个/下一个"
2. 对于一个页面来说，打开页面时自动 focus 到脑图上不应该是一个默认动作。

**Comment by klemperer** [comment]
> 

嗯理解，可能我要实现的效果比较独特:)，不过当手动调用jm.select_node(jm.get_root())选中根节点后，我理解应该还是要允许键盘操控，在init_nodes函数中focus到脑图可能不太好（虽然能暂时解决问题），不知道有没有其他更好的方法
