### ISSUE TITLE
Resize and adjusting container doesn't seems to work correctly

### ISSUE THREAD

**Issue by madsenfr** [hizzgdev/jsmind#322]
Hi,
Nice tool !
When it comme to get a large mind map, zoom in and out are useful, but container remains to its original size and resize function doesn't work.
Am I using it wrong or is there a bug on that function ?

**Comment by hizzgdev** [comment]
Maybe it’s a bug, would you please make a deep dive on it?

**Comment by hizzgdev** [comment]
Hi @madsenfr , is it still a problem?

**Comment by madsenfr** [comment]
Hi,
It still doesn't work properly, but I do not need it anymore as we get now an easy zoom in/out, and the ability to drag the mind map when it's bigger than the container.
