### ISSUE TITLE
Moving with a drag versus using scrollbars

### ISSUE THREAD

**Issue by madsenfr** [hizzgdev/jsmind#323]
Hi,
It would be nice to drag the map inside the container instead of using scrollbars to see the parts outside the container, especially when the container is bigger than the windows and you need to use first the window scrollbar before to use the container scrollbar.

**Comment by hizzgdev** [comment]
Thanks for your advice @madsenfr. TBH, jsmind is NOT a feature-completed version now. Let’s contribute it together, Thanks.

**Comment by madsenfr** [comment]
Hello,
As I needed it, and found a way to do it, here is the pull request https://github.com/hizzgdev/jsmind/pull/331

**Comment by hizzgdev** [comment]
resolved at https://github.com/hizzgdev/jsmind/pull/331
