### ISSUE TITLE
能否支持显示数学公式？

### ISSUE THREAD

**Issue by mgcyung** [hizzgdev/jsmind#325]

**Comment by hizzgdev** [comment]
目前是不支持的，感觉不像是个通用的需求，但是你可以自己扩展。

**Comment by mgcyung** [comment]
提了一个pull request #326，在例子里测试了一下mathjax的效果

![20220515-164004](https://user-images.githubusercontent.com/16061518/168464610-725c8d61-e998-4b01-b9a8-fc2612a044bf.png)

但不知该如何添加到jsmind中

**Comment by hizzgdev** [comment]
感谢 @mgcyung 实现比功能！ #330
