### ISSUE TITLE
在android webview中，总共500多个节点，拖动编辑一会，内存从200M暴增到5G，在拖动几下，oom~

### ISSUE THREAD

**Issue by KBiteMan** [hizzgdev/jsmind#327]
![image](https://user-images.githubusercontent.com/24225757/168478563-a0c280f9-7376-4ebc-871a-224eff179bcb.png)

**Comment by hizzgdev** [comment]
能看出来内存里都是什么吗？我用一个560多个nodes的脑图，发现在拖动节点的时候，内存会上涨到1G，结束拖动后马上又降回到100～200M。不确定在 webview 里有哪些不一样的地方。有意愿的话可以再深入研究一下，看看jsMind是否在哪里需要优化一下。谢谢。

**Comment by hizzgdev** [comment]
Close inactive issue
