### ISSUE TITLE
Can we have draggable nodes (but not editable)

### ISSUE THREAD

**Issue by MilitPanchasara** [hizzgdev/jsmind#329]
Hi,

I am using angular 8.2 and we have some specific requirements which I am not able to find with existing library.

We need draggable nodes, which can be placed randomly in the canvas, also nodes should not be editable as well.

As you can see in attached screenshot (it is blurry as it is zoomed out too much), we are dealing with larger maps so it would be great if nodes can be movable so that user can get better visualizations.

![image](https://user-images.githubusercontent.com/47338058/168796758-6a0d5468-f466-44ae-8f73-4cc695c7bb83.png)

Please look into it and let me know the possible solutions.
Thanks.

**Comment by madsenfr** [comment]
Hello,
About question 2️⃣, you may want to see issue https://github.com/hizzgdev/jsmind/issues/323, as it is the same, and got a pull request.

**Comment by MilitPanchasara** [comment]
Thank you @hizzgdev for the insights. Actually I was looking for solution for 2️⃣, but no worries.

@madsenfr, Thanks for pointing out, it is helpful. But #323 is slightly different than what we really wanted, we want specific node to move inside canvas, not whole map.
