### ISSUE TITLE
关于拖动整个节点会卡顿的问题

### ISSUE THREAD

**Issue by xiaoling123** [hizzgdev/jsmind#333]
在渲染脑图后快熟拖动整个节点，会有卡顿的问题先请教一下是否有优化方式呢？数据大概310kb左右

**Comment by hizzgdev** [comment]
你说的 “拖动整个节点” 是指手动整个画布吗？大概有多少节点呢？

**Comment by xiaoling123** [comment]
是的，就是鼠标拖动，800个节点左右

**Comment by hizzgdev** [comment]
先关闭了哈，有需要的话请随时再打开
