### ISSUE TITLE
这个显示模式，目前只有两种，都是水平方向的显示。可以支持垂直方向的显示吗？

### ISSUE THREAD

**Issue by chengsanjing** [hizzgdev/jsmind#342]

**Comment by hizzgdev** [comment]
之前有一个 PR https://github.com/hizzgdev/jsmind/pull/103 实现了这个功能，但是当时没来及测试。你如果有兴趣的话，可以尝试联系一下原作者，或者 fork 一下尝试重新整理一下？ @chengsanjing @perseverancer
