### ISSUE TITLE
hmargin，vmargin参数设置无效

### ISSUE THREAD

**Issue by geekwill** [hizzgdev/jsmind#343]

**Comment by hizzgdev** [comment]
我试了一下发现是可以生效的，你能再确认一下吗？或者明确一下具体的问题？

**Comment by hizzgdev** [comment]
@geekwill

**Comment by geekwill** [comment]
> 我试了一下发现是什么问题，你能再确认一下吗？

很感谢您的付出写出这么好的控件！

我这边目前的需求是想让根节点（root node）默认加载初始位置在容器的最左边，整体从左向右的延伸展开。
但是目前控制初始位置大概是在容器的最中间，所以我通过查看文档发现 hmargin、vmargin的字面意思是可以设置控件的初始位置的，然后我使用的过程中发现无效。最后通过下载并修改你的example发现依旧无效。

**Comment by hizzgdev** [comment]
你应该使用 `mode` 这个参数 https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md

**Comment by geekwill** [comment]
> 你应该使用 `mode` 这个参数 https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/23651539/172538971-f4d1efd1-3fd3-4dfe-b548-c94f93bc0026.png">

**Comment by hizzgdev** [comment]
终于明白了你的这个需求了……
目前没有提供相关的参数，如果你有兴趣可以考虑实现一下。

**Comment by hizzgdev** [comment]
或者你可以尝试修改一下代码里的 `_center_root` 这个方法，在自己项目里使用。 @geekwill

**Comment by geekwill** [comment]
> _center_root

 好的，我来看一看，如果咱们的注释详细一点可能就更好啦，感谢你的付出。

**Comment by hizzgdev** [comment]
好的，这个 issue 我就先关了哈。
