### ISSUE TITLE
如何让拖拽支持ES6

### ISSUE THREAD

**Issue by MTTTM** [hizzgdev/jsmind#350]
`import jsMind from "jsmind";
require("jsmind/js/jsmind.draggable");`

jsmind.draggable 无效，无法通过拖拽实现移动节点

**Comment by hizzgdev** [comment]
最近我在往es6上迁移，不过会比较慢。你可以自己试试迁移一下，然后提交个pr。

不过如果你着急用的话，也可以把代码和在一起，在自己的项目里用。

**Comment by hizzgdev** [comment]
Close old issues
