### ISSUE TITLE
整个页面无法进行自由拖拽

### ISSUE THREAD

**Issue by hurahoo** [hizzgdev/jsmind#366]
整个页面无法进行拖拽，但是节点比较多的时候，会遮挡，整个时候无法拖拽整体

**Comment by south936** [comment]
请问解决了吗?我也遇到这个问题了 ,放大之后拖拽显示不全

**Comment by hizzgdev** [comment]
两位的问题是不是也不太一样？

@hurahoo  是只有当节点比较多的时候不能拖拽吗？能不能提供一个测试数据？

@south936 放大是指调用了 zoomIn 这个方法了吗？拖拽显示不全是指连接线显示不全吗？

**Comment by hizzgdev** [comment]
请确认一下用的是不是最新的版本。如果还不行的话，能不能告诉我这个问题中节点较多具体是指有多少？

**Comment by hurahoo** [comment]
不好意思，没注意信息，一个是浏览器兼容，火狐和谷歌有的版本不能拖拽，升级完版本后可以了，这个我再确认下，另外一个是百分比缩小后，没居中
