### ISSUE TITLE
一个node只能有一个parent

### ISSUE THREAD

**Issue by Cynun** [hizzgdev/jsmind#367]
我在尝试用jsmind绘制类似下图的“科技树”
![image](https://user-images.githubusercontent.com/110143030/181880307-ea5f1c08-57e4-4339-97e3-c648474d3890.png)
但是我的树拥有![image](https://user-images.githubusercontent.com/110143030/181880329-25f709bf-cd33-4e01-b56c-67d6c3fffc07.png)这样的有两个（及以上）parent的节点。
我尝试在data中加入`"parentid": ["1","2"]`这样的片段，但是这样做jsmind会直接不绘制对应的节点。
document中也没有对应的功能说明，请问是我的用法不对还是jsmind没有对应的实现？

**Comment by hizzgdev** [comment]
是 jsmind 不支持这种图😂

**Comment by Cynun** [comment]
所以只能自己实现了是吗☹

**Comment by hizzgdev** [comment]
😂😂😂😂😂
加油吧少年！

搞好了可以给 jsmind 提 pull-request
