### ISSUE TITLE
添加到npm - 已处理

### ISSUE THREAD

**Issue by tiaod** [hizzgdev/jsmind#37]

**Comment by hizzgdev** [comment]
@tiaod  感谢你的支持，不过我对 node 不太了解，你能帮我处理这个问题吗？

**Comment by tiaod** [comment]
发布到npm主要是方便webpack以及browserify的用户使用。我也很想帮你，但是我看了一下发布的流程，发现是需要自己创建一个用户并设置密码，才能进行发布。所以发布工作最好由作者亲自完成: )

https://docs.npmjs.com/getting-started/publishing-npm-packages
这里有篇视频教程，教你如何发布npm包。

https://github.com/vuejs/vue
这里有个前端项目，是发布到npm的，你可以参考它的`package.json`写法。

不要忘记`package.json`的main字段需要包括样式文件。你可以这样写
```json
{
  main:["js/jsmind.js","js/jsmind.draggable.js","style/jsmind.css"]
}
```

祝你好运！

**Comment by hizzgdev** [comment]
@tiaod 感谢，我学习一下，尽快处理该问题。

**Comment by hizzgdev** [comment]
https://www.npmjs.com/package/jsmind
