### ISSUE TITLE
截图问题

### ISSUE THREAD

**Issue by Xiong-Zz** [hizzgdev/jsmind#370]
1、图片没有背景色
2、在options中设置support_html: true后，图片上显示的是html语句

**Comment by hizzgdev** [comment]
1这个问题里的图片是个背景透明的图片吗，然后把这个图片放到node里，截图时没有把node的背景颜色显示出来。是这个意思吗？

2这个问题是个已知问题，目前也没有合适的解决方案，你可以翻翻之前的issue，之前讨论过。如果你有合适的解决办法也可以再聊。

**Comment by Xiong-Zz** [comment]
- 1的问题是指调用shootDownload方法后，自动生成下载的图片是没有底色的，此时jsmind-container有设置背景色。但是用shootAsDataURL方法生成的base64url，下载下来的图片是有背景色的
- 2的问题有尝试用过其他库完成，但是普遍存在的问题是仅限于视窗大小。如果利用缩放来让所有元素都集中在画布上，最后的截图会出现元素错乱的情况

**Comment by Xiong-Zz** [comment]
目前配合dom-to-image插件已经解决support-html下的截图问题。jsmind-inner的样式要注释掉overflow属性，再配合dom-to-image就可以解决截图问题

**Comment by hizzgdev** [comment]
> 1的问题是指调用shootDownload方法后，自动生成下载的图片是没有底色的，此时jsmind-container有设置背景色。

jsmind-container 里的背景颜色确实没有，这个也不会支持。原因是在 jsMind 的理念里，container 是 jsMind 之外的，它可以有很多自定义的样式，jsMind 不会对其进行读写，仅仅把脑图放在里面。

如果项目中需要截图带 container 的背景颜色，你可以自行修改源码并在你的项目里使用；
如果需要 jsMind 本身支持背景颜色，那么应该先在 option 中添加背影颜色的参数，然后再看如何实现它。

@Xiong-Zz

**Comment by hizzgdev** [comment]
> 2的问题有尝试用过其他库完成，但是普遍存在的问题是仅限于视窗大小。如果利用缩放来让所有元素都集中在画布上，最后的截图会出现元素错乱的情况
>
> 目前配合dom-to-image插件已经解决support-html下的截图问题。jsmind-inner的样式要注释掉overflow属性，再配合dom-to-image就可以解决截图问题

感谢你提供的这个信息，大概看了一下 dom-to-image ，发现它的设计非常奇妙，有时间会考虑借鉴一下它的思路支持一下这个问题。 多谢 @Xiong-Zz

**Comment by rcdingning** [comment]
> 目前配合dom-to-image插件已经解决support-html下的截图问题。jsmind-inner的样式要注释掉overflow属性，再配合dom-to-image就可以解决截图问题

感谢, 可以实现
