### ISSUE TITLE
Question about some ideas to a relative postion of some nodes

### ISSUE THREAD

**Issue by pmario** [hizzgdev/jsmind#371]
Hi, I did discover this library some hours ago. ... It seems to be very close to what I was searching for years \o/ -- Even the internal data structure is very close to what we use already. -- Well done. 

Question: Did you ever consider to allow the nodes to have an additional `delta x` and `delta y` value, to allow them to be at a different location than usually calculated by the default "positioning" algorithm. 

The idea is as follows. .. I personally believe, that for mind mapping "positional data" like "proximity" or "distance" of different nodes has a meaning. 

In the first step while brain storming, where ideas are mainly "chaos", a mind map should be "fast". So chaotic-ideas can be collected in "real time" ... 

In a second step the maps should allow the user to "untangle" the chaos and sort the mind-map. ... 

It seems the current implementation allows a fast collection and sorting is possible with drag and drop. ... But ... It's not possible to create maps, where the relative position of nodes and sub-nodes has a meaning. ... They are all equidistant using the default settings. 

I think this would be a nice improvement ... My idea would be to use a meta-key and "drag node" to add some "delta-coordinates" to the internal structure, that can be used to **add** a relative position. 

What do you think?

**Comment by hizzgdev** [comment]
Thanks for your great inputs, @pmario . I agree with you that it would be useful to `allow the nodes to have an additional delta x & y` value. But I would to say, it may not a good solution to your `untangle` case, a document would be more appropriate?

There are many additional relationships that are not very easy to express with a simple map:
  - proximity and distance
  - cause and effect
  - important and unimportant

I'm expected that the features could be supported in a plugin way, by the open source developers 😂 

Another question is it's not an easy work to support the `delta x/y` feature, think about expand/collapse, and the overlap of nodes.

Feel free to append comments if you have any ideas about it.

**Comment by pmario** [comment]
@hizzgdev Thanks for your fast reply. ... I'll try to use the library as it is atm anyway. ... 

>Another question is it's not an easy work to support the delta x/y feature, think about expand/collapse, and the overlap of nodes.

I didn't have the time to look at the code in detail, but from the functionality of demo 2 -- feature demo, it seems if elements are collapsed or expanded, the position of the "surrounding" elements are recalculated already. So I'll have to have a closer look at the maths there. .. :)

> I'm expected that the features could be supported in a plugin way, by the open source developers 😂

I've seen, that there is a plugin system.  --- I'll need to dig a bit deeper into the code first. 

------------

I've seen, that SVG paths are used to draw the connections between nodes. ... Did you consider a full SVG export, instead of a PNG screenshot?

**Comment by hizzgdev** [comment]
> I've seen, that SVG paths are used to draw the connections between nodes. ... Did you consider a full SVG export, instead of a PNG screenshot?

I did. It's not a prefect solution since the style in stylesheet will lose in the exported SVG.
