### ISSUE TITLE
Can I hook the event of dragging node to another parent?

### ISSUE THREAD

**Issue by lofti198** [hizzgdev/jsmind#372]
Can I handle event, when after dragging node A onto node B, its parent changes to node B?

**Comment by hizzgdev** [comment]
see [add_event_listener](https://github.com/hizzgdev/jsmind/blob/master/src/jsmind.js#L646) and [move_node](https://github.com/hizzgdev/jsmind/blob/master/src/jsmind.js#L444), you will get the answer.
