### ISSUE TITLE
jsmind with react

### ISSUE THREAD

**Issue by coder-do** [hizzgdev/jsmind#373]
Hi,
we have a repository [this](https://github.com/lofti198/react-jsmind/tree/dev), which imports jsmind to render tree of elements on the page.  And we have a problem - we can't use `drag and drop` and other files `jsmind.draggable.js` , `jsmind.shell.js`, because they are separate files and are not imported in main `jsmind.js` file.
Do you know how we can solve this issue? Or you have any reference how use this library with react, it will also help us!

P.S I tried to import these files in `public/index.html` and then use in react file as `window.jm` but without result. Also tried to import in `components.jsx` but also without result.

**Comment by hizzgdev** [comment]
I am not good at React, would you mind trying the ES6 version?
The ES6 code is located in `/src`, and the js files that can run in browsers are located in `/es6`
