### ISSUE TITLE
Can I add relations (associative connections)?

### ISSUE THREAD

**Issue by lofti198** [hizzgdev/jsmind#374]
Hello! Can I add relations (associative connnections)? Like this
![image](https://user-images.githubusercontent.com/42960488/187020559-feec28e2-bb47-43b3-b50a-1668bcecebdf.png)

If it is possible, how can I specify them in mind object like this:
![image](https://user-images.githubusercontent.com/42960488/187020594-d3f7a2e9-cfe2-4d64-b76d-830b6c18be48.png)

 [
                        { id: 'root', isroot: true, topic: 'MainTopic' },
                        { id: 'subtopic1', parentid: 'root', topic: 'Subtopic1' },
                        { id: 'sub1', parentid: 'subtopic1', topic: 'Sub1' },
                        { id: 'sub11', parentid: 'sub1', topic: 'Sub11' },
                        { id: 'sub12', parentid: 'sub1', topic: 'Sub12' },
                        { id: 'sub121', parentid: 'sub12', topic: 'Sub121' },
                        { id: 'sub13', parentid: 'sub1', topic: 'Sub13' },
                        { id: 'sub2', parentid: 'subtopic1', topic: 'Sub2' },
                        { id: 'sub21', parentid: 'sub2', topic: 'Sub21' },
                        { id: 'sub22', parentid: 'sub2', topic: 'Sub22' },
                        { id: 'subtopic2', parentid: 'root', topic: 'Subtopic2' },
                        { id: 'sub3', parentid: 'subtopic2', topic: 'Sub3' },
                    ];

**Comment by hizzgdev** [comment]
I’m afraid it’s not supported.🤷‍♂️

**Comment by lofti198** [comment]
Ok thank you! If you suggest the direction how to implement it I would appreciate!

**Comment by hizzgdev** [comment]
I prefer add a new field (relationship) in the `Mind` object, and build plugin for different type of relationship.
Considering that there are different types, the relationship need to be implemented in the plugin.

For you case, I think you may need to get the point(In/Out) of the node, it is in the node object, you can get it in chrome console panel.

```json
{
    "meta":{...},
    "format":"node_array",
    "data":[],
    "relationship": [
        {
            "relationType": "Type_Enum",
            ... varags depends on type
        },
        {
            "relationType": "Type_Enum",
            ... varags depends on type
        }
    ]
}
```

**Comment by lofti198** [comment]
Thank you for your fast help and coollibrary!

**Comment by lofti198** [comment]
One more thing - do you take orders for paid adding features like this? And how much would that cost?
![image](https://user-images.githubusercontent.com/42960488/187075873-a00a116c-e318-42be-82ba-e8b1ec4414cc.png)

**Comment by hizzgdev** [comment]
Sorry, I have not a plan to the paid features yet.Because I can’t promise a clear timeline for them.

I will consider the feature more, and the paid support plan. But I guess it will take a long time.
