### ISSUE TITLE
How I can set the maximum number of symbols to show for big string?

### ISSUE THREAD

**Issue by lofti198** [hizzgdev/jsmind#375]
How I can set the maximum number of symbols to show for big string? Also is there a way to create multiline node?

![image](https://user-images.githubusercontent.com/42960488/187064417-8f0c63c7-465a-4daa-bab2-bc37c6932cac.png)

**Comment by hizzgdev** [comment]
> How I can set the maximum number of symbols to show for big string?

We can set the maximum width of the node, which is set in the style sheet.

**Comment by hizzgdev** [comment]
> is there a way to create multiline node?

Use HTML

**Comment by lofti198** [comment]
Thank you! I see!
