### ISSUE TITLE
Can I avoid moving canvas when dragging nodes?

### ISSUE THREAD

**Issue by lofti198** [hizzgdev/jsmind#376]
Found the following behavior : https://somup.com/c3jUfXUXVC . Can the canvas stay on its place, when dragging nodes?

**Comment by madsenfr** [comment]
Hello,
I think I'm the one responsibe for that ;-)
Simply set the draggable view option to false, see https://github.com/hizzgdev/jsmind/blob/master/docs/en/2.options.md

**Comment by hizzgdev** [comment]
I think it’s a bug needs to be fixed.

**Comment by madsenfr** [comment]
Not really a bug but something that we forgot to do and to test.
The draggable option works just as it is intend to do.
Now if we want it not to drag the whole map when in edit mode and when a node is selected, we just need to add a condition based upond edit option (easy to do) and when a node selection event is fired (that I don't know to do).
If someone can give a hint to get the node selection status, I can easily add the new feature.

**Comment by madsenfr** [comment]
I've fixed it in PR #377.

**Comment by hizzgdev** [comment]
Thanks @madsenfr , I leave a comment in the PR, PTAL.
