### ISSUE TITLE
Colored labels

### ISSUE THREAD

**Issue by MelkorNemesis** [hizzgdev/jsmind#38]
Hello,

would it be possible to add different background colors per label?

E.g.
{"id":"root", "isroot":true, "topic":"jsMind","background": "#ffff00"},
{"id":"sub1", "parentid":"root", "topic":"sub1","background": "#ff0000"}

Thanks

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/pull/39

hi @MelkorNemesis , i added a feature to try to resolve your problem, have not been thoroughly tested. you may try it out. 
Thank you.

**Comment by MelkorNemesis** [comment]
Thanks mate! I will try it and let you know. Great job.

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/pull/39

**Comment by DHJesus** [comment]
How to resolve?Thanks
