### ISSUE TITLE
如何关闭日志

### ISSUE THREAD

**Issue by Xiong-Zz** [hizzgdev/jsmind#380]

**Comment by hizzgdev** [comment]
找到源码，把log改成_noop就好了，有时间我给加个选项。

**Comment by hizzgdev** [comment]
添加了一个 `log_level` 的选项，设置为 `disable` 就能关闭所有日志了。 文档在这里：https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md#22-%E5%B8%B8%E8%A7%84%E9%80%89%E9%A1%B9

不过需要使用 es6 版本的 jsmind, 可参考这个网页 http://hizzgdev.github.io/jsmind/example/2_features_es6.html

@Xiong-Zz
