### ISSUE TITLE
jm.update_node的bug

### ISSUE THREAD

**Issue by Xiong-Zz** [hizzgdev/jsmind#383]
利用jm.update_node更新未展开的节点，更新完后展开节点会出现重叠问题

**Comment by hizzgdev** [comment]
感谢反馈，稍后我会确认一下这个问题。

**Comment by hizzgdev** [comment]
@Xiong-Zz 这个问题已经修复了。再次感谢。

**Comment by Xiong-Zz** [comment]
> @Xiong-Zz 这个问题已经修复了。再次感谢。

3Q，npm仓库也很久没更新了，麻烦有空推送一下哈

**Comment by hizzgdev** [comment]
OK

**Comment by hizzgdev** [comment]
> 3Q，npm仓库也很久没更新了，麻烦有空推送一下哈

已更新 @Xiong-Zz
