### ISSUE TITLE
请问作者有考虑实现xmind的复制粘贴文本为导图的功能吗

### ISSUE THREAD

**Issue by pphgood** [hizzgdev/jsmind#389]
xmind中可以复制导图 粘贴为用空格代表层级的文本 也可以拿这个文本直接粘贴到xmid中生成对应导图，请问作者有考虑过如何实现这个功能吗

**Comment by hizzgdev** [comment]
XMind 的这个功能只能按文本导入（粘贴）吗？能不能导出这种格式的文本？

**Comment by pphgood** [comment]
> 
XMind 可以通过鼠标拖拽选择需要导出的部分导图，然后直接ctrl +c ，ctrl+v 出去就可以生成文本 类似如下：
父节点
    子节点
        子节点
同时也可以用以上文本复制粘贴进入xmind 直接生成对应导图

**Comment by pphgood** [comment]
> XMind 的这个功能只能按文本导入（粘贴）吗？能不能导出这种格式的文本？

![0b534367c6020a013d2a9db543c6ace](https://user-images.githubusercontent.com/101175483/194827413-9d27e415-ba9b-4196-8332-35bbeb7a6a31.png)
格式类似于这种

**Comment by pphgood** [comment]
> 

好的 感谢回答

**Comment by pphgood** [comment]
> > 
> 
> 好的 感谢回答



> 这种功能之前考虑过，但没有计划实现到jsmind 里，jsmind 更关注于脑图如何呈现出来，用户交互部分不是 jsmind 关注的重点。
> 
> 不过如果我们把这种文本看作是一种特殊的脑图格式，倒是也可以考虑支持它，但是不会有局部复制粘贴的能力。
我实现了从xmind复制部分导图然后粘贴到JSmind中，如果作者有兴趣的话，我可以提供代码

**Comment by pphgood** [comment]
> 这种功能之前考虑过，但没有计划实现到jsmind 里，jsmind 更关注于脑图如何呈现出来，用户交互部分不是 jsmind 关注的重点。
> 
> 不过如果我们把这种文本看作是一种特殊的脑图格式，倒是也可以考虑支持它，但是不会有局部复制粘贴的能力。

不只是包括复制xmind，复制特定格式的文本也可以

**Comment by hizzgdev** [comment]
是提供了新的api方法吗？还是使用现有的方法？

可以分享一下，感谢！

**Comment by pphgood** [comment]
> 是提供了新的api方法吗？还是使用现有的方法？
> 
> 可以分享一下，感谢！

 我直接发你的邮箱吧，不过我目前使用没有进行封装 如果你要加进JSmind的话可以自己封装一下

**Comment by hizzgdev** [comment]
谢谢

**Comment by pphgood** [comment]
> 谢谢

邮件已经发送至你的这个邮箱[hizzgdev@163.com]，描述的可能不是很清楚，如果有问题可以沟通

**Comment by hizzgdev** [comment]
收到了，谢谢。

**Comment by pphgood** [comment]
> 收到了，谢谢。

我刚刚在使用这个粘贴Ctrl+V的时候发现了一个问题，在修改节点名称时，我粘贴时也触发了这个粘贴文本转为导图事件，我的解决方案是用一个全局变量isEdit默认为false 在编辑节点时isEdit变为true 当isEdit为true时return转化导图事件，这样就可以避免上面的问题，然后在结束编辑时将isEdit改为true

**Comment by pphgood** [comment]
> 收到了，谢谢。
你好 我想在每个jmnode节点上面点击添加增加删除的按钮时遇到了困难，请问如果想实现这个操作 应该在代码的哪部分添加我的button结构，感谢
