### ISSUE TITLE
你好，我想在节点中添加额外的数据，使用node中的data，但是始终起不了作用，可否给一个data的简单设置案例。

### ISSUE THREAD

**Issue by niuzhi** [hizzgdev/jsmind#390]
需求node中data的一个简单案例

node {
    id,        //  : string                    节点id
    index,     //  : integer                   节点序号
    topic,     //  : string                    节点主题
    isroot,    //  : boolean                   指示该节点是否为根节点
    parent,    //  : node                      该节点的父节点，根节点的父节目为 null ，但请不要根据此属性判断该节点是否为根节点
    direction, //  : enum(left,center,right)   该节点的分布位置
    children,  //  : array of node             该节点的子节点组合
    expanded,  //  : boolean                   该节点的下级节点是否展开
    data,      //  : object{string,object}     该节点的其它附加数据
}

**Comment by hizzgdev** [comment]
你是按文档添加的吗？下面链接里的3.4章节？
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/3.operation.md

**Comment by niuzhi** [comment]
是的，请问一下，能否给提供一个案例，我这边试了好长时间添加不上去

**Comment by wenliumeng** [comment]
我不太懂js，请问一下，我看demo界面上没有显示{'a':'hello', 'b':'world'}的地方，需要自己写js代码把它提取出来然后展示，是这个意思吗

**Comment by hizzgdev** [comment]
是的，数据只是数据，默认情况下并不会显示出来，需要显示的话你可能需要自己开发一下。
