### ISSUE TITLE
jsmind放大后顶部区域不显示

### ISSUE THREAD

**Issue by Xiong-Zz** [hizzgdev/jsmind#391]
超过屏幕上边界的区域直接被裁剪掉，滚动栏显示已经拉到最上面了

**Comment by Xiong-Zz** [comment]
![image](https://user-images.githubusercontent.com/61372665/197430131-22014232-a650-43a5-84c9-b350f50efe40.png)

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/issues/387
你要不用最新版本再试试？

**Comment by Xiong-Zz** [comment]
是最新版本的，npm版本号0.4.10

**Comment by hizzgdev** [comment]
我刚把 npm 上的版本更新到了 0.4.11，你再试一下吧。
