### ISSUE TITLE
画布保持位置

### ISSUE THREAD

**Issue by xiaoxiao-96** [hizzgdev/jsmind#393]
因为项目需要动态加载节点数据，在调用jsmind的show方法重新渲染数据时，会重新回到画布中央，这样用户需要自己手动拖拽到上一次点击的地方，怎么样能不改变画布原有位置呢，可以实现吗

**Comment by hizzgdev** [comment]
你这每次都是重新 show 整个脑图的吗？如果这样的话，可能需要你自己把脑图活动到原来的位置了。

或者你可以考虑在原有的脑图上直接添加修改节点。

**Comment by xiaoxiao-96** [comment]
对，是重新show的。昨天看了您源码鼠标拖拽的方法，用scrollby已经实现了画布保持不动了，谢谢~

**Comment by hizzgdev** [comment]
👍
