### ISSUE TITLE
希望能完全支持npm 并支持自由控制每个节点的样式

### ISSUE THREAD

**Issue by ALNY-AC** [hizzgdev/jsmind#394]

**Comment by hizzgdev** [comment]
能具体说明一下什么是完全支持npm吗？

**Comment by dakang824** [comment]
节点与节点之间的样式不可以自定义

**Comment by hizzgdev** [comment]
> 节点与节点之间的样式不可以自定义

你是指让各节点的样式可以不同吗？还是指自定义线条？ @dakang824

**Comment by dakang824** [comment]
> > 节点与节点之间的样式不可以自定义
> 
> 你是指让各节点的样式可以不同吗？还是指自定义线条？ @dakang824

就是节点与节点之间的线的颜色可以自定义

**Comment by hizzgdev** [comment]
>>> 节点与节点之间的样式不可以自定义
>>
>> 你是指让各节点的样式可以不同吗？还是指自定义线条？ @dakang824
>
>就是节点与节点之间的线的颜色可以自定义

后续可以考虑支持

**Comment by hizzgdev** [comment]
> > > 节点与节点之间的样式不可以自定义
> > 
> > 
> > 你是指让各节点的样式可以不同吗？还是指自定义线条？ @dakang824
> 
> 就是节点与节点之间的线的颜色可以自定义

在 #399 支持了。 https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md#14-%E6%A0%B7%E5%BC%8F

**Comment by dakang824** [comment]
牛逼
