### ISSUE TITLE
节点收缩/展开控制器小圆点 展开能否设置为只展开下一级节点

### ISSUE THREAD

**Issue by pphgood** [hizzgdev/jsmind#396]
你好，我又来了hh，节点收缩/展开控制器小圆点 展开能否设置为只展开下一级节点，而不是展开所有子节点

**Comment by hizzgdev** [comment]
我记得他就是只展开下一级节点的。你是怎么测试的？

**Comment by pphgood** [comment]
> 我记得他就是只展开下一级节点的。你是怎么测试的？

我如果想写一个函数，只展开这个节点的下一层这个如何实现

**Comment by pphgood** [comment]
经过测试 如果手动将子节点收缩后，再展开的话就不会展开收缩的节点，是不是节点的expand属性默认为true,收缩之后为false，这样就不会展开了

**Comment by pphgood** [comment]
一个投机取巧的办法，先关闭所有节点，这个时候打开就默认只打开下一层了

**Comment by hizzgdev** [comment]
是的，因为下级本来就是展开的，所以自然就是保持原来的样子。

**Comment by pphgood** [comment]
> 是的，因为下级本来就是展开的，所以自然就是保持原来的样子。

还有个bug，我的第一层节点的第一个节点总是无法选中和编辑还有没办法点击圆点展开，不知道是不是什么冲突了，作者有遇到这个bug吗

**Comment by hizzgdev** [comment]
没注意到这个情况，你能不能验证一下，看在demo页中有没有这个问题？

**Comment by pphgood** [comment]
> 没注意到这个情况，你能不能验证一下，看在demo页中有没有这个问题？

demo中没出现这个情况，这个问题不知道怎么去debug，是这个节点没添加上事件？
