### ISSUE TITLE
导图初始化加载时，连接的线条未加载出来

### ISSUE THREAD

**Issue by pphgood** [hizzgdev/jsmind#397]
你好，我刚才在使用时，突然导图初始化加载时，连接的线条未加载出来，我如果点击扩展的圆点之后，这个线条又加载出来了，请问作者知道这是什么情况吗

**Comment by hizzgdev** [comment]
如果能稳定复现的话，就是一个bug。
如果不能的话，我也说不了是啥情况……可能只能看到当时console里的log才能知道问题是啥。

**Comment by pphgood** [comment]
我目前也不知道是什么原因，这个问题是我在点击节点跳转到新页面再返回时出现的，然后就一直就有了（可能和我用的代码框架又关系），没有报错，我点一下扩展，线条又出来了，我目前解决方案是，在加载完成后触发一个扩展到下一级，然后线条就会显示

**Comment by hizzgdev** [comment]
“返回”是指浏览器的后退吗？

再出现这个情况的话，看看dom里的canvas的大小是多大，另外浏览器是chrome吗？
