### ISSUE TITLE
期望能过提升下性能，在数据量达到万级的话，会导致无响应。

### ISSUE THREAD

**Issue by geekwill** [hizzgdev/jsmind#398]
在数据量达到5万条时，浏览器会无响应。
打了下断点，jm.view_provider.show_nodes方法会卡死，执行不下去。

测试设备：macbookpro i7 2.8GHz 四核  16GB
测试浏览器：最新版谷歌浏览器
数据量：48500条

view.engine = svg

**Comment by hizzgdev** [comment]
能问下你这是什么需求吗？5万条数据的脑图是不是不太适合用**一张**脑图来呈现？
