### ISSUE TITLE
添加右键菜单

### ISSUE THREAD

**Issue by qboy1987** [hizzgdev/jsmind#40]
建议添加右键添加菜单，目前在我的电脑里没有del键，无法对节点进行删除？是否有其它方式删除？

**Comment by hizzgdev** [comment]
jsMind并没有在交互方面进行过多设计，一方面是因为jsMind是一个类库，交互并不是其的关注点；另一方面，用户交互比较贴近业务或者使用习惯，而这方面不同的场景会有不同的需求，jsMind统一提供反而不太合适。不过jsMind提供了很多接口，如果需要的话，可以根据自己的需求自行处理用户交互逻辑。

另外，你的电脑是 mac 吗？ mac 里的 fn + delete 就相当于 pc 里的 del 。

**Comment by cjz9032** [comment]
交互太多就大了..我就是要个这么简单的  我自己加一发交互就好了

**Comment by hizzgdev** [comment]
@cjz9032  Right!
