### ISSUE TITLE
mode:full不生效

### ISSUE THREAD

**Issue by lesvate** [hizzgdev/jsmind#408]
> add_node: function (parent_node, nodeid, topic, data, direction, expanded, idx) {
            if (!jm.util.is_node(parent_node)) {
                logger.error('the parent_node ' + parent_node + ' is not a node.');
                return null;
            }
            var node_index = idx || -1;
            var node = new jm.node(nodeid, node_index, topic, data, false, parent_node, parent_node.direction, expanded);
            if (parent_node.isroot) {
                node.direction = direction || jm.direction.right;
            }
            if (this._put_node(node)) {
                parent_node.children.push(node);
                this._reindex(parent_node);
            } else {
                logger.error('fail, the nodeid \'' + node.id + '\' has been already exist.');
                node = null;
            }
            return node;
        },

node.direction = direction || jm.direction.right;
这里direction 未设置则会导致node.direction永远等于jm.direction.right，也就是mode：full时，并不会自动切换左右，请作者看看是否有这情况

**Comment by hizzgdev** [comment]
你使用的是 `mind` 对象的 `add_node` 吧，试试 `jsMind` 对象的 `add_node`.

**Comment by lesvate** [comment]
用的是jsmind

> 你使用的是 `mind` 对象的 `add_node` 吧，试试 `jsMind` 对象的 `add_node`.
用的jsMind.show(options,mind)方法初始化的，没有单独调用add_node方法，我是调试定位到这个方法的，是我初始化方式错误么？请指教

**Comment by lesvate** [comment]
demo里的basic也是没设置mode和direction，我理解应该mode默认为full，此时应该自动切换左右

**Comment by hizzgdev** [comment]
你应该是打开一个现有的脑图吧，或者是生成了一个 jsmind 的 json 对象，然后交给 jsMind show 的吧，这种情况下确实节点只会在右边。原因是`mode: full` 这个选项只有在调用 `jm.add_node` 这个方法时会起作用，而解析一个 mindmap 文件（或 json 数据）时是用不到这个选项的。

这么设计原因有两点：
- 如果一个脑图画好了，那它的布局结构应该是固定的，不应该受到 option 的影响；
- 打开一个脑图时，我们对它的期待应该是跟上次保存时的布局结构一样。

所以 `mode: full` 这个选项就只用在了设计脑图的过程中，而不会在呈现脑图时生效。

换句话说，交给 jsMind show 的那个对象应该有显式的左右设置的，你可以在生成 json 的时候选择“左-右-左-右”的模式或者“右-右-左-左”的模式，这样也更方便开发者自由处理吧。

@lesvate

**Comment by lesvate** [comment]
ok，那我处理下数据吧，建议在文档中加上说明，感觉容易像我一样不理解的情况

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md

文档已更新，感谢提醒。 @lesvate
