### ISSUE TITLE
怎么控制键盘addchild只向右生成节点

### ISSUE THREAD

**Issue by tangyibo000** [hizzgdev/jsmind#409]
怎么控制键盘addchild只向右生成节点，看了prototype有一个layout.calculate_next_child_direction()函数，不能取消右生成一个左生成一个这种方式

**Comment by hizzgdev** [comment]
mode : (string) 显示模式，jsMind 现支持两种显示模式:

> full - 子节点动态分布在根节点两侧 [默认值]
> side - 子节点只分布在根节点右侧

https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md
改成 'side' 即可
