### ISSUE TITLE
通过 update_node 方法修改节点方向不生效

### ISSUE THREAD

**Issue by WangYingling** [hizzgdev/jsmind#415]
节点添加的代码如下：
`var selectedNode = _jm.get_selected_node(); // as parent of new node
        if (!selectedNode) {
            layer.msg('请先选中节点');
            return;
        }
        var newNode = this.newNode(null,selectedNode.id,"<i>请输入条件</i>",null,false,"left",false
            ,true,false,false,false,true);
        var addNode = _jm.add_node(selectedNode,newNode.id,newNode.topic,newNode);
        //调整方向"left";  这里尝试赋值为left，也不生效
        addNode.direction=-1;
        _jm.update_node(addNode.id,addNode.topic);`

**Comment by hizzgdev** [comment]
```
var newNode = this.newNode(null,selectedNode.id,"<i>请输入条件</i>",null,false,-1,false ,true,false,false,false,true);

```

有没有试过这样？

**Comment by hizzgdev** [comment]
@WangYingling 请问这个问题有什么更新吗？

**Comment by WangYingling** [comment]
尝试了你的办法还是不行。我再看看有么有别的办法

**Comment by WangYingling** [comment]
我跟踪了下代码，发现在修改了node的其他属性之后，源码里没有调用布局方法，所以才无法改变默认的right布局。后来修改了源码如下图：添加了两行代码
![image](https://user-images.githubusercontent.com/23132769/215089718-2cd5fb78-e578-4f5b-af50-76f9874c99e1.png)

**Comment by WangYingling** [comment]
> @WangYingling 请问这个问题有什么更新吗？

问题已经解决，我更新了源码，见上一个回复

**Comment by hizzgdev** [comment]
你这是“修改节点”，而不是“添加节点”？
这个按说应该把`if`的条件改一下，不过能用就行。感谢你的回复，我有时间看看这里如何优化一下。

**Comment by WangYingling** [comment]
> 你这是“修改节点”，而不是“添加节点”？ 这个按说应该把`if`的条件改一下，不过能用就行。感谢你的回复，我有时间看看这里如何优化一下。

是新增节点，新增的方法里没有设置direction的参数位置。执行add方法之后，设置direction属性之后，为了生效就又调用了一次update方法

**Comment by hizzgdev** [comment]
我细看了一下，你这截图里的方法是 `update_node: function (nodeid, topic)`, 这个方法只是用来修改 topic 的，如果需要调整方向，可以使用 `move_node: function (nodeid, beforeid, parentid, direction)` 这个方法。

另外，关于你说的 `新增的方法里没有设置direction的参数位置` 的问题，可以考虑给 `add_node` 方法添加一个 `direction` 的参数来解决，类似这样：

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1690290/215472866-61860c92-8a30-4c3d-b4a3-55a4c3f528ea.png">
