### ISSUE TITLE
双击节点输入topic显示之后，用get_data方法获取内容还是之前的默认topic

### ISSUE THREAD

**Issue by WangYingling** [hizzgdev/jsmind#416]
![image](https://user-images.githubusercontent.com/23132769/213635805-1d657ace-d2d2-4bcd-9140-26bb9536a06a.png)

事实上的导图内容节点已经被修改为下图，请问如何解决？
![image](https://user-images.githubusercontent.com/23132769/213635940-dfe6e30d-77c3-4889-98b2-1dd7e1fa079e.png)

**Comment by hizzgdev** [comment]
如果能稳定复现的话，这就是个bug，你能把你的代码贴出来吗？ @WangYingling 

我在[这里](https://hizzgdev.github.io/jsmind/example/2_features.html) 并没能重现你说的这个问题。

**Comment by WangYingling** [comment]
问题原因找到了。我在初始化节点的时候。节点的data里有一个名为topic的属性，在后来update的时候，更新了节点的topic，但是没有更新data.topic，在最后get_data的时候，node.data.topic覆盖了node.topic，导致获取的数据异常。要么修改get_data方法，要么更新update_node方法。我本地代码采用的后一种：
代码1393行下添加如下：
`                    if(!!node.data.topic){//避免获取数据时覆盖node.topic，使得获取的数据异常
                        node.data.topic=topic;
                    }`

**Comment by hizzgdev** [comment]
👍
