### ISSUE TITLE
子节点如果输入公式，会导致节点连线偏离

### ISSUE THREAD

**Issue by WangYingling** [hizzgdev/jsmind#418]
效果如下图：
![image](https://user-images.githubusercontent.com/23132769/215373364-6737994c-4396-4586-b921-87b0b31d7bbb.png)
节点的topic内容是：$ \sqrt[2]{4} $
我尝试过在根节点输入公式，根节点的连线效果不会偏离

**Comment by hizzgdev** [comment]
是的，这是个已知问题， https://github.com/hizzgdev/jsmind/pull/330

MathJax 是异步渲染公式的，当 jsMind 获取这个 node 的尺寸时获取得并不是它最终的大小。

我翻了一下它的文档并没有找到同步方式渲染公式的选项，所以目前还不很好地支持这个插件。我前段时间已经把 demo 的链接从 README 里删除了，如果你有时间可以研究一下。
