### ISSUE TITLE
能否使用自定义长宽和内容的节点？

### ISSUE THREAD

**Issue by hahadaba** [hizzgdev/jsmind#421]
hello!
如果想要每一个节点都能够自定义长宽和内容，有没有办法？

**Comment by hizzgdev** [comment]
可以的。参见文档
https://hizzgdev.github.io/jsmind/docs/zh/1.usage.html
1.4. 样式

**Comment by hahadaba** [comment]
谢谢回复！
我想将jsmind封装进我的vue或者svelte项目，对于每一个节点，使用自定义组件（插槽slot）的方式，请教一下实现的思路？

**Comment by hizzgdev** [comment]
抱歉，我对 vue 和 svelte 不太了解。
