### ISSUE TITLE
hello,请问一下子节点如何双击进入编辑状态

### ISSUE THREAD

**Issue by 284539527** [hizzgdev/jsmind#422]
请问一下子节点如何双击进入编辑状态，我发现root节点可以进入编辑状态，但是双击子节点时只能拿到jmnodes元素对象，无法拿到jmnode对象

**Comment by 284539527** [comment]
我发现用鼠标完全没问题，用笔记本触摸版双击时，第二下得慢一些才有效

**Comment by hizzgdev** [comment]
😂，如果不方便，可以使用快捷键，也可以参考文档修改快捷键。

**Comment by 284539527** [comment]
快捷键也有在使用，但总归会习惯性双击，哈哈，感谢大佬
