### ISSUE TITLE
如果自定义新增的节点

### ISSUE THREAD

**Issue by lyh0371** [hizzgdev/jsmind#424]
比如 我想每一次新增出来的节点都是这样子
<img width="442" alt="image" src="https://user-images.githubusercontent.com/30796346/225807857-4a1ceedc-f854-4061-b3e0-12a695df2279.png">
请问，要如何配置

**Comment by hizzgdev** [comment]
你是说每个节点都是两个输入框吗？能不能细化一下你的需求，而且考虑一下新增时，和新增后两个阶段的显示样式？

从这个图片上我能猜测出来的需求大概是这样：
1. 节点之间的连接线改成直角，并在末端添加箭头
2. 节点上可以显示输入框
3. 输入框输入的内容可以保存起来
4. 保存后的内容需要以不带输入框的方式呈现出来

上面这些需求中的2可以直接支持，jsmind的node可以接受html，但是其他的几点都不是jsmind直接能提供的，需要你自行扩展。

另外对于jsmind来说没有“新增的节点”这个概念，不过节点是有编辑状态的。我觉得你可能需要从这个角度来考虑如何支持你的需求。

这是jsmind的文档，你可以阅读一下看看能支持到什么程度。https://hizzgdev.github.io/jsmind/docs/ 。如果有具体的想法或者需求咱们可以继续探讨。

**Comment by hizzgdev** [comment]
所以你可能需要对jsmind作出修改来支持你的需求。思路是当节点处于编辑模式时，输入框要怎么设置。

**Comment by lyh0371** [comment]
现在遇到一个问题，我的思路是在节点新增后立马修改节点 但是报这个错误 
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/30796346/225860928-1f090416-2ff7-4f73-958b-996f1bb9e047.png">
代码如下
  jm.add_event_listener((...res)=>{
                    const [index,{evt}] = res
                    console.log(evt);
                    if(evt === 'add_node'){
                        console.log(res[1].node);
                        jm.update_node(res[1].node, `111`)
                        if(res[1].data[1]){
                        //    setTimeout(() => {
                        //     jm.update_node(es[1].node, `111`)
                        //    }, 1000);
                        }
                        return false
                    }
                  
                })

**Comment by hizzgdev** [comment]
update_node方法里的node并不是html里的dom element。这里你看看是不是需要修改一下？
