### ISSUE TITLE
add_node direction方向不好使

### ISSUE THREAD

**Issue by wu6666gong** [hizzgdev/jsmind#426]
npm安装版本：^0.5.3
你好，我在根节点使用添加节点：jm.add_node 设置direction为left，不生效。
代码： jm.add_node(jm.get_selected_node(), id, topic, {}, 'left')
期望：在根节点添加节点，设置left 会添加在左面，而不是添加在右面

**Comment by hizzgdev** [comment]
你把 `'left'` 换成 `jsMind.direction.left` 这个常量就好了。

过两天我会更新一下，让它也支持字符串参数。

**Comment by hizzgdev** [comment]
@wu6666gong  0.5.4 版本已发布，支持你的这种写法了。

**Comment by wu6666gong** [comment]
感谢感谢
