### ISSUE TITLE
建议增加线条颜色自定义API

### ISSUE THREAD

**Issue by zhangqianfeng** [hizzgdev/jsmind#428]
建议增加线条颜色自定义API，目前全局灰色线条不能自定义成和系统主题保持一致，显示很突兀

**Comment by hizzgdev** [comment]
这个功能是支持的。
之前的 issue： https://github.com/hizzgdev/jsmind/issues/394
对应PR： https://github.com/hizzgdev/jsmind/pull/399
对应文档： https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md#14-%E6%A0%B7%E5%BC%8F  
关键词： `leading-line-color`

**Comment by hizzgdev** [comment]
哦，提醒一下，这个功能只在 es6 的版本上支持，所以你可能需要修改一下引用的路径，把 URL 中的 js 换成 es6，如

js版： https://cdn.jsdelivr.net/npm/jsmind/js/jsmind.js
es版：https://cdn.jsdelivr.net/npm/jsmind/es6/jsmind.js

具体文件名参考: https://www.npmjs.com/package/jsmind?activeTab=code

**Comment by hizzgdev** [comment]
对了，如果你是希望把所有线条的颜色全部换成同一种颜色，也可以直接设置一下`view.line_color`这个选项，可能会更简单一些。 https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md#23-%E6%8E%92%E7%89%88%E9%80%89%E9%A1%B9
