### ISSUE TITLE
Please add a note in the docs about how to export a mind map

### ISSUE THREAD

**Issue by lborgman** [hizzgdev/jsmind#429]
I am reading the docs and trying to find out how to export a mindmap. I can't find it.

**Comment by hizzgdev** [comment]
do you means `get_data`?  https://github.com/hizzgdev/jsmind/blob/master/docs/en/3.operation.md#36-access-to-data

if what you want is exporting a mind map to a file, I think it's out of the scope of jsmind.

**Comment by lborgman** [comment]
Thanks @hizzgdev ! Now I only need info about the value of the parameter `data_format`. I do not understand what "in the specified format of the current mindmap" means. (Should it perhaps be "for the current"?)

**Comment by hizzgdev** [comment]
Three formats are supported by jsMind: `node-tree`, `node-array`, `freemind`. jsMind can load either format below, also can export data for any format of them. @lborgman 

The format is introduced here https://github.com/hizzgdev/jsmind/blob/master/docs/en/1.usage.md#12-data-format . PTAL

**Comment by lborgman** [comment]
@hizzgdev 
Thanks, I see. So `data_format` should be a string with a value of "node_tree", "node_array" or "freemind"?

**Comment by hizzgdev** [comment]
> So `data_format` should be a string with a value of "node_tree", "node_array" or "freemind"?

Yes
