### ISSUE TITLE
Option view.engine = "svg" but canvas still created

### ISSUE THREAD

**Issue by lborgman** [hizzgdev/jsmind#432]
I am using the "svg" option (for connection line drawing). I works very well as far as I have seen. 

However a canvas DOM element is still added by jsmind. If I remove the canvas everything still seems to work.

**Comment by hizzgdev** [comment]
do you enable `jsmind.draggable-node.js` plugin?
If true, the `<canvas>` you see is created for supporting `draggable-node`.

**Comment by lborgman** [comment]
@hizzgdev 
Yes, I add that. However dragging seems to work even if I remove the canvas. Maybe the canvas is still around, but not attached to the DOM? Does it need to be attached to the DOM? 

I am using latest version of Google Chrome, today this Version 111.0.5563.147 (Official Build) (64-bit) on MS Windows. I am struggling a bit to get both a context menu and dragging to work on Android. So I am a bit confused about Android at the moment. 😐

**Comment by hizzgdev** [comment]
> However dragging seems to work even if I remove the canvas.

The canvas is used for the connection line:
<img width="533" alt="screenshot" src="https://user-images.githubusercontent.com/1690290/230304604-72f437b0-1eed-4cd2-8903-42006e1d4107.png">

> I am struggling a bit to get both a context menu and dragging to work on Android.

Yes, I think it's a challenge to handle the dragging feature on a touch screen devices.  :smirk:

**Comment by lborgman** [comment]
Why not just use just a (rotated) html div?

**Comment by hizzgdev** [comment]
> Why not use just a (fixed position, rotated) html div?

It maybe an alternative, I prefer `Canvas` because:
1. easier, since only two coordinates are needed
2. faster, no DOM change
3. more scalable, it would be easier to change the color, sharp, style of the line.

**Comment by lborgman** [comment]
Another alternative is to use an outline on the possible target. Even easier and faster.

**Comment by hizzgdev** [comment]
> Another alternative is to use an outline on the possible target. Even easier and faster.

Sorry, I'm not quite sure what you mean by `outline` and `the possible target` in the case. Would you please explain more?

**Comment by lborgman** [comment]
I just meant a CSS outline on the target node.
