### ISSUE TITLE
How to add custom rendering to a node?

### ISSUE THREAD

**Issue by qrdlgit** [hizzgdev/jsmind#436]
I'd like to add a very small change to rendering of nodes (prefix the innerHTML) if there is certain auxiliary data added to the node.  I couldn't see a straightforward way to do this, given the change I want to do is quite minor.  eg, just add an awesomefont icon.

**Comment by hizzgdev** [comment]
you could create a new theme for your case, or customize the style for those nodes.
https://github.com/hizzgdev/jsmind/blob/master/docs/en/1.usage.md

**Comment by qrdlgit** [comment]
Hmm, I looked at that, but there is no 'set_node_theme' or 'set_node_style' functions, so that didn't quite make sense.  I can see a more extensive change that could be done to make this happen, but was wondering if there was already support for this.

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/en/3.operation.md#35-setting-style

PTAL
