### ISSUE TITLE
edit nodes need their own theme

### ISSUE THREAD

**Issue by qrdlgit** [hizzgdev/jsmind#438]
![image](https://user-images.githubusercontent.com/129564070/231495228-3277db82-6d43-4d17-aaba-64cef8bb0ed4.png)

I'd like to fix that.  The edit box should grow or be of a fixed size as you type things in.  Any suggestions on how you'd like it fixed before I start the PR?

**Comment by hizzgdev** [comment]
Thanks @qrdlgit , I prefer to give a `min-width` style to `node` element in the theme.

But never mind, you can choose any other way to resolve it for your project .

**Comment by qrdlgit** [comment]
I see.  As that changes the mid-width of every node and not just the one being edited, I will need to use a different method.  I appreciate the response, however.

**Comment by qrdlgit** [comment]
I'd like to re-open this issue.   I constantly run into this problem.  Can we get a separate theme for nodes in edit state?   min width would make sense for that.

**Comment by hizzgdev** [comment]
> I'd like to re-open this issue. I constantly run into this problem. Can we get a separate theme for nodes in edit state? min width would make sense for that.

Yes, we can. Would you like to submit a PR for that?

**Comment by qrdlgit** [comment]
Sure, what do you think of:


```
edit_node_begin(node) {
..
var element = view_data.element;
element.classList.add("editing")
```

And then remove it in edit_node_end

You didn't use classlist for selected, so maybe you have other ideas.

**Comment by hizzgdev** [comment]
The solution is OK.

> You didn't use classlist for selected, so maybe you have other ideas.

it's just because `classlist` was not compatible with all browsers when the feature was developed. So you can use it now.
