### ISSUE TITLE
缩放的时候不符合预期

### ISSUE THREAD

**Issue by scrod7** [hizzgdev/jsmind#440]
缩放时不是以鼠标所在的中心点进行缩放的, 脑图大一点之后缩放完全找不到之前的位置

**Comment by scrod7** [comment]
> 我记得之前有这么一个问题，但在后续的版本中修复了。你能确认一下你用的是哪个版本吗？

您好~ 我自己已经拉下来代码做了一些定制化的修改了; 不过如果是这个修复: fix zoom position #410 的话, 我已经带上了;
另外我尝试了一下在这个demo中: https://hizzgdev.github.io/jsmind/example/2_features.html 节点多的时候也有同样的问题, 这个demo是最新版本吗?

**Comment by hizzgdev** [comment]
https://hizzgdev.github.io/jsmind/example/2_features.html 这个是最新版本。

@scrod7  能分享一下你的解决方案吗？jsmind 的缩放好像确实没有以鼠标所在的位置做为中心点。

**Comment by scrod7** [comment]
我看了一下源码, zoom之后会_center_root而不是以捏合中心或鼠标位置定位的;
我尝试了一下解决, 原理是zoom前记下之前的鼠标位置在整个画布的比例, 在zoom后定位到相同比例的位置; 但是还是不对,
我想可能是因为这一段代码: 会造成zoom的时候只有节点的尺寸变了, 并不是整个画布直接缩放的; 会不会直接整个画布缩放可以解决这个问题呢?
for (var i = 0; i < this.e_panel.children.length; i++) {
                this.e_panel.children[i].style.zoom = zoom;
            };

**Comment by scrod7** [comment]
trick一点的话, 可以记下离鼠标位置最近的那个节点, 缩放后定位到那个节点

**Comment by hizzgdev** [comment]
> 会不会直接整个画布缩放可以解决这个问题呢?

基于 jsMind 目前的实现方案，整个画布其实就是代码里的 `e_panel`( 对应 dom 里的 `jsmind-inner`) 是与 `container` 的大小一致的，是一个固定尺寸的容器。如果脑图比较大的话，滚动或平移是发生成 `jsmind-inner` 内部的，这样就完全不会被 `container` 上的任何样式或行为所影响。

基于这个思路来考虑的话，如果整个画布缩放的话，可能会受到 `container` 样式的影响，最直观的问题是可能会导致 jsMind 里出现两层滚动条，或者撑开 container 等情况。

如果想实现整个画布缩放的话，那就需要在 `jsmind-inner` 里面再加一层，对这一层做缩放，这样理论上可以实现，但是需要对 jsMind 做一下重构，需要小心测试才行。

**Comment by hizzgdev** [comment]
回到这个 issue 最初的问题上来，要实现完美的 zoom，可能首先要取消 `_center_root`。另外由于 jsMind 的 zoom 不是平滑的，倒可以根据鼠标坐标计算出 offset，然后 scroll 到合适的位置。如果你有兴趣可以尝试一下这个方案。

**Comment by scrod7** [comment]
> 回到这个 issue 最初的问题上来，要实现完美的 zoom，可能首先要取消 `_center_root`。另外由于 jsMind 的 zoom 不是平滑的，倒可以根据鼠标坐标计算出 offset，然后 scroll 到合适的位置。如果你有兴趣可以尝试一下这个方案。

这个方案我尝试了一下, 但是发现在y轴上总有偏差, 不知道是什么原因

**Comment by scrod7** [comment]
> > 会不会直接整个画布缩放可以解决这个问题呢?
> 
> 基于 jsMind 目前的实现方案，整个画布其实就是代码里的 `e_panel`( 对应 dom 里的 `jsmind-inner`) 是与 `container` 的大小一致的，是一个固定尺寸的容器。如果脑图比较大的话，滚动或平移是发生成 `jsmind-inner` 内部的，这样就完全不会被 `container` 上的任何样式或行为所影响。
> 
> 基于这个思路来考虑的话，如果整个画布缩放的话，可能会受到 `container` 样式的影响，最直观的问题是可能会导致 jsMind 里出现两层滚动条，或者撑开 container 等情况。
> 
> 如果想实现整个画布缩放的话，那就需要在 `jsmind-inner` 里面再加一层，对这一层做缩放，这样理论上可以实现，但是需要对 jsMind 做一下重构，需要小心测试才行。

好的~ 谢谢!

**Comment by hizzgdev** [comment]
> > 回到这个 issue 最初的问题上来，要实现完美的 zoom，可能首先要取消 `_center_root`。另外由于 jsMind 的 zoom 不是平滑的，倒可以根据鼠标坐标计算出 offset，然后 scroll 到合适的位置。如果你有兴趣可以尝试一下这个方案。
> 
> 这个方案我尝试了一下, 但是发现在y轴上总有偏差, 不知道是什么原因

有空我也详细看看这个情况。

**Comment by scrod7** [comment]
> > > 回到这个 issue 最初的问题上来，要实现完美的 zoom，可能首先要取消 `_center_root`。另外由于 jsMind 的 zoom 不是平滑的，倒可以根据鼠标坐标计算出 offset，然后 scroll 到合适的位置。如果你有兴趣可以尝试一下这个方案。
> > 
> > 
> > 这个方案我尝试了一下, 但是发现在y轴上总有偏差, 不知道是什么原因
> 
> 有空我也详细看看这个情况。

谢谢!

**Comment by chinayzq** [comment]
> trick



> 的话，那就需要在 `jsmind-inner` 里面再加一层，对这一层做缩放，这样理论上可以实现，但是需要对 jsMind 做一下重构，需要小心测试才行。

@scrod7 请问你的问题解决了吗，能分享下不

**Comment by hizzgdev** [comment]
这个问题已经解决 https://github.com/hizzgdev/jsmind/pull/467, 并包含在 v0.6.1 版本中。@scrod7 @chinayzq 
此功能改进仅在 ES6 version 中支持，欢迎试用。如果你使用的是老版本，请别忘了修改文件路径：

- https://cdn.jsdelivr.net/npm/jsmind@0.6.1/es6/jsmind.js
- https://jsd.onmicrosoft.cn/npm/jsmind@0.6.1/es6/jsmind.js (国内镜像)

**Comment by chinayzq** [comment]
感谢大佬！~
