### ISSUE TITLE
More space between cousins?

### ISSUE THREAD

**Issue by qrdlgit** [hizzgdev/jsmind#441]
One issue I'm seeing is that the spacing between siblings is the same as between cousins, which makes it a bit more visually difficult to separate them.

![image](https://user-images.githubusercontent.com/129564070/231930484-da81a297-35f9-484d-8676-99522dcdfae5.png)

**Comment by hizzgdev** [comment]
Well, it doesn't look good. Will have a look on it, thanks.

**Comment by qrdlgit** [comment]
Here's another example

![image](https://user-images.githubusercontent.com/129564070/231938140-19346715-260d-4e0b-b95c-a89576eceb71.png)

I'm guessing there is no easy fix via the options/style overrides.

**Comment by qrdlgit** [comment]
![image](https://user-images.githubusercontent.com/129564070/231942229-13079214-59a1-43ba-a4c6-ea341701fb7f.png)


I added some spacing to the last line of 
_jm.layout._layout_offset_subnodes_height  
_jm.layout._layout_offset_subnodes
..
return total_height+10

Seems to work.  I noticed that the expand bubble is a bit off kilter as I've reduced the padding for jmnode via style override, not sure if you want to support that or not.

**Comment by hizzgdev** [comment]
>  the expand bubble is a bit off kilter as I've reduced the padding for jmnode via style override

There may be a bug here, I will take a look too.

**Comment by hizzgdev** [comment]
A new option `layout.cousin_space` is added by PR https://github.com/hizzgdev/jsmind/pull/442 , and the change is included in version 0.5.5. So you can add space to the cousin node in your project now.

for the expand bubble, I can not reproduce it, can you share the overrode style?

**Comment by qrdlgit** [comment]
body jmnode {
      padding: 5px;
  }

Another issue I ran into was changing the color of the draggable node line.  I had to fork the entire plugin, couldn't monkey patch it.  :(

**Comment by hizzgdev** [comment]
```css
body jmnode {
padding: 5px;
}
```

It's fine on my laptop

<img width="448" alt="image" src="https://user-images.githubusercontent.com/1690290/232123400-b563293b-e7dc-42d0-a960-e739ae02d984.png">

**Comment by hizzgdev** [comment]
> Another issue I ran into was changing the color of the draggable node line. I had to fork the entire plugin, couldn't monkey patch it. :(

Sorry, I'm afraid you have to, I didn't expect anyone to want to modify this color. lol.

But I will consider providing configurable options for plugins as well, in the future. Thanks.

**Comment by qrdlgit** [comment]
The problem was I changed the background to dark, so the line vanished.  :p

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/pull/472/files#diff-b1d4f143f137f22c06f47fec0a17e85fecdcd9ace4b6c7314435b81467a45a43R32
https://github.com/hizzgdev/jsmind/pull/474
