### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by qrdlgit** [hizzgdev/jsmind#444]
A gap in jsmind is multi select.   

Question:   Is this a plugin?   IF so, it'd be nice to see some decoupling between plugins and the repository for forward compatibility.  How can we enable this plugin using only public apis in jsmind?

Different levels of support for this:

- ctrl-click to select nodes and add to the list of selected nodes
- shift ctrl click to select many nodes
- ctrl mouse select nodes

**Comment by hizzgdev** [comment]
1. `multi select` won't be a plugin, it should be a mechanism to allow the selection of multiple nodes, which is not supported yet.
    - `jm.select_node(node)` existing api, will clear the selection before select the new node.
    - `jm.select_node(list of node)` proposed new api
    - `jm.add_selected_node(node)` proposed new api
    - `jm.clear_selected_node()` proposed api name
2. `how to select node(s)` can be a plugin, but we don't have to, since it's light weight - just a key event mapping

**Comment by qrdlgit** [comment]
Perhaps ctrl-mouse drag select box will be a plugin.
