### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by qrdlgit** [hizzgdev/jsmind#445]
Another gap in jsmind is copy/paste.   Should this also be a plugin?

I listed this separately, but this could be merged with multi select if the owner would prefer that.  The two features are highly coupled, imho.

Multi select issue here - https://github.com/hizzgdev/jsmind/issues/444

**Comment by hizzgdev** [comment]
`Copy/Paste` is out of the scope of `jsMind`, but it could be a plugin.

I have another perspective on this topic: `Copy` or `Paste` are not important, the important things are:
- export nodes
- import nodes to a existing node

`Export/Import` can be a feature of jsMind, and they should be the built-in features not plugin.

Thanks for the great ideas @qrdlgit

**Comment by hizzgdev** [comment]
I don't think it's the one-line feature, since we have to introduce a new object, something like a mind-fragment.
