### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by qrdlgit** [hizzgdev/jsmind#446]
I've hacked together a undo/redo manager, but it's not ideal.  I basically just push the entire get_data onto a undo/redo stacks.   That said, it might be workable until something better comes along, like a command based one.

Would like to hear some comments about how this might be done.  Again, is this a plugin?  If so, again, I'd like to start trying to decouple the plugins from the repo in terms of only using documented apis.

decoupling like this has two key benefits:  Better api support, and forward compatibility.

One idea might be to classify plugins as either being decoupled or coupled.   Coupled plugins are allowed, but they need to be labeled as such.

An undo/redo manager of the type above could be a start to the decoupled plugins as it probably requires limited api additions.

Some missing gaps in my version:

- unclear undo/redo semantics (always tricky)
- not filtering out the right events for pushing onto stack, eg, undo node select probably isn't necessary
- poor scrollto behavior after undo/redo is done
- not saving undo/redo stacks (not sure this is required)

You can play around with my version here - https://github.com/qrdlgit/simbiotico

You don't need an api key, just type in anything.

**Comment by hizzgdev** [comment]
Yes, the solution should be events. push all the mutation event to a stack (do not push the entire data), pop event and revert for `undo`.
I have tried a `shell` feature `features/jsmind.shell.js`, I stored the event data and replay them. It may bring you some idea. PTAL.

**Comment by hizzgdev** [comment]
Some ideas about `documented apis` and `undocumented apis`:

I prefer to categorize the users of `jsMind` into two categories: `User` and `Developer`.

`User` use the documented apis to ensure compatibility.
`Developer` can use the internal api/data to achieve complex features. 

You will be a `Developer` when you want to build a plugin, please align with me if you want share the plugin in the `jsMind` repo.

`Developer` can also build plugins without any internal api/data, which is cool and encouraging.
All public API requirements are also welcome.
