### ISSUE TITLE
somehow style root

### ISSUE THREAD

**Issue by opto** [hizzgdev/jsmind#451]
I just noticed that when the map is like

![image](https://user-images.githubusercontent.com/204256/233724709-d3f530c6-1920-49f3-b13f-2a7da7485fe9.png)

then it cannot be seen what is root: T4 M1 or node gelber Raum

maybe give it another shade?

**Comment by opto** [comment]
a colored shadow works but maybe looks a bit ugly:

![image](https://user-images.githubusercontent.com/204256/233726027-aed5789c-d813-42b9-b431-c7fc0cee2619.png)

I just saw that you increased the font size for root, which maybe a better idea

**Comment by opto** [comment]
maybe bold at same font size for all nodes looks best:

selected and root

![image](https://user-images.githubusercontent.com/204256/233730931-24ca4ebb-e258-42f7-9101-2f4df6d3d8ea.png)

**Comment by hizzgdev** [comment]
As you probably know how to customize the theme, I would suggest solving the case by a custom theme. Bigger fontSize, different colors, border, shadows are all available options.

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/en/1.usage.md#13-themes

**Comment by opto** [comment]
yes, thanks, I wrote the original post before closer looking at how you indicated root by changing font size.
thanks for the good software library!
