### ISSUE TITLE
howto set mindmap to minimum height or a selected height?

### ISSUE THREAD

**Issue by opto** [hizzgdev/jsmind#452]
how do I set the jsmind_container height?
if there is no mindmap yet, I can do a _jm.show() and then set the height of the container by style.height. This height is set to 600px to allow adding nodes.

After editing, I might need only 200px to display the full map. Howto reduce the height?
I tried      _jm.resize(); but it did not change from the 600px set in editing.
;

How can I set any arbitrary height after a height has been set, meaning how to rerender the map in the new height of the div?
And another question: if I have less or more height than needed,  how can I center root in the visible part?

Many thanks for your help.

**Comment by hizzgdev** [comment]
### how do I set the jsmind_container height?

1. The size of the container is out of scope of jsMind,  jsMind won't change any style of the container, you would manage the size by your applicatoin.
2. If you change the size of the container, please call `jm.resize()` to adjust the new container size.

for your case, I think you have to reduce the height by your app, and then `resize()`.


### if I have less or more height than needed, how can I center root in the visible part?

There is an internal method to move the root node to the center: `jm.view._center_root()`, you can just use it in your project, or search it from the code to learn how it is used, and refactor the code for your project.
