### ISSUE TITLE
example html from github do not work in browsers

### ISSUE THREAD

**Issue by opto** [hizzgdev/jsmind#453]
Brave, Chrome, Firefox: open example button does not open the mindmap.
(e.g. in file:///G:/G/Arbeit/JS/mindmap/jsmind/example/2_features.html)

I got it running in the previous version (0.5.5) by replacing  inline scripts by putting them into a js file, and by replacing the CDN (not sure whether that is needed) by local copies of the js files.

**Comment by hizzgdev** [comment]
### open example button does not open the mindmap
let me confirm that you run the example html in local mode? which means the url in the browser is `file:///G:/....`
If it's true, I would suggest that you start a web server to run the example html file, the url should be `http://localhost....`. 

The demo pages are all built for remote mode, the `src` in `<script>`, the `href` in `<link>` are all related to the `root directory` of a web application. So it's expected that the resources can not be loaded, and the features will be broken.

### why does it use CDN
- CDN is the recommended way to reference jsMind, so it is used in all demo pages;
- Some generated files exist in CDN, but are not included in the repo (e.g. `es6/jsmind.js`);

### how can i do if i want preview the demo pages in local mode
Yes, It's fine to replacing all the resources to relative url, and generate the target file if you are working on ES6 version.

**Comment by opto** [comment]
this
href="//unpkg.com/jsmind/style/jsmind.css"
and this
src="//unpkg.com/jsmind/js/jsmind.js"
etc. currently cause net errors
```
jsmind.js:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by opto** [comment]
this, same for css, works locally:

```
        <script type="text/javascript" src="../js/jsmind.screenshot.js"></script>
        <script type="text/javascript"  src="./2_features.js">

```

plus putting the inline js into a js script file.

if you want, I can make a pull request for a 2_feature_in_browser.html

**Comment by opto** [comment]
and resizing does work, I can confirm.

Now, the interesting question is why it does not work in my app, I am using the same way to set height.
I noticed that the div height is reduced, but the canvas height is not.

What I may do differently is that I first set to 600px for editing, and later after editing to 200px, which then is not adjusted (div height goes to 200px, canvas stays at 580 px - some value near 600). The visual height of div is not changed, although html inspector shows height = 200px

**Comment by hizzgdev** [comment]
```
jsmind.js:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
```

It works on my laptop in Beijing, it's very likely blocked by some network service. Sorry for that, I will update the url soon.

**Comment by hizzgdev** [comment]
```
make a pull request for a 2_feature_in_browser.html
```

Thanks for your kindly help. but i'm afraid it is not necessary: the ES6 version will take the place soon, considering the network issue on CDN, I need to find a better way to provide the demo pages.

**Comment by hizzgdev** [comment]
Add 2 demo pages using China CDN in https://github.com/hizzgdev/jsmind/pull/459 to avoid `net::ERR_FILE_NOT_FOUND`.
- https://hizzgdev.github.io/jsmind/example/1_basic_cn.html
- https://hizzgdev.github.io/jsmind/example/2_features_cn.html
