### ISSUE TITLE
为何一个节点显示不完全

### ISSUE THREAD

**Issue by EvenyYlzz** [hizzgdev/jsmind#454]

**Comment by EvenyYlzz** [comment]
就是文本很长的时候，自动就显示...了，这个除了该里面的css，还有办法去修改吗

**Comment by hizzgdev** [comment]
有一个参数你可以用来设置显示全部文本：`node_overflow`，具体说明在这里 https://github.com/hizzgdev/jsmind/blob/master/docs/zh/2.options.md
