### ISSUE TITLE
怎么监听双击修改topic

### ISSUE THREAD

**Issue by chinayzq** [hizzgdev/jsmind#462]
hi，大佬你好，我在用jsmind开发一个类似思维导图的功能，然后现在需要做一个撤销的功能，但是我没办法监听到双击节点后修改的动作，请问这个需要怎么实现呢

**Comment by hizzgdev** [comment]
试试这样：

```javascript 
//定义一个方法
function callback(type ,data){
    // 看看修改时控制台里有什么数据，选择合适的type完成你的需求。
    console.log(arguments);
}

// 注册到 jsMind 里
jm.add_event_listener(callback);

```

**Comment by chinayzq** [comment]
<img width="567" alt="767129b6988db0c5179ba973e1bcaa1" src="https://github.com/hizzgdev/jsmind/assets/16029800/9fddecc9-26a2-468a-824d-a6af92210930">
请问怎么设置或者处理，能让红框中的节点和他的同级挨着呢

**Comment by hizzgdev** [comment]
这是个已知问题，之前有讨论过，你看看https://github.com/hizzgdev/jsmind/issues/440

> 拖动到最右边某个节点以后进行缩放，会回到画布的最左边，请问这个有没有办法做到根据鼠标中心点来缩放？

**Comment by hizzgdev** [comment]
> 拖动到最右边某个节点以后进行缩放，会回到画布的最左边，请问这个有没有办法做到根据鼠标中心点来缩放？

这个问题已经解决 https://github.com/hizzgdev/jsmind/pull/467, 并包含在 v0.6.1 版本中。
此功能改进仅在 ES6 version 中支持，欢迎试用。如果你使用的是老版本，请别忘了修改文件路径：

- https://cdn.jsdelivr.net/npm/jsmind@0.6.1/es6/jsmind.js
- https://jsd.onmicrosoft.cn/npm/jsmind@0.6.1/es6/jsmind.js (国内镜像)
