### ISSUE TITLE
jsmind，太棒了，能参考这里，增加相关功能就完美了

### ISSUE THREAD

**Issue by hktalent** [hizzgdev/jsmind#466]
@hizzgdev jsmind，太棒了
能参考这里，增加相关功能就完美了

- 看了文档，不知道有多少主题可供选择啊
- 能参考（扣出来），https://www.yuque.com/dashboard 给出更多的功能和风格吗？非常感谢
<img width="1158" alt="image" src="https://github.com/hizzgdev/jsmind/assets/18223385/9d6e01a8-e657-4acf-a284-003caebceab3">
<img width="849" alt="image" src="https://github.com/hizzgdev/jsmind/assets/18223385/da1d1851-d638-4005-9962-32f558e705e6">
<img width="1076" alt="image" src="https://github.com/hizzgdev/jsmind/assets/18223385/797af230-b9a8-4a99-8e40-3303bfe45b69">
<img width="1156" alt="image" src="https://github.com/hizzgdev/jsmind/assets/18223385/7e84bb30-eeb4-4457-8335-8e0c185c9e11">
<img width="761" alt="image" src="https://github.com/hizzgdev/jsmind/assets/18223385/94be6a22-543c-45fc-85fe-b8c113e733a9">
<img width="800" alt="image" src="https://github.com/hizzgdev/jsmind/assets/18223385/587d1358-1f38-41e4-a52a-45e6eb0a696d">

万分感谢

**Comment by hktalent** [comment]
另外建议
jm.add_node(parent_node, node_id, topic, data, direction)
等 api参数可以合并为一个: obj||function
的，这样灵活性更高
而function给使用者带来更多灵活性，当然function需要将当前jm压入this

**Comment by hizzgdev** [comment]
感谢 @hktalent 分享的这些漂亮的主题以及关于 API 的建议。首先承认 jsMind 功能还比较简单，距离完善都还差得远，更不用提“完美”这个词了。但实话实说，完善的功能背后是大量的工作量。兴趣和热爱固然可贵，但是合作、分享与贡献更有实际的价值。我想这也是开源的意义。

### 关于更多主题的回答
相信您查阅文档应该能看到，jsMind 默认提供了一些主题，而且文档中也介绍了如何自定义主题，不过 jsMind 对主题的支持还仅仅停留在基础的样式上，高级复杂的样式（比如随机线条颜色）还需要 jsMind 的功能迭代才能支持。

### 关于 add_node 方法参数的回答

#### 为什么不使用 object 来代替那一堆参数
设计 `jsMind` API 时考虑过使用一个 `object` 来代替具体参数的方案，但后来没有采用。原因是使用 `object` 当参数太灵活了，灵活到必须写一个文档才能说明白 `object` 里应该包含哪些信息；而且当有参数/字段变更时，仅从 api 上也看不出来变化在哪里。作为一个公开的 API，如果能从参数列表中得到信息，将会好过于再去查阅文档。 **如果可能的话，我更希望开发者们不必读文档就能轻松快速的使用它**

#### 为什么不使用 function 作为参数
说实话我没有很理解把 `function` 作为参数的具体使用方法，但不知道上面那个问题的回答是否也可以回答你这个问题。如果不行的话请可以继续回复，我们可以进一步探讨。

#### 为何不给 selected_node 默认值
如果你是某个项目的开发者，在你的项目里给 `selected_node` 默认值设置为根节点，应该不是一个太难的事情。但是作为一个基础 library，抛出一个异常比给一个默认值更友好，想一想你是怎么发现这个问题的，然后在调用这个方法的时候是不是还要考虑一下它的默认值是什么。

再次感谢你的这些好问题，也希望我的回复能够解开你的部分疑惑，如果需要欢迎继续回复。也希望你能继续支持 jsMind.

**Comment by hktalent** [comment]
关于 function 作为参数的好处，可以参考D3的设计
