### ISSUE TITLE
引用了 jsmind.draggable-node.js之后，双击节点（跟节点除外）不能进入编辑模式

### ISSUE THREAD

**Issue by mapengfei** [hizzgdev/jsmind#471]
![Image_20230529183754](https://github.com/hizzgdev/jsmind/assets/17701379/e4840a6b-783f-4b8a-b2a8-c5c591368ac0)
官网的demo也是一样，只有根节点双击可以进入编辑模式

**Comment by mapengfei** [comment]
去掉jsmind.draggable-node.js引用，双击可以正常进入编辑模式

**Comment by hizzgdev** [comment]
我这里并不能复现你说的问题，下面这三个 demo 我都试过。你看一下控制台，看是不是某个 js 文件没能正常加载或者是不是有报错。

https://jsmind.online/
https://hizzgdev.github.io/jsmind/example/1_basic.html
https://hizzgdev.github.io/jsmind/example/2_features.html

**Comment by mapengfei** [comment]
上面三个demo，我这里只有根节点，双击可以进入编辑模式，其他节点双击均不能进入编辑模式。F2所有节点都可以进入编辑模式。控制台没有报错，双击没有任何log输出。我本地验证的时候，去掉jsmind.draggable-node.js引用，所有节点双击就可以进入编辑模式了。（"jsmind": "^0.6.2", 本地使用的是0.6.2版本）

**Comment by hizzgdev** [comment]
说一下你测试用的浏览器及操作系统吧。我也找找相同的版本试试。

**Comment by mapengfei** [comment]
操作系统：Windows 10 企业版 LTSC
浏览器：Google Chrome （版本 112.0.5615.138（正式版本） （64 位）

**Comment by hizzgdev** [comment]
感谢

**Comment by mapengfei** [comment]
对不起，是我浏览器的问题，我重启了浏览器，一切都OK了。非常感谢的您的耐心解答。

**Comment by leeyoshinari** [comment]
我也遇到了一模一样的问题，请问是什么原因呀，重启浏览器，无痕模式都不行

系统：
windows10家庭版 64位

浏览器：
chrome 117.0.5938.152  （64位）
edge：118.0.2088.46   （64位）

**Comment by hizzgdev** [comment]
> 我也遇到了一模一样的问题，请问是什么原因呀，重启浏览器，无痕模式都不行
> 
> 系统： windows10家庭版 64位
> 
> 浏览器： chrome 117.0.5938.152 （64位） edge：118.0.2088.46 （64位）

你是在demo页测试的吗？
https://hizzgdev.github.io/jsmind/example/2_features_cn.html

如果不是的话，可能需要你自己排查一下，看是不是dom的事件被其他脚本接管了。
@leeyoshinari

**Comment by leeyoshinari** [comment]
@hizzgdev demo页面也是一样的，双击子节点不能编辑。

**Comment by hizzgdev** [comment]
已确认该问题，并在 0.7.3 版本 中修复。感谢报告！ @leeyoshinari

**Comment by hizzgdev** [comment]
如果验证还有问题，可以 reopen 这个 issue ，我们继续研究。 再次感谢 @leeyoshinari .

**Comment by hizzgdev** [comment]
好像还没有完全解决

**Comment by leeyoshinari** [comment]
@hizzgdev 感谢，我晚上回去验证一下看看

**Comment by hizzgdev** [comment]
0.7.4 版本应该能解决这个问题，可以先试试看，不行的话再 reopen 这个 issue，或创建个新的 issue 都行。

**Comment by leeyoshinari** [comment]
@hizzgdev 感谢，可以编辑了。
遇到了另一个问题，麻烦看看
