### ISSUE TITLE
这是jsmind 容器没找到报的错吗？但是我明明打印的出来容器的dom

### ISSUE THREAD

**Issue by wucyAAA** [hizzgdev/jsmind#477]
vue.runtime.esm.js:1897 TypeError: Cannot use 'in' operator to search for 'view' in undefined
    at g.create_node_element (jsmind.view_provider.js:169:1)
    at g.init_nodes (jsmind.view_provider.js:155:1)
    at g.load (jsmind.view_provider.js:127:1)
    at z._show (jsmind.js:277:1)
    at z.show (jsmind.js:297:1)
    at VueComponent.xmindInit (ConceptStocks.vue:587:1)
    at VueComponent.eval (ConceptStocks.vue:323:1)
    at Array.eval (vue.runtime.esm.js:1989:1)
    at flushCallbacks (vue.runtime.esm.js:1915:1)

**Comment by hizzgdev** [comment]
麻烦你确认一下你用的是哪个版本？页面里引用了那些jsmind的scripts？

**Comment by wucyAAA** [comment]
在vue使用npm下载的jsmind，版本是0.6.3，拖拽和快照的脚步也都引用了

**Comment by wucyAAA** [comment]
jsmind正常用确实没问题，场景复杂点好像就有点不行了，最小复现现在没空给你，你需要的话空了再给你

**Comment by hizzgdev** [comment]
单独跟踪了下上面帖的 stack 没发现有什么问题。你这里是不是有多个脑图，或者是有大量的 node 增减变化之类的？

**Comment by wucyAAA** [comment]
在一个页面里有很多个子页卡，每个页卡有一个脑图，但是我new jsmind() 是单例的

**Comment by hizzgdev** [comment]
你这里是每切换子页卡时，脑图都要重新 show 一遍吗？ 是不是一个 `new jsMind()` 对应一个脑图更好一些？

**Comment by wucyAAA** [comment]
每一次切换都要重新new一下，但是始终只有一个jm，肯定要重新show一遍，new多个实例有点不必要的空间浪费吧。

**Comment by hizzgdev** [comment]
所以上面这个报错是发生在（频繁）切换子页卡的时候吗？

**Comment by wucyAAA** [comment]
是的

**Comment by hizzgdev** [comment]
Hi @wucyAAA , 你能帮我确认一下几个问题吗？就是在频繁切换子页卡的时候：
1. 只是调用了 `show()` 这个方法
2. 没有对 `jsmind_container` 这个容器做任何处理（包括尺寸调整，可见性调整）
3. 没有对 `jsmind_container` 这个容器的父级容器做任何处理（包括尺寸调整，可见性调整）

**Comment by wucyAAA** [comment]
是只调用了show()这个方法，可见性肯定都变了，但是dom都在，我每一个页卡的jsmind容器的id都不一样，我最后的解决方法是，切换页卡把上个页卡的dom都销毁了，就没报错了，作者你太敬业了，你能花点时间把编辑的ui交互改一下吗^v^

**Comment by hizzgdev** [comment]
```
每一个页卡的jsmind容器的id都不一样
```

这个可能是问题的根源吧，按说每 `new jsMind()` 一次，得到的 jsMind 对象跟 container 就绑定在一起了。比方说你有两个页卡，对应的 container_id 分别是 `container1`, `container2`

```html
<div id="container1"></div>
<div id="container2"></div>
```

```javascript
// 不同的 container 对应不同的 jm 对象:
// container1 -> jm1
// container2 -> jm2

let mind1 = {...}
let jm1 = new jsMind({container: 'container1'});
jm1.show(mind1)

let mind2 = {...}
let jm2 = new jsMind({container: 'container2'});
jm2.show(mind2)

// 切换页卡的时候只需要找到页卡对应的 jsMind 对象，调用它的 show 方法即可
// mind1, mind2 可能已经更新了
jm1.show(mind1)
jm2.show(mind2)

// mind1, mind2 可能又变化了，或者换成其它的脑图了
jm1.show(mind3)
jm2.show(mind4)

// 就这样的话按说不会有什么问题
jm1.show(mind5)
jm2.show(mind6)

```

总结来说，只 new 一次，持有这个对象后可以不断的 show。

**Comment by hizzgdev** [comment]
> 把编辑的ui交互改一下吗

这一句指的是什么？能具体说说吗?

**Comment by hizzgdev** [comment]
> 当文字很多时，双击编辑时的输入框并只会有一行

好的，后面有时间考虑处理一下这里。感谢反馈
