### ISSUE TITLE
drag & drop node in angular project

### ISSUE THREAD

**Issue by MShahzadulHassan** [hizzgdev/jsmind#478]
Hi, I am facing issue in dragging the node and taking screenshot of the mindmap while using jsmind library in angular project. I import the jsmind library but i cannot do drag and drop the node and unable to download the image of the mindmap. I try to import the script file in angular.json and also tried in index.html but it didnot help me. Can you please help me in this issue may be i am missing something. I follow all the docs you mention in on https://www.npmjs.com/package/jsmind?activeTab=code . Please help me in this issue so that i can drag and drop the node and download the image. Thanks @sudwebdesign @hizzgdev  @StefH @godiard

**Comment by hizzgdev** [comment]
Hi @MShahzadulHassan , I am not good at angular, so I can’t provide any best practice about how to use jsMind with angular. Sorry for that.

But there are several general steps that I think can help us to debug the issue:

- check the console of the browser 
- check the resources are loaded 
- make sure the files we used are the latest version 
- build a mini version to verify if it works 
- post your code here, so we can help you with that

**Comment by MShahzadulHassan** [comment]
Hi @hizzgdev , Okay. 
I checked all the things you mentioned above, all these are fine. I am attaching screenshots of the console and angular.json file in which i called the scripts file for drag & drop.
![angularjson](https://github.com/hizzgdev/jsmind/assets/112062622/f4b94a23-bc4a-4175-8534-fde642ff173f)
![console](https://github.com/hizzgdev/jsmind/assets/112062622/617a9cb4-75f6-4da1-a800-ff679279aa49)

**Comment by MShahzadulHassan** [comment]
when i add script in index.html then console give me this error.
![console](https://github.com/hizzgdev/jsmind/assets/112062622/0f897f6f-e0c8-49f6-97b5-dc3ba0b1d5c8)
![angularjson](https://github.com/hizzgdev/jsmind/assets/112062622/5913ed27-ec5c-4a4d-b92d-cdf00affdf3a)

**Comment by hizzgdev** [comment]
It seems that angular doesn't load scripts in sequence. Is there a way to let angular load `jsmind.js` before `jsmind.draggable-node.js` ?

**Comment by MShahzadulHassan** [comment]
Yes I load jsmind.js before jsmind.draggable-node.js but in console it give me no error. But the issue is still as it is, cannot drag and drop the node.
![index](https://github.com/hizzgdev/jsmind/assets/112062622/73abe75d-01e9-4188-a738-c810ef61233f)

**Comment by hizzgdev** [comment]
I'm guessing the problem has something to do with angular's behavior of loading js files, but I'm not really sure either. it's better to build a mini use case for verifying it.

**Comment by MShahzadulHassan** [comment]
HI, I created simple html project of this jsmind and add draggable-node.js file in script. Its working in this project but its not working in angular.

**Comment by MShahzadulHassan** [comment]
> <title>jsMind</title> <script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.js"></script>
> ```
>         <script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.draggable-node.js"></script>
>     <style type="text/css">
>         li {
>             margin-top: 2px;
>             margin-bottom: 2px;
>         }
>         button {
>             width: 140px;
>         }
>         select {
>             width: 140px;
>         }
>         #layout {
>             width: 1230px;
>         }
>         #jsmind_nav {
>             width: 210px;
>             height: 600px;
>             border: solid 1px #ccc;
>             overflow: auto;
>             float: left;
>         }
>         .file_input {
>             width: 100px;
>         }
>         button.sub {
>             width: 100px;
>         }
> 
>         #jsmind_container {
>             float: left;
>             width: 1000px;
>             height: 600px;
>             border: solid 1px #ccc;
>             background: #f4f4f4;
>         }
>     </style>
> </head>
> <body>
>     <div id="layout">
>         <div id="jsmind_nav">
>             <div>1. Open</div>
>             <ol type="A">
>                 <li><button onclick="open_json();">open example</button></li>
>                 <li><button onclick="open_ajax();">open remote</button></li>
>                 <li>
>                     <button onclick="prompt_info('see 6.Multi Format');">
>                         open local file
>                     </button>
>                 </li>
>                 <li>
>                     <button onclick="prompt_info('see 6.Multi Format');">
>                         save local file
>                     </button>
>                 </li>
>                 <li><button onclick="screen_shot();">screenshot</button></li>
>             </ol>
>             <div>2. Select &amp; Toggle</div>
>             <ol type="A">
>                 <li><button onclick="select_node();">select a node</button></li>
>                 <li>
>                     <button onclick="prompt_info('please try click a node');">
>                         try click a node
>                     </button>
>                 </li>
>                 <li><button onclick="show_selected();">get the selected</button></li>
>             </ol>
>             <div>3. Edit</div>
>             <ol type="A">
>                 <li><button onclick="toggle_editable(this);">disable editable</button></li>
>                 <li><button onclick="add_node();">add a node</button></li>
>                 <li><button onclick="add_image_node();">add a image node</button></li>
>                 <li><button onclick="modify_node();">modify node</button></li>
>                 <li>
>                     <button onclick="prompt_info('please try double click a node');">
>                         try double click
>                     </button>
>                 </li>
>                 <li><button onclick="move_node();">move a node</button></li>
>                 <li><button onclick="move_to_first();">move to first</button></li>
>                 <li><button onclick="move_to_last();">move to last</button></li>
>                 <li><button onclick="remove_node();">remove node</button></li>
>             </ol>
>             <div>4. Style</div>
>             <ol type="A">
>                 <li><button onclick="change_text_font();">change font</button></li>
>                 <li><button onclick="change_text_color();">change color</button></li>
>                 <li><button onclick="change_background_color();">change bg-color</button></li>
>                 <li><button onclick="change_background_image();">change background</button></li>
>             </ol>
>             <div>5. Theme</div>
>             <ol type="A">
>                 <li>
>                     <select onchange="set_theme(this.value);">
>                         <option value="">default</option>
>                         <option value="primary">primary</option>
>                         <option value="warning">warning</option>
>                         <option value="danger">danger</option>
>                         <option value="success">success</option>
>                         <option value="info">info</option>
>                         <option value="greensea" selected="selected">greensea</option>
>                         <option value="nephrite">nephrite</option>
>                         <option value="belizehole">belizehole</option>
>                         <option value="wisteria">wisteria</option>
>                         <option value="asphalt">asphalt</option>
>                         <option value="orange">orange</option>
>                         <option value="pumpkin">pumpkin</option>
>                         <option value="pomegranate">pomegranate</option>
>                         <option value="clouds">clouds</option>
>                         <option value="asbestos">asbestos</option>
>                     </select>
>                 </li>
>             </ol>
>             <div>6. Adjusting</div>
>             <ol type="A">
>                 <li>
>                     <button onclick="change_container();">resize container</button>
>                     <button onclick="resize_jsmind();">adusting</button>
>                 </li>
>                 <li>expand/collapse</li>
>                 <ol>
>                     <li><button class="sub" onclick="expand();">expand node</button></li>
>                     <li><button class="sub" onclick="collapse();">collapse node</button></li>
>                     <li><button class="sub" onclick="toggle();">toggle node</button></li>
>                     <li>
>                         <button class="sub" onclick="expand_to_level2();">
>                             expand to level 2
>                         </button>
>                     </li>
>                     <li>
>                         <button class="sub" onclick="expand_to_level3();">
>                             expand to level 3
>                         </button>
>                     </li>
>                     <li><button class="sub" onclick="expand_all();">expand all</button></li>
>                     <li><button class="sub" onclick="collapse_all();">collapse all</button></li>
>                 </ol>
>                 <li>zoom(ctrl+mousewheel)</li>
>                 <button id="zoom-in-button" style="width: 50px" onclick="zoomIn();">In</button>
>                 <button id="zoom-out-button" style="width: 50px" onclick="zoomOut();">
>                     Out
>                 </button>
>             </ol>
> 
>             <div>7. Multi Format</div>
>             <ol type="A">
>                 <li>node_tree(default)</li>
>                 <ol>
>                     <li><button class="sub" onclick="show_data();">show data</button></li>
>                     <li><button class="sub" onclick="save_file();">save file</button></li>
>                     <li><input id="file_input" class="file_input" type="file" /></li>
>                     <li><button class="sub" onclick="open_file();">open file</button></li>
>                 </ol>
>                 <li>node_array</li>
>                 <ol>
>                     <li>
>                         <button class="sub" onclick="get_nodearray_data();">show data</button>
>                     </li>
>                     <li>
>                         <button class="sub" onclick="save_nodearray_file();">save file</button>
>                     </li>
>                     <li><input id="file_input_nodearray" class="file_input" type="file" /></li>
>                     <li><button class="sub" onclick="open_nodearray();">open file</button></li>
>                 </ol>
>                 <li>freemind(.mm)</li>
>                 <ol>
>                     <li>
>                         <button class="sub" onclick="get_freemind_data();">show data</button>
>                     </li>
>                     <li>
>                         <button class="sub" onclick="save_freemind_file();">save file</button>
>                     </li>
>                     <li><input id="file_input_freemind" class="file_input" type="file" /></li>
>                     <li><button class="sub" onclick="open_freemind();">open file</button></li>
>                 </ol>
>             </ol>
>         </div>
>         <div id="jsmind_container"></div>
>         <div style="display: none">
>             <input class="file" type="file" id="image-chooser" accept="image/*" />
>         </div>
>     </div>
>     
>     <script type="text/javascript" src="script.js"></script>
> </body>
> ```

Here is the HTML which i created like in your repository example.

**Comment by hizzgdev** [comment]
so how do you run the html project in angular?

**Comment by hizzgdev** [comment]
Let us say this html file is named `jsmind.html`.

does angular open the html file in a new browser window?

```html
<!-- angular-1.html -->

<a href="jsmind.html">jsmind</a>
```

```html
<!-- angular-2.html -->

<a (click)="openJsmind()">jsmind</a>

<script>
    openJsmind() {
       window.open("jsmind.html");
    }
</script>
```

Or do you load the content of this html, and put the content into a certain angular page?

```html
<!-- angular-3.html -->

<div id='jsmind_content'></div>

<script>
    // It may not be runnable code, just for example.
    http.get('jsmind.html', function(content){
       $('#jsminnd_contennt').innerHTML = content
    })
</script>
```



- `angular-1.html` and `angular-2.html` will work fine
- `angular-3.html` I think there will be some problems. We should make sure that the js files in `jsmind.html` are loaded sequentially

**Comment by MShahzadulHassan** [comment]
No not like this, i just shared with you simple html project file, it has no concern with the angular project its a completely different project. I just want to figure out this 
"<script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.js"></script>
        
 <script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.draggable-node.js"></script>"
 
 I added these two script files in angular project file and also i added these two project file in HTML project file, but in HTML project using these two script files dragging of the node is working but in angular project file i used these two scripts but the dragging functionality is not working..
 I made different HTML project of jsmind just for the check that dragging is working using these scripts or not.

**Comment by hizzgdev** [comment]
So would you like to build a mini use case on angular, and share it with us, if it doesn't take much effort. I think it will be helpful for detect the root cause.

**Comment by MShahzadulHassan** [comment]
Hi, https://github.com/MShahzadulHassan/jsmind-angular this is the angular project of jsmind. You just have to run "npm install" in the project terminal and the start the project by running "npm start"

**Comment by MShahzadulHassan** [comment]
In this project, there is a "src" folder in which a component "app" and in "app.component.ts" I import the jsmind library. 
in "app.component.html" i wrtie the 
"<button (click)="addNode()"> Add </button>
<button (click)="removeNode()">Remove </button>
<div id="jsmind_container"></div>"

In "src" folder there is "index.html" file, in which i add scripts
"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>JsmindProject</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link
            type="text/css"
            rel="stylesheet"
            href="https://unpkg.com/jsmind@0.5/style/jsmind.css"
        />
        <script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.js"></script>
        <script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.draggable-node.js"></script>
        <script type="text/javascript" src="https://unpkg.com/jsmind@0.5/es6/jsmind.screenshot.js"></script>
</head>
<body>
  <app-root></app-root>
</body>
</html>
"

**Comment by hizzgdev** [comment]
Hi @MShahzadulHassan, Thanks for your demo project, it's much useful.

I think the root cause is `import` clause only loads `jsmind.js`, we have to load other files manually. I will go on the issue further, but there are 2 ways to load the additional js/css files as a quick-fix for your project, PTAL:

- https://github.com/MShahzadulHassan/jsmind-angular/pull/1
- https://github.com/MShahzadulHassan/jsmind-angular/pull/2

**Comment by MShahzadulHassan** [comment]
> Hi @MShahzadulHassan, Thanks for your demo project, it's much useful.
> 
> I think the root cause is `import` clause only loads `jsmind.js`, we have to load other files manually. I will go on the issue further, but there are 2 ways to load the additional js/css files as a quick-fix for your project, PTAL:
> 
> * [solution 1: link resources in node modules MShahzadulHassan/jsmind-angular#1](https://github.com/MShahzadulHassan/jsmind-angular/pull/1)
> * [solution 2: link resources in cdn MShahzadulHassan/jsmind-angular#2](https://github.com/MShahzadulHassan/jsmind-angular/pull/2)

Hi @hizzgdev ,  Yes it works now. Yes it causes due to import clause that only jsmind.js. Thanks for the help. 👍

**Comment by MShahzadulHassan** [comment]
this issue resolved. Thanks @hizzgdev  👍
