### ISSUE TITLE
右击鼠标弹出增删改节点，同时快捷键新增节点，这时右击鼠标会有问题

### ISSUE THREAD

**Issue by novelAide** [hizzgdev/jsmind#479]
您好，右击鼠标弹出增删改节点，同时快捷键新增节点，这时右击鼠标就不会弹出增删改节点的弹层。

步骤如下
1、根结点右击鼠标正常弹出
<img width="842" alt="image" src="https://github.com/hizzgdev/jsmind/assets/90837360/6ba160cf-c50a-404a-b2cc-c50433f71071">
2、使用快捷键新增节点，右击鼠标不会弹出图一的弹层，而是弹出浏览器默认的弹层
<img width="930" alt="image" src="https://github.com/hizzgdev/jsmind/assets/90837360/5b3c96e8-d06d-4cd5-967a-d18dd2224e36">
3、我试着去掉浏览器默认弹层，但是并没有效果。右击展示的menu弹层和快捷键新增节点不可以同时使用吗，我查看新增的数据也没有区别。希望收到您的回复，非常感谢。

**Comment by novelAide** [comment]
针对快捷键新增的节点，右击鼠标不仅不弹出图1的自定义弹层，还会唤醒拖拽这个节点的情况

<img width="666" alt="image" src="https://github.com/hizzgdev/jsmind/assets/90837360/a191894e-f004-47d6-a530-7830760e0b8a">

**Comment by hizzgdev** [comment]
jsMind 是不带右键菜单的，你看看是不是有第三方开发者实现的这个功能？

**Comment by novelAide** [comment]
谢谢，问题已经修复。哈哈，这个jsmind必须给一个5星好评。

**Comment by novelAide** [comment]
感觉有个地方可以优化，就是幕布的拖拽前提条件是只有超出水平或者垂直方向才可以拖拽。感觉没有这个前提条件，可以直接进行拖拽幕布会更好些。

**Comment by hizzgdev** [comment]
> 感觉有个地方可以优化，就是幕布的拖拽前提条件是只有超出水平或者垂直方向才可以拖拽。感觉没有这个前提条件，可以直接进行拖拽幕布会更好些。

是的，后面会考虑如何实现这种无边模式。
