### ISSUE TITLE
add new option node_max_width to allow to control  a node width 

### ISSUE THREAD

**Issue by bfctd** [hizzgdev/jsmind#483]
thanks for you add a new option node_overflow at v0.5.3 version. In addition, i hope that a new option is able to control the node width. developer decide what width can be hidden or wrapped

In addition，there is a bug that keyboard 46 can not be used. can you check it, I try that other keyboard code is right.

thank you @hizzgdev

**Comment by hizzgdev** [comment]
> developer decide what width can be hidden or wrapped

For the use-case, the better solution is [custom theme](https://github.com/hizzgdev/jsmind/blob/master/docs/en/1.usage.md#13-themes) [[CN](https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md#13-%E4%B8%BB%E9%A2%98)]


> keyboard 46 can not be used

I can not reproduce the issue.
But there is a common situation about [Delete] if you are using Mac: there is no [Delete] key on its keyboard, you have to use [Fn]+[Backspace] instead.

**Comment by bfctd** [comment]
Yes，you are right. but it is not flexible. i want the max-width rather than width fixed. do you think so ?

**Comment by hizzgdev** [comment]
Would you please consider whether you want to control the `min-width`, `max-height` etc. So i don't think flexible is better. flexible means `limited` or `confusing` or `complexity` sometimes.

- limited: I can control the max-width, but I can't control the min-width;
- confusing: I setup the max-width option both in jsmind options and the style sheet. Which will take effect?
- complexity: there are many options, maybe some of them are conflicting, I can't say it's easier.

If we want to control the global style, then change the style sheet of a theme.
If we wang to control the style of a single node, then add custom style for that node.
