### ISSUE TITLE
draggable-node doesn't work with requirejs

### ISSUE THREAD

**Issue by Vente16** [hizzgdev/jsmind#488]
Hi! I'm using the [RequireJS library](https://requirejs.org/). The problem is that the CDNs for the draggable-node module don't work properly; they appear as 'undefined'.

I've tested the following CDNs:

[UNPKG](https://unpkg.com/browse/jsmind@0.6.4/)
  - https://unpkg.com/browse/jsmind@0.6.4/es6/jsmind.draggable-node.js
  - https://unpkg.com/browse/jsmind@0.6.4/js/jsmind.draggable-node.js

[jsDelivr](https://www.jsdelivr.com/package/npm/jsmind)
  - https://cdn.jsdelivr.net/npm/jsmind@0.6.4/js/jsmind.draggable-node.js
  - https://cdn.jsdelivr.net/npm/jsmind@0.6.4/es6/jsmind.draggable-node.js

[jsDelivr 的国内镜像](https://jsd.onmicrosoft.cn/npm/jsmind/)
  - https://jsd.onmicrosoft.cn/npm/jsmind@0.6.4/js/jsmind.draggable-node.js
  - https://jsd.onmicrosoft.cn/npm/jsmind@0.6.4/es6/jsmind.draggable-node.js
  
Here's the example that I've been testing:
  
```
<div id="jsmind_container"></div>
<script type="text/javascript" src="https://requirejs.org/docs/release/2.3.6/comments/require.js"></script>
<script type="text/javascript">
  require.config({
    paths: {
      jsMind: "https://unpkg.com/jsmind@latest/es6/jsmind",
      draggable_node:
        "https://jsd.onmicrosoft.cn/npm/jsmind@0.6.4/js/jsmind.draggable-node",
      // other paths if needed
    },
  });

  require(["jsMind", "draggable_node"], function (jsMind, draggableNode) {
    // Load jsMind and draggable_node
    console.log(draggableNode); // this gets undefined
  });
</script>

```

**Comment by Vente16** [comment]
> Hi @Vente16 , have you seen the error below: <img alt="image" width="368" src="https://user-images.githubusercontent.com/1690290/260765154-61aa1327-a33f-458a-884f-442f6b5b9a43.png">
> 
> 1. `jsMind` is the dependency of `draggable_node`, and should be loaded before load `draggable_node`
> 2. `jsMind` should be global so it can be used in `draggable_node`
> 3. it's expected that `draggableNode` is `undefined`, since nothing is exported
> 
> try it:
> 
> ```js
>     require(["jsMind"], function (jsMind) {
>         window.jsMind = jsMind
>         require(["draggable_node"], function (draggableNode) {
>             var mind={};
>             var jm = new jsMind(options);
>             jm.show(mind)
>         });
>     });
> ```
> 
> I know it's not a good solution, but it can be used as a workaround. And, do you have any suggestion about that?

Yep, I've seen that error before and I solve it loading jsmind first and then draggable_node

I was wondering if there is any chance to have draggable_node in jsmind and enable it or disabled it with a param something like this:

```
   const options = { draggable: true }
   const jm = new jsMind(options);
```

If that would be possible I'd like to contribute with that

**Comment by hizzgdev** [comment]
Thank you for your kindness @Vente16 .

I have considered the solution to merge all plugins to `jsMind` core library. TBH, I don't like it, since we have to load all features whether you use them or not.

A better solution is publishing plugins as a standalone npm package, but I haven't decided if it should be.

**Comment by Vente16** [comment]
> Thank you for your kindness @Vente16 .
> 
> I have considered the solution to merge all plugins to `jsMind` core library. TBH, I don't like it, since we have to load all features whether we use them or not.
> 
> A better solution is publishing plugins as standalone npm packages, but I haven't figured out if they should be.

Okay, cool. 

```
    require(["jsMind"], function (jsMind) {
        window.jsMind = jsMind
        require(["draggable_node"], function (draggableNode) {
            var mind={};
            var jm = new jsMind(options);
            jm.show(mind)
        });
    });
```
This previews code didn't work for me same error but I will close this issue and figured out another way. Thanks!

**Comment by hizzgdev** [comment]
A new version v0.6.5 has been published. `jsMind` will work fine with `requirejs`:

```html
<script src="https://requirejs.org/docs/release/2.3.6/minified/require.js"></script>
<script type="text/javascript">
    require.config({
        paths: {
            // note: replace `latest` with a specific version on production
            'jsmind': 'https://unpkg.com/jsmind@latest/es6/jsmind',
            'jsmind/draggable_node':
                'https://unpkg.com/jsmind@latest/es6/jsmind.draggable-node',
        },
    });
    require(['jsmind', 'jsmind/draggable_node'], function (jsMind, _) {
        let mind = {...};
        let options = {
            container: 'jsmind_container',
            editable: true,
            theme: 'primary',
        };
        let jm = new jsMind(options);
        jm.show(mind);
    });
</script>
```

Please note that `jsmind.js` is not in the `js` directory but `es6`

https://hizzgdev.github.io/jsmind/example/3_requirejs.html
