### ISSUE TITLE
能否控制节点输入字符长度事件回调

### ISSUE THREAD

**Issue by baiyajin** [hizzgdev/jsmind#489]

**Comment by hizzgdev** [comment]
如果有这样的功能，你希望它是什么样子的呢，或者怎么使用这个回调呢？

**Comment by baiyajin** [comment]
我想控制输入的文字长度



---原始邮件---
发件人: "Zhigang ***@***.***&gt;
发送时间: 2023年8月16日(周三) 下午3:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hizzgdev/jsmind] 能否控制节点输入字符长度事件回调 (Issue #489)




 
如果有这样的功能，你希望它是什么样子的呢，或者怎么使用这个回调呢？

**Comment by hizzgdev** [comment]
嗯，你是希望有一个参数能够配置 max-length 呢？还是说加个 callback， 超长了就回调呢？以及如果有这些功能的话，你的代码应该是什么样的呢？

**Comment by baiyajin** [comment]
max-length 挺不错的，目前有没有这个配置



---原始邮件---
发件人: "Zhigang ***@***.***&gt;
发送时间: 2023年8月16日(周三) 下午3:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hizzgdev/jsmind] 能否控制节点输入字符长度事件回调 (Issue #489)




 
嗯，你是希望有一个参数能够配置 max-length 呢？还是说加个 callback， 超长了就回调呢？以及如果有这些功能的话，你的代码应该是什么样的呢？

**Comment by hizzgdev** [comment]
事实上 `max-length` 并不应该是一个 jsMind 提供的功能。 因为 jsMind 支持读取脑图文件，这个文件是一个普通的文本文件，对其进行修改并无任何难度，因此在编辑器上做这种限制我认为意义不大。

对于 callback 方案，jsMind 提供的有 event 可供使用，不过它只能被动接收 event，而不能直接对 event 进行撤销，但是也可以在 event handler 里自行添加一些逻辑以支持这个需求。
