### ISSUE TITLE
移动端的自适应

### ISSUE THREAD

**Issue by 13994853095** [hizzgdev/jsmind#494]
在移动端使用时发现android设备节点间的距离适应的很好，但是ios会堆叠在一起，看起来很拥挤

**Comment by 13994853095** [comment]
![image](https://github.com/hizzgdev/jsmind/assets/135119632/38dd7ec0-3e5d-42e0-ae0b-8f20c1efe5e0)
就像这样

**Comment by hizzgdev** [comment]
你能把android上的截图也贴出来吗？

另外，麻烦看一下页面上引用的样式表的url是什么？

**Comment by 13994853095** [comment]
好的
![f0c88f375d7b9ed8bcf74c265f6ed1e](https://github.com/hizzgdev/jsmind/assets/135119632/e24b7a37-b961-44dd-9deb-732760e16761)
![602d2f0337fa1d17d314dd7e2cb8e3f](https://github.com/hizzgdev/jsmind/assets/135119632/4730fe01-ac86-4da5-abdd-38f6b89b4284)

**Comment by 13994853095** [comment]
在safari和chrome都试了，今天在ios做真机调试，发现是jmnodes的宽度变成跟父容器一样的，但是在android又不会这样，就很奇怪，之前在pc端也有类似的问题，当时是因为在还没切换到mindmap菜单时，就初始化jsmind，它无法获取准确的父容器宽高并自适应

**Comment by 13994853095** [comment]
我今天又试了一下应该是缩放的问题，我之前的代码在初始化时将zoom比例改成了0.5，现在我注释掉了，刚初始完成时就是正常的，但是我如果继续有缩放相关的操作，思维导图的效果又会挤在一起
![76879d42d4659132a07d85d7d325bea](https://github.com/hizzgdev/jsmind/assets/135119632/3a5f1556-f25f-47f9-be2c-56e7d6dcca95)

**Comment by 13994853095** [comment]
又测试了一会，问题更具体了，在ios上思维导图进行缩放时，每个节点box会跟随缩放，但是节点内容的fontsize却不会跟着缩放，导致虽然节点box宽度变窄了，高度却被字体撑开，就拥挤了

**Comment by hizzgdev** [comment]
感谢，你有没有在其它苹果手机上试过？我自己验证时 zoom in / out 时字体都会跟随缩放。是不是手机设置了强制字体大小？

**Comment by 13994853095** [comment]
试了，那可能是我的代码有问题吧，我去排查一下，感谢

**Comment by 13994853095** [comment]
因为我也单独写了一个box去测试fontsize是否随着zoom改变，结果是可以的，那看来是我思维导图的配置或者哪一步写的有问题
