### ISSUE TITLE
allow images to be in nodes

### ISSUE THREAD

**Issue by MEgooneh** [hizzgdev/jsmind#497]
is there a way for a node to contain images?
even allowing markdown rendering for boxes would be enough probably.

**Comment by hizzgdev** [comment]
Yes, images can be added to a mindmap in jsmind in 2 ways:

1. [recommended] add as a background. The feature is documented at [operation-setting-style](https://github.com/hizzgdev/jsmind/blob/master/docs/en/3.operation.md#35-setting-style) , and there is a demo of it: [all features](https://hizzgdev.github.io/jsmind/example/2_features.html) - [click “open example” button on the left-top of the page]

2. add as html-tag, by default jsmind allows you put html into node.topic, so it will be the last workaround you can take. The option about html supports is described in [options](https://github.com/hizzgdev/jsmind/blob/master/docs/en/2.options.md)
