### ISSUE TITLE
Implementing draggable plugin with  Iframes

### ISSUE THREAD

**Issue by Vente16** [hizzgdev/jsmind#503]
Hi there! When I have two iframes, and each one loads jsmind and jsmind.draggable-node, I get this error:

"Error: can not register plugin draggable_node: plugin name already exist"

![jsmind-problem](https://github.com/hizzgdev/jsmind/assets/22964999/5026b7e6-8399-40bd-baff-8a6c36b7162e)

The issue is over [here](https://github.com/hizzgdev/jsmind/blob/master/src/jsmind.plugin.js#L20). Is it possible to tell if the plugin was already loaded? Which means not to do nothing

Thanks a lot!

**Comment by hizzgdev** [comment]
Thanks for your report.
can you detail the case? I don't think jsmind/plugins in different iframes will affect each other.

**Comment by Vente16** [comment]
Hey @hizzgdev thanks for your fast replay. It was my bad it works properly. I will close this
