### ISSUE TITLE
思维导图节点使用support_html属性和<span>标签自定义，点击<span>文字无法选中节点

### ISSUE THREAD

**Issue by mxq-crystal** [hizzgdev/jsmind#506]
``` 
// jsMind 配置
let options = {
        container: 'jsmind_container',
        theme: 'primary',
        support_html: true, // topic是否支持自定义HTML元素
        log_level: 'disable',
        mode: 'side', // 子节点只分布在根节点右侧
        view: {
          engine: 'canvas', // 思维导图各节点之间线条的绘制引擎
          hmargin: 20, // 思维导图距容器外框的最小水平距离
          vmargin: 10, // 思维导图距容器外框的最小垂直距离
          line_width: 2, // 思维导图线条的粗细`
          line_color: '#e9e3e3', // 思维导图线条的颜色
          draggable: true
        },
      };
this.jm = new jsMind(options);
this.jm.show(mind);

```

```  
// 节点文字显示
node.topic = `<span><span>${item.question}</span><br/><span>${item.contents}</span></span>`;
```
点击${item.contents}和${item.question}文字区域无法触发节点选中事件，点击节点的padding区域可以触发，请问有什么办法可以在文字区域点击时也触发呢？

**Comment by hizzgdev** [comment]
我这里并不能复现你说的这个现象。你要不在这个 demo 页修改一个节点的 topic 试试看。https://hizzgdev.github.io/jsmind/example/2_features.html

- 如果仍然无法选中节点，那可能是浏览器的问题，或许可以换个电脑或换个浏览器试一下，另外麻烦提供一下你的浏览器及操作系统。
- 如果在上面的页面中没有问题，那猜测可能有以下几种可能：
    - 不是最新版本
    - 页面上有其它脚本接管了 span 的 click 事件
    - 页面上有额外的样式影响到了对 span 的 click

@mxq-crystal

**Comment by mxq-crystal** [comment]
> 我这里并不能复现你说的这个现象。你要不在这个 demo 页修改一个节点的 topic 试试看。https://hizzgdev.github.io/jsmind/example/2_features.html
> 
> * 如果仍然无法选中节点，那可能是浏览器的问题，或许可以换个电脑或换个浏览器试一下，另外麻烦提供一下你的浏览器及操作系统。
> * 如果在上面的页面中没有问题，那猜测可能有以下几种可能：
>   
>   * 不是最新版本
>   * 页面上有其它脚本接管了 span 的 click 事件
>   * 页面上有额外的样式影响到了对 span 的 click
> 
> @mxq-crystal
<img width="1384" alt="image" src="https://github.com/hizzgdev/jsmind/assets/133733133/b3511f55-b7b8-4231-a935-7dc337e56772">
像图中例子一样，先执行“change color”操作再只从“change backgorund”操作 以方便看到文字在图片之上，当我点击文字“Easy To edit”时文字消失且节点未选中，像是被背景图覆盖了

**Comment by mxq-crystal** [comment]
感谢你的回答。

jsMind非最新版，0.6+（6个月前的版本）
因业务需要，未安装依赖包，而是直接引入源代码文件

浏览器  chrome 117.0.5938.149（正式版本） (x86_64) 
操作系统  macOS Big Sur 11.7.2

我已经通过笨办法解决了：在span上绑定节点id，然后addEventListener('click', this.handleClick)和this.jm.select_node(e.target.id)

**Comment by mxq-crystal** [comment]
我看到你对这个问题的解答：https://github.com/hizzgdev/jsmind/issues/293
我用了两种方式都有点小问题：

1.将 `input type=text`改成 `input type=textarea`
并未能实现节点换行，但title提示换行了
```
// 节点文字显示
node.topic = `<span>Q: ${item.question}\nC: ${item.contents}</span>`;
```

<img width="271" alt="image" src="https://github.com/hizzgdev/jsmind/assets/133733133/55872fcc-8d84-479e-910a-dc6e98a79bfb">

2. 使用support_html属性 & <br/>标签
```
// 节点文字显示
node.topic = `<span>Q: ${item.question}<br/>C: ${item.contents}</span>`;
```
可以实现换行，但title显示如图
<img width="421" alt="image" src="https://github.com/hizzgdev/jsmind/assets/133733133/0aa126fb-eadc-4470-9d8e-f13328368774">

请问有什么办法可以解决吗
@hizzgdev

**Comment by hizzgdev** [comment]
并不是把 `<input type="text">` 改成 `<input type="textarea">`, 而是改成 `<textarea></textarea>`，你再这样试试呢？

另外 `jmnode` 节点上并没有 `title` 属性啊。你用的是文档中的提到的 cdn 上的版本吗？
