### ISSUE TITLE
节点删除之后未及时更新 index 属性导致与index 属性相关的方法出现异常，如find_node_after等

### ISSUE THREAD

**Issue by shuanglei7** [hizzgdev/jsmind#551]
## demo
官网example

## 复现步骤：
1. 添加多个二级节点
2. 随意删除几个节点
3. 使用键盘方向键快捷选中，会出现意料之外的错误

**Comment by shuanglei7** [comment]
复现步骤描述错误
需添加多个非二级节点

**Comment by hizzgdev** [comment]
感谢报告，我确认一下。

**Comment by hizzgdev** [comment]
@shuanglei7  你好，此问题已在 [0.7.9](https://github.com/hizzgdev/jsmind/discussions/556) 版本中修复，请更新后试用，如有问题请随时反馈。感谢！
