### ISSUE TITLE
放大后截图，存在节点错乱问题

### ISSUE THREAD

**Issue by mxq-crystal** [hizzgdev/jsmind#552]
在官方示例中
https://hizzgdev.github.io/jsmind/example/2_features.html

首先创建一些节点～
<img width="1093" alt="image" src="https://github.com/hizzgdev/jsmind/assets/133733133/ade326a8-c7aa-42a3-9b6c-a8a35e2cb941">

当放大后截图～
<img width="1270" alt="image" src="https://github.com/hizzgdev/jsmind/assets/133733133/5ad26d8c-eb07-4178-9ebb-ef370d006a0a">

保存的图片如图～
<img width="1404" alt="image" src="https://github.com/hizzgdev/jsmind/assets/133733133/30259d3b-47d5-4ef9-acf8-71ba6e03ed9c">

请问这是一个已知的bug吗～

**Comment by hizzgdev** [comment]
感谢报告，我确认一下。

**Comment by hizzgdev** [comment]
已确认，近期将修复。

**Comment by mxq-crystal** [comment]
万分感谢～

**Comment by hizzgdev** [comment]
@mxq-crystal 你好，此问题已在 [0.7.9](https://github.com/hizzgdev/jsmind/discussions/556) 版本中修复，请更新后试用，如有问题请随时反馈。感谢！
