### ISSUE TITLE
脑图的垂直上下展示的一个方案

### ISSUE THREAD

**Issue by yohanceli** [hizzgdev/jsmind#56]
现在仅支持水平左右展示，想知道何时会支持垂直上下展示？很有业务需求都是垂直展示的

**Comment by guimeisang** [comment]
考虑下怎么做这个？因为我们这边也需要做组织结构的脑图

**Comment by hizzgdev** [comment]
希望大家能一起完成这个需求。

**Comment by perseverancer** [comment]
![image](https://user-images.githubusercontent.com/17759912/29019107-24caa2a6-7b90-11e7-8fe6-2d355552ef52.png)
还不完善，线有重叠的部分，还不知怎么弄

**Comment by guimeisang** [comment]
怎么实现？可以p出修改的地方么？
一起来解决这个重叠部分

**Comment by perseverancer** [comment]
提交之前有些问题要改，这两天有点忙，过两天

**Comment by hizzgdev** [comment]
@perseverancer
把折线换成曲线就不存在重叠的问题了。

**Comment by guimeisang** [comment]
你好，怎么实现支持鱼骨图，和组织结构图，另外连线的颜色也可以改变～

**Comment by hizzgdev** [comment]
感谢 @perseverancer 发起的PR: https://github.com/hizzgdev/jsmind/pull/103 。各位可以先尝试一下

**Comment by hizzgdev** [comment]
因太久没有更新而关闭
