### ISSUE TITLE
freemind格式文件支持问题

### ISSUE THREAD

**Issue by xdsnet** [hizzgdev/jsmind#57]
我尝试了几次，利用freemind格式的文件（利用xmind输出的）都不能正常显示。
利用的2_features.html 页面，在本地或者在你的页面 http://hizzgdev.github.io/jsmind/example/2_features.html 上都是类似的问题。
已经确认mind数据加载成功，单步调试可以看见文件被正确加载，但显示不出来。
下面是测试用的数据
[tt.zip](https://github.com/hizzgdev/jsmind/files/565628/tt.zip)

**Comment by xdsnet** [comment]
[Uploading tt.zip…](测试用的freemind数据)

**Comment by xdsnet** [comment]
我后来追踪了下执行过程，发现所有节点都需要定义属性"expanded"，而一般的freemind文件节点是不包括这个属性的。

**Comment by hizzgdev** [comment]
@xdsnet 感谢你的支持，这个问题我已经修复了。请试用。
如果还有其他的问题，也欢迎随时提出。

https://github.com/hizzgdev/jsmind/commit/6428b35917b697d70d3baabc86f861ce288e7991
