### ISSUE TITLE
特性请求：节点链接属性支持

### ISSUE THREAD

**Issue by xdsnet** [hizzgdev/jsmind#58]
JSmind很好，对于思维导图等的展示很方便，不过希望增加对节点链接属性的支持，对有链接属性的节点展示一个特定的图标，并且可以点击打开链接。

**Comment by hizzgdev** [comment]
链接属性是freemind提供的吗？如果是的话，我考察一下，可以进行支持。如果不是的话，你可以给一个节点的topic设置为html代码以实现链接功能。

**Comment by xdsnet** [comment]
链接属性是freemind提供的，选中节点后，插入菜单中可以分别插入到文件（快捷键 Ctrl+Shift+K）的链接或者文字（URL，快捷键 Ctrl+K）

**Comment by leeboo** [comment]
建议：
显示的节点除了topic，在增加一个内容，比如text等；这样显示的时候显示topic，里面有html内容，如图标，链接等，双击修改时显示text这个纯文本

**Comment by hizzgdev** [comment]
@leeboo

jsmin主要是为了显示脑图，其编辑功能比较弱，目前也并没有这方面的功能增强计划，你可以尝试自己完善。
至于增加内容方面，jsmind的每一个node都有一个data属性可以存储额外的信息。你可以试着用用。

**Comment by manyuanbin** [comment]
jsmind node是否支持html不仅仅是string 的topic

**Comment by ttsdzzg** [comment]
@manyuanbin 不是很明白你的意思。
目前node支持普通文本，图片，以及html。
这些特性文档中都有描述，你可以看看是否满足你的要求。

**Comment by hizzgdev** [comment]
@manyuanbin 不是很明白你的意思。
目前node支持普通文本，图片，以及html。
这些特性文档中都有描述，你可以看看是否满足你的要求。

**Comment by mendream** [comment]
麻烦问一下，怎么实现给一个节点的topic设置为html代码以实现链接功能？本人是小白，新来的，麻烦了

**Comment by hizzgdev** [comment]
@mendream 
```javascript
jm.add_node('pid', 'id', '<a href="node-url">node-topic</a>',null);
jm.update_node('id','<a href="node-url">node-topic</a>');
```
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/3.operation.md#34-编辑节点
添加节点 : 使用 jm.add_node(parent_node, nodeid, topic, data) 方法可添加一个节点。
更新节点 : 使用 jm.update_node(nodeid, topic) 方法可更新指定节点的 topic

**Comment by xue560** [comment]
麻烦问一下，jsmind能否更改线条为折线以及在线条上增加备注信息

**Comment by hizzgdev** [comment]
@xue560 
目前不支持在线条上增加备注，也不支持直接通过配置改为折线。
但改折线还是比较容易的，你看一下源码的 bezierto 或 lineto 方法，实现一下折线的方法就行了。
