### ISSUE TITLE
淘宝源的旧地址SSL已经过期，目前默认设置还是指向旧的

### ISSUE THREAD

**Issue by JerryWangTdcy** [hizzgdev/jsmind#580]
问题：
https://registry.npm.taobao.org/  地址的SSL已经过期了，现在没办法正常安装，只能关闭SSL安装依赖。

<img width="1255" alt="image" src="https://github.com/hizzgdev/jsmind/assets/34759071/c7d493c1-efab-4fdb-be89-1a72cb4eb77b">

期望：更换新的地址

**Comment by hizzgdev** [comment]
你确定没有发错地方吗？

**Comment by JerryWangTdcy** [comment]
错了错了，不好意思。 麻烦删掉吧....
