### ISSUE TITLE
通过npm包安装的无法使用下载导图和拖拽功能啊

### ISSUE THREAD

**Issue by asheng1219** [hizzgdev/jsmind#582]
TypeError: Cannot read properties of undefined (reading 'w')
    at eval (jsmind.draggable-node.js:8:319)
    at eval (jsmind.draggable-node.js:8:22)
    at eval (jsmind.draggable-node.js:8:108)
    at ./node_modules/jsmind/es6/jsmind.draggable-node.js (12.js:67:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/mind/mind.vue?vue&type=script&lang=js&:35:94)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/mind/mind.vue?vue&type=script&lang=js& (11.js:59:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)    会出现这样的错误

**Comment by asheng1219** [comment]
解决掉了 需要编译下es6的语法

**Comment by hizzgdev** [comment]
```javascript
    import jsMind from 'jsmind'
    import 'jsmind/draggable-node'
    import 'jsmind/style/jsmind.css'
```

可以参考这个示例
https://github.com/hizzgdev/jsmind-samples/tree/main/jsmind-vue

**Comment by asheng1219** [comment]
import 'jsmind/es6/jsmind.draggable-node.js';
这种方式引入的可以使用

**Comment by asheng1219** [comment]
import 'jsmind/draggable-node' 
这种方式引入的会报错找不到路径
import 'jsmind/es6/jsmind.draggable-node.js';
完整的引入才可以
现在又遇到一个问题
import domtoimage from 'dom-to-image';
import 'jsmind/es6/jsmind.screenshot.js';
引入screenshot的时候 我已经安装了dom-to-image并且引入了还是会报错
Error: dom-to-image is required

**Comment by asheng1219** [comment]
因为我的项目需要再无网络状态下运行 没有办法使用csdn 但是我按照您的官方文档去操作确实出现了这种错误找不到路径的错误 我的项目node.js是10.22.0,使用的是vue2 ,可能是项目比较老吧 不过还是感谢作者大大您的回答

**Comment by JinHaocong** [comment]
我在vue2项目中使用时报了这个错 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 请问怎么解决？

**Comment by JinHaocong** [comment]
好的已经解决啦谢谢
发自我的 iPhone

在 2024年3月23日，20:13，Zhigang Zhang ***@***.***> 写道：

﻿

抱歉 @JinHaocong<https://github.com/JinHaocong> 我本人也并非太了解 vue，以后有时间我会尝试也在 vue2 的环境里试一下。但在此之前，恐怕还需要你自己多尝试尝试，如果发现需要修改 jsMind 才能解决的话，麻烦也告诉我一声，我可以在下个版本里把这个补丁给打上。非常感谢！

**Comment by JinHaocong** [comment]
> 抱歉 @JinHaocong 我本人也并非太了解 vue，以后有时间我会尝试也在 vue2 的环境里试一下。但在此之前，恐怕还需要你自己多尝试尝试，如果发现需要修改 jsMind 才能解决的话，麻烦也告诉我一声，我可以在下个版本里把这个补丁给打上。非常感谢！

只需要降级一下es6语法即可

**Comment by JerryWangTdcy** [comment]
> > 抱歉 @JinHaocong 我本人也并非太了解 vue，以后有时间我会尝试也在 vue2 的环境里试一下。但在此之前，恐怕还需要你自己多尝试尝试，如果发现需要修改 jsMind 才能解决的话，麻烦也告诉我一声，我可以在下个版本里把这个补丁给打上。非常感谢！
> 
> 只需要降级一下es6语法即可

您好，能说一下具体如何操作的吗？

**Comment by JinHaocong** [comment]
> 抱歉 @JinHaocong 我本人也并非太了解 vue，以后有时间我会尝试也在 vue2 的环境里试一下。但在此之前，恐怕还需要你自己多尝试尝试，如果发现需要修改 jsMind 才能解决的话，麻烦也告诉我一声，我可以在下个版本里把这个补丁给打上。非常感谢

我的项目是老版本的vue2项目，bable.config.js已经配置了'@vue/cli-plugin-babel/preset'，但是还是报错需要额外的loader来处理jsmind，后来查阅资料发现，这个预设不会对node_modules中的包进行处理，如需要额外处理，需要在vue.config.js中添加modules.exports = {
  transpileDependencies: ['jsmind'],
}
这样就可以了

**Comment by JinHaocong** [comment]
> > > 抱歉 @JinHaocong 我本人也并非太了解 vue，以后有时间我会尝试也在 vue2 的环境里试一下。但在此之前，恐怕还需要你自己多尝试尝试，如果发现需要修改 jsMind 才能解决的话，麻烦也告诉我一声，我可以在下个版本里把这个补丁给打上。非常感谢！
> > 
> > 
> > 只需要降级一下es6语法即可
> 
> 您好，能说一下具体如何操作的吗？

vue-cli官方文档是这样说的
![image](https://github.com/hizzgdev/jsmind/assets/100753463/e801e094-a4b3-4c1a-a16b-432d1ff1f2e2)

**Comment by 2878547611yll** [comment]
> > 抱歉 @JinHaocong 我本人也并非太了解 vue，以后有时间我会尝试也在 vue2 的环境里试一下。但在此之前，恐怕还需要你自己多尝试尝试，如果发现需要修改 jsMind 才能解决的话，麻烦也告诉我一声，我可以在下个版本里把这个补丁给打上。非常感谢
> 
> 我的项目是老版本的vue2项目，bable.config.js已经配置了'@vue/cli-plugin-babel/preset'，但是还是报错需要额外的loader来处理jsmind，后来查阅资料发现，这个预设不会对node_modules中的包进行处理，如需要额外处理，需要在vue.config.js中添加modules.exports = { transpileDependencies: ['jsmind'], } 这样就可以了

加上后页面报错
![image](https://github.com/user-attachments/assets/f51b6b17-94a0-49b2-8c0f-053594968906)

![image](https://github.com/user-attachments/assets/02edad4f-1938-4aca-8ea6-adf689e55b56)是什么情况
