### ISSUE TITLE
用例示范需求：对freemind格式远程加载

### ISSUE THREAD

**Issue by xdsnet** [hizzgdev/jsmind#59]
例子代码中有对json数据格式的远程加载示范，没有对freemind格式的。
例子中的freemind格式加载采用的是file对象，这和远程加载不同，我参照对json尝试对freemind进行加载，老是报错。我加载freemind的代码是：
```
  jsMind.util.ajax.get("test.mm",function(freemind_data){
   var options = {
            container:'jsmind_container',
            theme:'greensea',
            editable:false
        }
   var mind={
        "meta":{
               "name":"testmm",
               "author":"xdsnet",
              "version":"1.0.0"
        },
        "format":"freemind",
        "data":freemind_data
   };
   jsMind.show(options,mind);
}```

**Comment by hizzgdev** [comment]
FYI: 
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md#c-freemind格式示例

**Comment by xdsnet** [comment]
不是freemind格式，格式没有问题，就是这么采用jsmind远程加载freemind文档

**Comment by hizzgdev** [comment]
你的这个写法是没有问题的，报错的原因是 `jsMind.util.ajax.get(...)` 这个方法仅支持json格式的数据，没有兼容其他的格式，我已经在这个 commit https://github.com/hizzgdev/jsmind/commit/e73181958065a11cb3449ea9f8dc488d70e8245e 中进行了修复。请试用。

感谢你的宝贵意见。
