### ISSUE TITLE
最后一个节点编辑后，宽度无法正确调整

### ISSUE THREAD

**Issue by HefeiWangDan** [hizzgdev/jsmind#590]
![image](https://github.com/hizzgdev/jsmind/assets/22468869/49cf51ce-7051-4149-8fcf-b8f37780ce17)
在图片中， 右侧的节点在编辑后使用update_node更新，宽度未正确调整
开发环境：
 1."vue": "^3.4.21",
 2."jsmind": "^0.8.2",  
其他节点编辑后，正常更新
期望作者大大可以回复

**Comment by hizzgdev** [comment]
看上去最右边的节点样式好像跟其它节点样式不太一样，你有修改它的样式吗？
另外，你提到其它节点编辑后能正常更新，那这个节点是否有哪里不同呢？
你先排查一下，不行的话我们再一起看看代码。

**Comment by HefeiWangDan** [comment]
我是自定义了节点的样式，新增的子节点是一样的，没有不同，只有在编辑后会出现UI问题，add_node也是正常的。
这是新增节点代码
const addNode = () => {
  if (!selectedId.value) return
  const newid = jsMind.util.uuid.newid()
  _jm.add_node(_jm.get_node(selectedId.value), newid, '子主题', { data: { level: 'other' } }, 'right')
  isChange.value = true
  clearSelected()
  _jm.select_clear()
  nextTick(() => {
    _jm.select_node(newid)
    selectedId.value = newid
    showSetting.value = true
    _jm.scroll_node_to_center(newid)
  })
}
这是编辑后失去焦点的代码
const handlerBlur = () => {
  clearSelected()
  const { id } = topicElement!.dataset
  showEdit.value = false
  nextTick(() => {
    _jm.update_node(id, editValue.value)
    editValue.value = ''
  })
}
这是我的dom
  <div
    ref="jsmindContainer"
    class="flow-mind-box"
    :class="{ 'is-default': !editable, 'is-editing': showEdit }"
    @pointerup.prevent="emits('openDialog')"
  >
    <Teleport :to="`#${selectedId}`" v-if="showEdit">
      <el-input
        v-model="editValue"
        ref="textareaRef"
        class="flow-mind-box__input"
        type="textarea"
        placeholder="请输入内容"
        resize="none"
        autosize
        @blur="handlerBlur"
        @pointerup.stop="void 0"
      />
    </Teleport>
    <Teleport :to="`#${selectedId}`" v-if="showSetting">
      <div :class="{ 'flow-mind-box__btn': true, 'root-btn': selectedId === 'root_1' }">
        <i class="flow-mind-box__btn-icon icon_flow_add" @pointerup.stop="void 0" @pointerdown.stop="addNode"></i>
        <i class="flow-mind-box__btn-icon icon_flow_delete" @pointerup.stop="void 0" @pointerdown.stop="deleteNode"></i>
      </div>
    </Teleport>
  </div>

**Comment by hizzgdev** [comment]
上面代码倒看不出有什么问题，你能弄一个小的项目，并把必要的代码放上去，然后我们一起调试一下吗？我还是怀疑页面上有其它样式干扰。

**Comment by HefeiWangDan** [comment]
已经解决了, 修改hmargin和vmargin, 就正常了
