### ISSUE TITLE
关于远程加载freemind

### ISSUE THREAD

**Issue by xdsnet** [hizzgdev/jsmind#60]
昨天提到需要远程加载freemind示范，结果我后来追踪了一下代码，发现是jsMind.util.ajax.request 的实现有兼容性问题造成的，在实现中默认预设了远程获取数据只能是json类的，而不能兼容xml，所以造成这样的问题，解决办法是把`var data = eval('('+xhr.responseText+')');` 改为`var data = xhr.responseText;`即可，这样修改后，远程加载json数据需要在自定义的回调函数中进行数据处理，比如例子中“2_features.html”的远程加载“open remote”的“"open_ajax()”的函数实现中需要把`_jm.show(mind);`改为`_jm.show( eval('('+mind+')'));`，这样兼容性更好

**Comment by ttsdzzg** [comment]
参见你昨天的这个 issue https://github.com/hizzgdev/jsmind/issues/59 ，我已经处理过了。
处理的逻辑与你的想法类似，首先尝试转换为json，转换失败后会回落到原始的字符串，这样可以与上版本的jsmind兼容。

请试用。感谢你的宝贵意见。

此问题得到解决后，请关闭这个 issue。

**Comment by hizzgdev** [comment]
参见你昨天的这个 issue https://github.com/hizzgdev/jsmind/issues/59 ，我已经处理过了。
处理的逻辑与你的想法类似，首先尝试转换为json，转换失败后会回落到原始的字符串，这样可以与上版本的jsmind兼容。

请试用。感谢你的宝贵意见。

此问题得到解决后，请关闭这个 issue。

**Comment by xdsnet** [comment]
确实可以这样处理。
