### ISSUE TITLE
节点内输入的内容怎么换行？

### ISSUE THREAD

**Issue by w4rw4r** [hizzgdev/jsmind#609]
节点点输入时Enter、Shift+Enter、Ctrl+Enter、Alt+Enter都不能实现换行操作，而且粘贴多行文本后也是现实单行，貌似\n换行符无效

**Comment by hizzgdev** [comment]
是的，目前默认的输入框是单行输入框，所以任何换行字符都不能输入。
如果你的目的是让用户能输入换行，可以有两种方法：
- 修改源码，把单行输入框改成多行输入框，并处理好回车事件：换行还是保存
- 不直接使用jsmind的编辑功能，而使用api来更新节点内容，配合 custom_render 把换行符替换成`<br>`。

如果有困难可以再来寻求帮助。

**Comment by haomingjian063893** [comment]
修改源码中，jsmind.view_provider.js、jsmind.js中的键盘监听事件，先判断ctrl + 回车的时，将target的value加上一个\n, 然后return掉，阻止下面结束编辑的方法，亲测有效

**Comment by UmbraCi** [comment]
@hizzgdev 是否可以考虑在源码加一个配置项，让用户可以决定使用input还是textarea，并且追加、修改相关键盘事件
