### ISSUE TITLE
无效代码问题

### ISSUE THREAD

**Issue by xdsnet** [hizzgdev/jsmind#61]
jsmind.js 的1772行是定义的`_layout_offset_subnodes_height:function(nodes)`，其实现代码中存在大量无效代码，其中从1774行至1811行的代码都在return之后，是不能执行的，是否是忘记注释掉了？

**Comment by hizzgdev** [comment]
@xdsnet 
这是曾经调试的时候加的代码，后来忘记删除了。
非常感谢你的指出。
