### ISSUE TITLE
这个方向是对了，细节上有小问题，引用不要远程引用，用本地的，如

### ISSUE THREAD

**Issue by woodgreat** [hizzgdev/jsmind#620]
这个方向是对了，细节上有小问题，引用不要远程引用，用本地的，如
<body>
        <div id="jsmind_container"></div>
        <script src="./js/jsmind.js"></script>
        <script src="./js/jsmind.draggable-node.js"></script>

这个程序运行会表现稳定好多，还有，库中用例部分不够系统，1_basic_cn 改写后能正工作 。2_features_cn就不行了，如处理的好用，用的人会更多，不用考虑自动升级的问题，因为这是使用者考虑的，只要把库做的好用，快用，就很好了。

**Comment by hizzgdev** [comment]
所以 issue 是啥呢？是发错地方了吗？
