### ISSUE TITLE
双击Node进入编辑后，直接拖拽输入框会导致异常

### ISSUE THREAD

**Issue by mydaoyuan** [hizzgdev/jsmind#622]
处于编辑模式下进行拖拽的情况。鼠标会一直有一个空白的node节点。

<img width="821" alt="image" src="https://github.com/user-attachments/assets/a737b99c-bc36-4824-bb08-8af942b182e0">

**Comment by mydaoyuan** [comment]
复现流程：
1、双击一个节点进入编辑模式。
2、直接拖拽节点的边框

**Comment by hizzgdev** [comment]
感谢报告

**Comment by hizzgdev** [comment]
已修复 https://github.com/hizzgdev/jsmind/pull/623 ，将随下个版本一并发布。
