### ISSUE TITLE
你好，我通过npm下载使用导出成为图片功能发现下载后少文件

### ISSUE THREAD

**Issue by Eohu** [hizzgdev/jsmind#625]
![Uploading 微信截图_20240729140828.png…]()

**Comment by Eohu** [comment]
![Uploading 微信截图_20240729140828.png…]()

**Comment by Eohu** [comment]
[https://txr001.zthj.net/Carbon-footprint-accounting/index/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20240729140828.png](url)

**Comment by hizzgdev** [comment]
并未能复现出你截图里的现象，你能否确认一下版本号？
你也可以看看你项目里 node_modules/jsmind 里的文件是否跟这个截图里一样。

![image](https://github.com/user-attachments/assets/07b679fe-869c-4ce4-89c4-81619ae04688)

**Comment by Eohu** [comment]
找到对应的文件了，可以拿到这个图片的路径吗？

**Comment by hizzgdev** [comment]
jsmind是一个浏览器端的类库，所以这个图片只在浏览器的内存里，所以没有一个url。

如果你指的路径是下载保存的路径，jsmind 也是没法知道的，有些高级的浏览器api支持把文件保存到指定的位置，你可以查查相关的资料，但那已经超出了jsmind的职责范围了。

你也可以看看源码，根据自己的需要把图片存到指定的地方。如果有需要可以联系我一起帮你实现。

**Comment by Eohu** [comment]
您好，这个怎么单独把双击编辑事件组织掉？

**Comment by hizzgdev** [comment]
```javascript
var options = {
      container: 'jsmind_container',
      theme: 'orange',
      editable: true,
      default_event_handle: {
          enable_mousedown_handle: true,
          enable_click_handle: true,
          enable_dblclick_handle: true,
          enable_mousewheel_handle: true,
      }
  };

```

default_event_handle 这里还有几个参数，你把其中的 enable_dblclick_handle 改成 false 应该就可以了。 @Eohu

**Comment by hizzgdev** [comment]
由于这并不是issue，先关闭了哈，有问题的话可以到 [Discussion](https://github.com/hizzgdev/jsmind/discussions/categories/general) 里发帖。
