### ISSUE TITLE
能否添加异步载入数据的方式？

### ISSUE THREAD

**Issue by linchen1102** [hizzgdev/jsmind#65]
在点击打开节点的加号时，能否在这里添加方法使得能够异步加载数据。有的时候数据量非常大想在点击打开节点的时候载入数据

**Comment by hizzgdev** [comment]
这个功能在现有情况下就能做到。参考以下思路：

1. 需要异步加载的节点，首次展示时设为折叠状态，并添加一个临时节点；
2. 监听”加号“点击事件，异步加载数据后，通过API删除临时节点，并添加异步返回的数据

**Comment by asdfghjkl01** [comment]
@linchen1102 请问异步载入数据的方式实现了吗，能不能共享下代码

**Comment by hizzgdev** [comment]
@DiSheng1994 用 dom 事件就可以了。这个元素大概长这样：

```html
<jmexpander nodeid="sub2">-</jmexpander>
```

里面也有 nodeid 可供你使用。
