### ISSUE TITLE
请教3个小问题: number型id/监听事件/扩展连线

### ISSUE THREAD

**Issue by gmxyb** [hizzgdev/jsmind#68]
首先非常感谢作者的辛勤劳动！我这里有3个小问题想请教一下：
1. 表对象的 id，parentid 貌似不能使用 number，这算是个小缺陷
2. 没有找到关于事件的说明，不知道如何监听例如select/unselect节点，展开/收拢等等事件，能不能通过事件阻止展开/收拢？
3. 不知道能不能提供一些“画连线功能”的api，能自己实现在非父子节点间画线。

谢谢~

**Comment by hizzgdev** [comment]
@gmxyb

感谢你的支持。

第一个问题，如果确实需要的话，你可以改进一下，但是要注意js在数字和字符串比较时的特点，不能把节点1和节点“1”当成同一个节点了。

第二个问题，本来这个在计划里，但是后来发现通过监视dom很容易就实现了，做api的话可能会增加学习成本，所以暂时还没有加，想先看看大家反馈的情况再做决定。

第三个问题，画线这个需求看似简单，又很不简单，直线很容易，但是实用性不强，曲线用处广，可是画起来又比较复杂，如果项目需要的话，你可以拿到canvas对象先进行绘制，看看能不能从你的项目中总结出需要的线型，我给加进去。

**Comment by gmxyb** [comment]
回复的好快~~ 

1. 我的意思是，应该允许使用number(整形的)的id, parentid，但是内部都转成string而不是直接报错，另外，对于root节点，其实可以不必要加isroot=true，可以更加智能点，找不到 parentid 的就是 root（丢弃多余的），这样从数据库生成数据更规整。

2. 节点 topic 是html的好处理，可是象select/unselect，展开/收拢 之类的好像不知道如何监听啊~~

3. 粗看了下源码，确实可以用 canvas 绘制。那么如何取节点的位置属性呢？如果没有 展开/收拢事件，如何做到绘制的同步处理呢？

^_^~

**Comment by hizzgdev** [comment]
1. 报错就不应该了，我回头看一下，作为一个bug处理一下。

2. isroot这个是我刻意加的，让使用者显式指定，以避免错误的认定根节点，对于tree方式，就没有这个属性了。

3. 这些事件确实提供一下比较好，暂时可以先用dom的click代替。

4. 如果需要根据节点坐标画线的话，我想应该需要知道很多坐标才行，你看一下运行期的jsmind对象，有很多隐藏的属性供你参考。

**Comment by gmxyb** [comment]
好的。我在研究研究~ 谢谢了！

**Comment by hizzgdev** [comment]
resolve https://github.com/hizzgdev/jsmind/commit/dc5c12d69528aa62c589322a670b3a251808ffb4
