### ISSUE TITLE
node的topic如果过长或者存在多行时，显示不出来

### ISSUE THREAD

**Issue by zjg23** [hizzgdev/jsmind#69]

**Comment by zjg23** [comment]
![image](https://cloud.githubusercontent.com/assets/12578973/21792325/dd5a100c-d723-11e6-910c-e918d7f2114f.png)

**Comment by hizzgdev** [comment]
@zjg23 
为保持图形显示整齐，特意设置了每个节点的最大长度，如果需要多行显示的话，请参考这个内容进行调整 https://github.com/hizzgdev/jsmind/wiki/HotTopic-ShowMultiLineText

**Comment by hizzgdev** [comment]
@zjg23 如果问题解决，请关闭此 issue

**Comment by zjg23** [comment]
已解决，3Q
