### ISSUE TITLE
是否支持zoomin和zoomout？是的，支持。

### ISSUE THREAD

**Issue by lqm229026** [hizzgdev/jsmind#70]
请问在jsmind中能否支持放大和缩小呢？在不改变整个网页大小的前提下。
因为我是想将jsmind作为页面的一个局部进行展示，但是脑图太大的时候翻阅有点麻烦。

**Comment by hizzgdev** [comment]
@lqm229026 有些刚实现不久的功能还没有更新到文档里。你参考一下项目中的`example/2_features.html` 或者直接访问 http://hizzgdev.github.io/jsmind/example/2_features.html ，可以看到有放大和缩小的接口：[6.C] zoom in/out

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/57830814-dbc75280-77e5-11e9-9091-a94f9342bad7.png)

放大之后视野受限 :cry:
