### ISSUE TITLE
拖动节点

### ISSUE THREAD

**Issue by mybydhn** [hizzgdev/jsmind#75]
在拖动节点的时候遇到一个问题 选中之后 进行拖动的时候  鼠标未变成可移动的那个样式，也无法进行拖动。再进行刷新一下就又可以拖动了。

**Comment by hizzgdev** [comment]
并没有能重现你所描述的现象，能否具体描述一下。
@mybydhn

**Comment by huoji555** [comment]
可能是你禁用了编辑节点，然后在拖拽时获取node时，就不能够获取到节点，取消编辑节点即可
