### ISSUE TITLE
节点批注功能

### ISSUE THREAD

**Issue by lqm229026** [hizzgdev/jsmind#76]
请问有没有计划实现xmind中那种给节点添加批注的功能呢？
或者简单点，单纯显示批注的功能。

**Comment by hizzgdev** [comment]
@lqm229026 

https://github.com/hizzgdev/jsmind/blob/master/docs/zh/3.operation.md#34-编辑节点

每个节点都有一个 data 字段供你使用，但是 jsmind 可能不能提供显示这些数据的功能，你可以监听一下节点的点击之类的事件，获取 data 后自行显示出来。

**Comment by lqm229026** [comment]
@hizzgdev 
恩，这种通过点击显示的解决方案我们之前也讨论过，不过对于我们的应用场景还是有点不太适合。看来得想一些别的办法了~~感谢您的回复。
