### ISSUE TITLE
报错：Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SuperMary001** [hizzgdev/jsmind#78]
显示正常：
![c04 rafldl7fnx d2k jcw](https://cloud.githubusercontent.com/assets/22342802/23981256/0f577f64-0a40-11e7-8286-f6396ea8ab71.png)

下面是部分数据：
![p5v d vrf8l9 2udd st tg](https://cloud.githubusercontent.com/assets/22342802/23981259/14c8f8a6-0a40-11e7-87f5-66ad563bffe1.png)

报错：Maximum call stack size exceeded 
![2r 0 1of 1cq 1ju4 62g](https://cloud.githubusercontent.com/assets/22342802/23981110/1f2dbd78-0a3f-11e7-81bd-73c3648d9e10.png)

我把下面这段代码注释掉了，不然会一直提示到上千条警告，然后网页崩溃掉。
logger.warn('the node[id='+nodeid+'] can not be found'); 
![u o 4 166991uloa i8 2e](https://cloud.githubusercontent.com/assets/22342802/23981127/36caa91e-0a3f-11e7-8ea0-196da7c717d4.png)

**Comment by hizzgdev** [comment]
这是哪里报的错？

**Comment by hizzgdev** [comment]
@SuperMary001 
这个错误是 jsmind 对传入的 parent_node 没有经过检查导致的。你的数据中应该有些node有问题。获取最新版本后，便可在控制台看到是哪些数据有问题了。

感谢你的支持！
