### ISSUE TITLE
NPM package doesn't work

### ISSUE THREAD

**Issue by jt-wang** [hizzgdev/jsmind#83]
Hi there, I found jsmind quite useful in its convenience as well as its simplicity beauty. Many thanks for your work. However, the NPM package of this repo does not work as expected. 

I examined the directories of the package, and realized that the cause is that it does not conform to the export consensus of NPM package.

This package exports `jsmind.js` only, while **`jsmind.js` doesn't export any constructor**. Indeed, `jsmind.js`, as well as other `jsmind.*.js`, are written for purely html injection instead of node `require()`. It binds itself directly to the window object without any exportation of constructor or so on, which prevents users from using it in customized `app.js` like `let jsMind = require('jsmind')`.

Therefore, I suggest that there can be a kind refactor, or at least an explicit documentation of this uncommon NPM package.

Many thanks.

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/pull/98
