### ISSUE TITLE
是否动态设置分支（从父节点到子节点的线）的颜色宽度等style？

### ISSUE THREAD

**Issue by vitoFantasy** [hizzgdev/jsmind#86]
我想利用颜色对不同的分支加以区别，比如有些分支我希望加深颜色，有些分支我希望加浅颜色？ 改起来的难度如何呀， 能够给一些建议， 谢谢啦

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/3.operation.md#35-设置样式
