### ISSUE TITLE
怎样给数据变化增加一次监听事件，实现撤销和重做的功能？

### ISSUE THREAD

**Issue by fengnovo** [hizzgdev/jsmind#89]
怎样给数据变化增加一次监听事件，实现撤销和重做的功能？我想每次数据变化后能缓存整个数据，当点击撤销时可以按数据还原上一次操作。

**Comment by hizzgdev** [comment]
可在编辑节点时输出一个事件，把操作记录起来，撤销的话就根据操作历史，进行反向操作……
