### ISSUE TITLE
多个节点能形成一个节点组么？这些节点用一个虚框的园包裹起来。

### ISSUE THREAD

**Issue by mokeyish** [hizzgdev/jsmind#90]
![baidushurufa_2017-6-14_10-30-46](https://user-images.githubusercontent.com/16131917/27112960-960e15ca-50ec-11e7-8ff1-5f4d4ca1e3d2.png)

想这个图片一样。

**Comment by hizzgdev** [comment]
目前不支持，需要二次开发。
非常建议你自行处理。如果有可能，还忘能收到你的 pull-request。
