### ISSUE TITLE
使用node array作为数据类型时，js.resize函数失效了

### ISSUE THREAD

**Issue by hanxiaomax** [hizzgdev/jsmind#91]
是个bug吗

**Comment by hanxiaomax** [comment]
应该不是 bug ，但是似乎调用 jm.resize 的时候，计算中心位置是以全部节点展开后的大小来计算的？似乎和第一次加载时计算的不一样。有没有其他办法，让导图始终居中？尤其是当一侧的节点深度明显大于另一侧时？

**Comment by hizzgdev** [comment]
是的，中心是以全部展开后的大小来计算的。但是提供了一个 _center_root 方法，你看看源码，了解一下能否解决你的需求。

**Comment by hanxiaomax** [comment]
谢谢，我去了解一下

**Comment by hizzgdev** [comment]
此issue先关闭了。如需要请再次打开。
