### ISSUE TITLE
绑定事件

### ISSUE THREAD

**Issue by xutaogit** [hizzgdev/jsmind#92]
目前是react项目中，如何在jsmind树每个节点上绑定事件。
例如单击事件，获取对应节点对象，或者能否在双击的时候做其他事情。
（ps：当前项目默认单击节点会变色应该是单击事件的体现。）

有看到jsmind对象返回的click_handle方法，该如何使用？

**Comment by hizzgdev** [comment]
本来想完善一下这些事件，但是感觉还是不如你们自己绑定。
用 react 的话，jsmind 不能提供像 react 那样的事件机制，需要你直接在 dom 上进行事件绑定和处理。
