### ISSUE TITLE
在tab-pane里canvas的宽高失效了

### ISSUE THREAD

**Issue by hackerxiaobai** [hizzgdev/jsmind#93]
结合bootstrap来做将jsMind的div放在tab-pane里。canvas的宽高不起作用了

**Comment by hizzgdev** [comment]
jsmind_container 这个元素的宽高建议是绝对尺寸，它用来确定画布的大小。
如果采用 bootstrap 布局的话， 画布的大小随时会变，线条和节点布置就需要时时重绘，会十分影响脑图的显示效率。
如果你希望脑图的大小能随着页面的大小调整，建议你监听浏览器的事件，动态设置 jsmind_container 的宽高。
