### ISSUE TITLE
数据格式问题

### ISSUE THREAD

**Issue by MrZhangFengfeng** [hizzgdev/jsmind#95]
请教一个问题，例子中给的格式内都是有id，parentid，topic的，如果后台给一个数据量很大的并且没有这些key的数据，该怎么处理？谢谢

**Comment by hizzgdev** [comment]
id, parentid 用来标识节点之间的关系，也便于后续把节点数据回写到后台。如果你的业务中并没有这些id，那你也总可以编出一些id来，但是仍然需要建立节点上下级的关系。

**Comment by MrZhangFengfeng** [comment]
就是说id ，parentid ，topic， children等属于关键字，是必需要有的，如果没有 我就自己来添加上，是这样 吗？

**Comment by hizzgdev** [comment]
参考文档： https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md#12-数据格式
文档中描述的数据格式可以看做是 **一种要求**，你需要按此要求组织你的数据。
根据你的描述，我觉得 **表对象格式** 可能更符合你业务场景。

数据结构中每个字段的含义请参考文档： https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md#注

**Comment by MrZhangFengfeng** [comment]
好的，谢谢了。
